export const meta = {
  name: 'build-idea',
  description: 'From a committed feature brief to a running feature and a DRAFT PR: plan, implement in slices, gate, ONE quick "does it work" check, hand the task to the human — no device pass',
  whenToUse: 'The Exp build: launched from the vitrinka-experimental build-idea skill once the brief is committed; runs unattended until the draft PR is open and the hand-back names what to poke at. The thorough device pass is a separate decision (vitrinka-experimental:test).',
  phases: [
    { title: 'Plan', detail: 'the brief into ≤4 disjoint implementation slices, a scope and a main journey' },
    { title: 'Implement', detail: 'one agent per slice, same worktree, then the gates' },
    { title: 'Quick check', detail: 'start the app, open the changed routes once at desktop, walk the main journey, one small board' },
    { title: 'Ship', detail: 'the draft PR, the hand-back' },
  ],
}
// Code generated by tools/gen-workflows from experimental/workflows-src/flows/build-idea.js. DO NOT EDIT.
// Edit the flow or its lib/ fragments under experimental/workflows-src/, then `go run ./tools/gen-workflows`.
// ---- lib/preamble.js — the lines every Exp agent prompt starts with
// Agents already carry the repo's CLAUDE.md; these name only what a
// workflow stage needs beyond it. Keep it to contracts, never procedure —
// procedure is served by the vitrinka server (`docs {topic}`) and the CLI's
// `--help`. Exp differs from core in ONE line: apps run where the repo's run
// target says, never where a rule of thumb assumes.
const PREAMBLE = [
  'You are one stage of a vitrinka workflow. Your final text IS the return value: return raw data for the schema, never a human-facing report.',
  'Work in the current checkout (a worktree). Never switch branches, never stash, never touch the main checkout.',
  'Apps run where the run target says: the Prepare stage resolved `.claude/vitrinka-workflows.json` → `run.web` and hands you `where` (devbox | local) and `baseUrl`; `devbox` means `devbox run -- \'<cmd>\'` on this branch\'s workspace, `local` means this machine. Simulator work (iOS, Android) always runs on this machine. Say so in `problems` when you had to deviate.',
  'Every vitrinka board/task link you return is the server-returned `url`, verbatim — never composed, never shortened.',
  'Browser work: onyx `browser_start(session: $CLAUDE_CODE_SESSION_ID)` first, headless, then playwright; screenshots land in the capture root you were given, never the repo root.',
  'When a door refuses (4xx with a diagnosis), apply the corrected call it names once; a second refusal is a `problems` entry, not a workaround.',
].join('\n')

function withPreamble(prompt) {
  return PREAMBLE + '\n\n' + prompt
}
// ---- lib/run.js — the run target: where a run starts the app
// `.claude/vitrinka-workflows.json` → `run: { web: "auto" | "devbox" | "local" }`.
// `auto` (the default) picks the devbox when `devbox` resolves a workspace
// for this branch, else this machine. Simulator lanes (iOS, Android) are
// always local — the simulator lives here. Nobody assumes a devbox exists:
// vitrinka is a SaaS and most teams have none.
const RUN_TARGETS = ['auto', 'devbox', 'local']

function resolveRun(override) {
  const web = override && override.run && RUN_TARGETS.indexOf(override.run.web) >= 0 ? override.run.web : 'auto'
  return { web }
}

// The rule the Prepare stage applies, as prompt text. It reads the file
// itself (a script cannot), so the whole ladder travels with the prompt.
const RUN_RULE =
  'Run target: read `.claude/vitrinka-workflows.json` and take `run.web` (`auto` when the file or the key is absent). ' +
  '`auto`: start the app on this branch\'s devbox workspace when `devbox` resolves one (`devbox run -- \'<cmd>\'`), otherwise locally on this machine. ' +
  '`devbox`: the devbox only — an unresolved devbox is a `problems` entry with `baseUrl` empty, never a silent local fallback. ' +
  '`local`: this machine only, never a devbox. Return `where` as devbox | local and the file\'s content as `override` ({} when absent).'
// ---- lib/schemas.js — structured-output schemas shared by the Exp flows
const ROUTE = {
  type: 'object',
  properties: {
    path: { type: 'string' },
    title: { type: 'string' },
    file: { type: 'string', description: 'repo-relative implementing file' },
    auth: { type: 'string', description: 'none | user | admin | <role>' },
    setup: { type: 'string', description: 'how to reach it with data on screen (seed, fixture, deep link)' },
  },
  required: ['path', 'title'],
}

const JOURNEY = {
  type: 'object',
  properties: {
    title: { type: 'string' },
    steps: { type: 'array', items: { type: 'string' } },
    roles: { type: 'array', items: { type: 'string' } },
  },
  required: ['title', 'steps'],
}

const TERRAIN_SCHEMA = {
  type: 'object',
  properties: {
    projectType: { type: 'string', enum: ['web', 'expo', 'cli', 'other'] },
    routes: { type: 'array', items: ROUTE },
    journeys: { type: 'array', items: JOURNEY },
    extendPoints: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, file: { type: 'string' }, why: { type: 'string' } }, required: ['what', 'file'] } },
    duplicationRisks: { type: 'array', items: { type: 'object', properties: { risk: { type: 'string' }, existing: { type: 'string' } }, required: ['risk', 'existing'] } },
    openQuestions: { type: 'array', items: { type: 'string' } },
    terrainUrl: { type: 'string' },
    boardUrl: { type: 'string' },
  },
  required: ['projectType', 'routes'],
}

const FINDING = {
  type: 'object',
  properties: {
    key: { type: 'string' },
    id: { type: 'integer', description: 'annotation id from the annotate receipt' },
    cardId: { type: 'integer' },
    route: { type: 'string' },
    lane: { type: 'string', description: 'the lane key the finding was seen in' },
    state: { type: 'string', description: 'capture state for the iOS lane (default | keyboard | scrolled | scroll-end | landscape | overscroll)' },
    area: { type: 'string', description: 'route, component or subsystem the fix lives in' },
    kind: { type: 'string', enum: ['finding', 'suggestion'] },
    severity: { type: 'string', enum: ['blocker', 'major', 'minor'] },
    rule: { type: 'string' },
    summary: { type: 'string' },
    files: { type: 'array', items: { type: 'string' } },
    inScope: { type: 'boolean', description: 'false when the defect lives outside the feature scope the run was given' },
  },
  required: ['key', 'area', 'kind', 'severity', 'summary'],
}

const FINDINGS_SCHEMA = {
  type: 'object',
  properties: {
    lane: { type: 'string' },
    findings: { type: 'array', items: FINDING },
    regressions: { type: 'array', items: { type: 'object', properties: { id: { type: 'integer' }, key: { type: 'string' }, fixed: { type: 'boolean' }, note: { type: 'string' } }, required: ['key', 'fixed'] } },
    screensRead: { type: 'integer' },
    boardUrl: { type: 'string' },
  },
  required: ['findings'],
}

const SHOOT_SCHEMA = {
  type: 'object',
  properties: {
    lane: { type: 'string' },
    shots: { type: 'array', items: { type: 'object', properties: { route: { type: 'string' }, state: { type: 'string' }, label: { type: 'string' }, file: { type: 'string' } }, required: ['route', 'label'] } },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['lane', 'shots'],
}

const USERTEST_SCHEMA = {
  type: 'object',
  properties: {
    qaTaskUrl: { type: 'string' },
    boardUrl: { type: 'string' },
    cases: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, lane: { type: 'string' }, verdict: { type: 'string', enum: ['pass', 'fail', 'skip'] }, note: { type: 'string' }, files: { type: 'array', items: { type: 'string' } } }, required: ['title', 'verdict'] } },
    bugs: { type: 'array', items: { type: 'string', description: 'task url of each bug filed' } },
  },
  required: ['cases'],
}

const FIX_SCHEMA = {
  type: 'object',
  properties: {
    fixed: { type: 'array', items: { type: 'string', description: 'finding key' } },
    skipped: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, why: { type: 'string' } }, required: ['key', 'why'] } },
    touchedRoutes: { type: 'array', items: { type: 'string' } },
    touchedFiles: { type: 'array', items: { type: 'string' } },
    commits: { type: 'array', items: { type: 'string' } },
  },
  required: ['fixed', 'skipped', 'touchedRoutes', 'touchedFiles'],
}

const GATE_SCHEMA = {
  type: 'object',
  properties: {
    green: { type: 'boolean' },
    ran: { type: 'array', items: { type: 'string' } },
    failures: { type: 'array', items: { type: 'string' } },
    repaired: { type: 'boolean' },
  },
  required: ['green', 'ran'],
}

const PREPARE_SCHEMA = {
  type: 'object',
  properties: {
    baseUrl: { type: 'string', description: 'reachable app url; empty only when no web lane needs one or the run target could not be honoured' },
    where: { type: 'string', enum: ['devbox', 'local'] },
    branch: { type: 'string' },
    sha: { type: 'string', description: 'short HEAD sha' },
    project: { type: 'string' },
    task: { type: 'string', description: 'vitrinka task id the run is bound to' },
    override: { type: 'object', description: 'parsed .claude/vitrinka-workflows.json or {}' },
    projectType: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['where', 'branch', 'projectType'],
}

const PUBLISH_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    section: { type: 'string' },
    cards: { type: 'array', items: { type: 'object', properties: { cardId: { type: 'integer' }, route: { type: 'string' }, lane: { type: 'string' }, state: { type: 'string' }, label: { type: 'string' } }, required: ['cardId'] } },
  },
  required: ['boardUrl', 'boardSlug', 'section', 'cards'],
}

// The quick check of Exp build-idea: one desktop pass plus one journey walk.
const QUICKCHECK_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    routes: { type: 'array', items: { type: 'object', properties: { route: { type: 'string' }, verdict: { type: 'string', enum: ['works', 'broken', 'unreachable'] }, note: { type: 'string' }, cardId: { type: 'integer' } }, required: ['route', 'verdict'] } },
    journey: { type: 'object', properties: { title: { type: 'string' }, verdict: { type: 'string', enum: ['works', 'broken', 'skipped'] }, note: { type: 'string' }, steps: { type: 'array', items: { type: 'object', properties: { step: { type: 'string' }, verdict: { type: 'string' }, note: { type: 'string' } }, required: ['step', 'verdict'] } } }, required: ['verdict'] },
    shots: { type: 'integer' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['routes', 'journey'],
}

// The lanes door receipt: the run board and one child board per lane.
const RUNBOARD_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    lanes: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, slug: { type: 'string' }, url: { type: 'string' } }, required: ['key', 'slug', 'url'] } },
  },
  required: ['boardUrl', 'boardSlug', 'lanes'],
}

// The run door result: the qa task and the bugs it filed.
const RUNDOOR_SCHEMA = {
  type: 'object',
  properties: {
    qaTaskUrl: { type: 'string' },
    lanes: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, published: { type: 'boolean' }, note: { type: 'string' } }, required: ['key', 'published'] } },
    bugs: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, url: { type: 'string' } }, required: ['url'] } },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['lanes', 'bugs'],
}
// ---- lib/helpers.js — plain-code helpers shared by the Exp flows (no agents here)
const SEVERITY_RANK = { blocker: 3, major: 2, minor: 1 }

// Findings the loop fixes on its own: defects at or above the threshold.
// Suggestions and anything below stay staged on the board for the human.
function autoAcceptable(findings, threshold) {
  const min = SEVERITY_RANK[threshold] || SEVERITY_RANK.minor
  return findings.filter(f => f.kind === 'finding' && (SEVERITY_RANK[f.severity] || 0) >= min)
}

// Group findings by area into at most `max` disjoint fix lists. A finding
// whose files also appear in another area is `shared` and runs first, so
// the parallel fixers never edit the same file.
function groupByArea(findings, max) {
  const byArea = new Map()
  for (const f of findings) {
    const area = f.area || 'misc'
    if (!byArea.has(area)) byArea.set(area, [])
    byArea.get(area).push(f)
  }
  const fileOwners = new Map()
  for (const [area, list] of byArea) {
    for (const f of list) for (const file of f.files || []) {
      if (!fileOwners.has(file)) fileOwners.set(file, new Set())
      fileOwners.get(file).add(area)
    }
  }
  const shared = []
  for (const [area, list] of byArea) {
    const keep = []
    for (const f of list) {
      const crosses = (f.files || []).some(file => fileOwners.get(file).size > 1)
      if (crosses) shared.push(f); else keep.push(f)
    }
    byArea.set(area, keep)
  }
  let groups = [...byArea].filter(([, l]) => l.length).map(([area, list]) => ({ area, findings: list }))
  groups.sort((a, b) => b.findings.length - a.findings.length)
  while (groups.length > max) {
    const tail = groups.pop()
    const smallest = groups[groups.length - 1]
    smallest.area = smallest.area + '+' + tail.area
    smallest.findings.push(...tail.findings)
  }
  return { shared: shared.length ? { area: 'shared', findings: shared } : null, groups }
}

function uniq(list) {
  return [...new Set(list.filter(Boolean))]
}

function key(f) {
  return f.key || (f.cardId + ':' + f.summary)
}

function slugify(s) {
  return String(s || '').replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase()
}
// args: { brief: string (repo-relative path), task: string, project?: string, base?: 'main' }
const A = args || {}
if (!A.brief) throw new Error('build-idea: args.brief (the committed brief\'s repo-relative path) is required')
if (!A.task) throw new Error('build-idea: args.task (the epic or story the brief belongs to) is required')
for (const k of ['cap', 'severity', 'matrix', 'lanes']) {
  if (A[k] !== undefined) throw new Error(`build-idea: args.${k} is not a build decision — the Exp build has no device pass; run vitrinka-experimental:test after the human has looked`)
}

const PLAN_SCHEMA = {
  type: 'object',
  properties: {
    slices: {
      type: 'array',
      maxItems: 4,
      items: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          goal: { type: 'string' },
          files: { type: 'array', items: { type: 'string' }, description: 'files this slice owns; disjoint from every other slice' },
          dependsOn: { type: 'array', items: { type: 'string' } },
          acceptance: { type: 'array', items: { type: 'string' } },
          tests: { type: 'array', items: { type: 'string' }, description: 'tests to write or extend, in the repo\'s own framework' },
        },
        required: ['name', 'goal', 'files', 'acceptance'],
      },
    },
    shared: { type: 'object', properties: { goal: { type: 'string' }, files: { type: 'array', items: { type: 'string' } } }, description: 'schema, types, shared components every slice needs — built first, empty when none' },
    scope: { type: 'string', description: 'one paragraph: what a later test run should cover' },
    scopeFiles: { type: 'array', items: { type: 'string' }, description: 'every file the feature owns — the boundary later fixers respect' },
    routes: { type: 'array', items: ROUTE, description: 'routes the feature adds or changes, with how to reach each with data on screen' },
    journey: JOURNEY,
  },
  required: ['slices', 'scope', 'routes', 'journey'],
}

const IMPL_SCHEMA = {
  type: 'object',
  properties: {
    slice: { type: 'string' },
    done: { type: 'array', items: { type: 'string' } },
    left: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, why: { type: 'string' } }, required: ['what', 'why'] } },
    files: { type: 'array', items: { type: 'string' } },
    commits: { type: 'array', items: { type: 'string' } },
  },
  required: ['slice', 'done', 'left', 'files'],
}

const PR_SCHEMA = {
  type: 'object',
  properties: {
    pr: { type: 'string', description: 'the PR url, empty when none was opened' },
    draft: { type: 'boolean' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['pr'],
}

phase('Plan')
const plan = await agent(withPreamble(
  `Read the feature brief at ${A.brief} (and the terrain artifact it links, if any). Plan its implementation for THIS repo as at most 4 slices that can be built in parallel in one worktree: each slice owns a disjoint set of files; anything two slices need (schema/migration, types, a shared component, a door) goes into \`shared\`, built first. Every slice lists its acceptance criteria as observable behaviour and the tests it writes in the repo's own framework. Honour the repo's laws (CLAUDE.md, the project memory files whose triggers match) — a plan that fights a law is wrong. Also return: the routes the feature adds or changes (path, title, file, auth, how to reach each with data on screen), the ONE main journey a human walks to see the feature work (title + concrete steps), the feature's scope files, and one paragraph of what a later test run should cover. Read-only: change nothing.`
), { label: 'plan', phase: 'Plan', schema: PLAN_SCHEMA })
if (!plan || !plan.slices.length) throw new Error('build-idea: planning produced no slices')
log(`build-idea: ${plan.slices.length} slices${plan.shared && plan.shared.files && plan.shared.files.length ? ' + shared' : ''}, ${plan.routes.length} routes, journey "${plan.journey.title || 'main'}"`)

phase('Implement')
const implPrompt = (s, isShared) => withPreamble(
  `Implement ${isShared ? 'the SHARED foundation' : `slice "${s.name}"`} of the feature in ${A.brief} (task ${A.task}), in this worktree.\n` +
  `Goal: ${s.goal}\nFiles you own: ${JSON.stringify(s.files)}\n${s.acceptance ? `Acceptance: ${JSON.stringify(s.acceptance)}\n` : ''}${s.tests ? `Tests to write/extend: ${JSON.stringify(s.tests)}\n` : ''}` +
  (isShared ? 'Other slices build on what you leave; keep it minimal and typed.' : 'Other slices are being built in this same checkout right now: never edit files outside your list, never reformat shared code; a need outside your files is a `left` item with why.') +
  ` A defect you notice outside the feature's scope is NOT yours: name it in \`left\` with why "off-scope" — never fix it here. Commit per coherent unit with a trailer naming the task. Return what is done, what is left and why, files and commits.`
)
const impl = []
if (plan.shared && plan.shared.files && plan.shared.files.length) {
  impl.push(await agent(implPrompt(plan.shared, true), { label: 'implement:shared', phase: 'Implement', schema: IMPL_SCHEMA }))
}
impl.push(...await parallel(plan.slices.map(s => () => agent(implPrompt(s, false), { label: `implement:${s.name}`, phase: 'Implement', schema: IMPL_SCHEMA }))))
const built = impl.filter(Boolean)
const left = built.flatMap(r => r.left.map(l => ({ slice: r.slice, ...l })))
const offScope = left.filter(l => /off-scope/i.test(l.why || ''))
const todo = left.filter(l => !/off-scope/i.test(l.why || ''))
log(`build-idea: ${built.length} slices built, ${todo.length} items left, ${offScope.length} off-scope defects spotted`)

if (todo.length) {
  const sweep = await agent(withPreamble(
    `Finish what the slice builders left in this worktree (feature ${A.brief}, task ${A.task}): ${JSON.stringify(todo)}. Everything is yours now — no other agent edits this checkout. An item that needs a product decision is left with why; an off-scope defect stays off-scope. Commit. Return done/left/files/commits.`
  ), { label: 'implement:sweep', phase: 'Implement', schema: IMPL_SCHEMA })
  if (sweep) built.push(sweep)
}

const gate = await agent(withPreamble(
  `Gate the implementation: run every type/build/test gate CLAUDE.md names, where it says they run, plus the tests the slices wrote. Repair and commit what this branch broke; report what predates it. Return green, what ran, failures.`
), { label: 'gate', phase: 'Implement', schema: GATE_SCHEMA })
if (!gate || !gate.green) log(`build-idea: implementation gate red — ${JSON.stringify((gate && gate.failures) || ['no result'])}; continuing so the quick check shows the state`)

phase('Quick check')
const prep = await agent(withPreamble(
  `Prepare the quick check of the feature on this branch.\n` +
  `1. Report the current branch, the short HEAD sha and the vitrinka project the repo is bound to (\`vitrinka status\` / the repo's .vitrinka descriptor).\n` +
  `2. ${RUN_RULE}\n` +
  `3. Decide projectType (web | expo | cli | other) from the repo.\n` +
  `4. Start the app for this branch there; wait until it answers; return the reachable base URL. The run is bound to task ${A.task}.\n` +
  `Never create tasks, boards or commits here.`
), { label: 'prepare', phase: 'Quick check', schema: PREPARE_SCHEMA })
if (!prep) throw new Error('build-idea: prepare failed')
const run = resolveRun(prep.override)
const boardSlug = `${slugify(prep.branch)}-quick-check`
const captureRoot = '.vitrinka/screenshots/quick-check'
log(`build-idea: quick check on ${prep.branch} at ${prep.baseUrl || '(no app)'} (${prep.where}, run.web=${run.web})`)

let quick = { boardUrl: '', boardSlug, routes: plan.routes.map(r => ({ route: r.path, verdict: 'unreachable', note: 'quick check did not run' })), journey: { title: plan.journey.title, verdict: 'skipped', note: 'quick check did not run' }, shots: 0, problems: [] }
if (!prep.baseUrl) {
  quick.problems = (prep.problems || []).concat(['no app url — the run target could not be honoured'])
  log('build-idea: no app url — the quick check is skipped and the hand-back says so')
} else {
  const shot = await agent(withPreamble(
    `ONE quick "does it work" check of the feature (task ${A.task}) against ${prep.baseUrl} — desktop only, 1440×810@2, mouse. This is not a review: no findings, no matrix, no second pass.\n` +
    `Routes (open every one with data on screen; a route's \`setup\` says how):\n${JSON.stringify(plan.routes)}\n` +
    `Main journey to walk once:\n${JSON.stringify(plan.journey)}\n` +
    `Read \`docs {topic: "guide:publish-capture"}\` first. For each route: open it at exactly that viewport, wait for it to settle, scroll the whole page once, capture 2× and adopt it with \`vitrinka board capture web --file <png> --route <path> --device desktop --viewport 1440x810@2 --label quick/<route-slug> --title "<title>" --note "<what is on screen>" --src <implementing file> --root ${captureRoot} --yes\`; then judge it works | broken | unreachable with one line of why (a console error, a blank region or a failed request is broken). Walk the journey step by step, capturing after each step under label quick/journey/<n>, and judge each step; the journey is broken when any step is.\n` +
    `Then publish everything onto board ${boardSlug}${prep.project ? ` (project ${prep.project})` : ''} bound to task ${A.task}: ONE section "Quick check" — the route shots in route order, the journey shots after them, and beside each route a verdict card (works | broken + the line of why); a summary card at the head naming the branch, the sha ${prep.sha || ''}, the route count and the tally. Return the board's server url and slug, every route verdict with its card id, the journey verdict with its steps, the shot count and problems.`
  ), { label: 'quick-check', phase: 'Quick check', schema: QUICKCHECK_SCHEMA })
  if (shot) quick = shot
}
const broken = quick.routes.filter(r => r.verdict !== 'works')
log(`build-idea: quick check — ${quick.routes.length - broken.length}/${quick.routes.length} routes work, journey ${quick.journey.verdict}${quick.boardUrl ? ` → ${quick.boardUrl}` : ''}`)

phase('Ship')
const pr = await agent(withPreamble(
  `Open a DRAFT pull request for this branch through the prm skill (Skill tool: prm) with \`--draft\`, base ${A.base || 'main'}, bound to task ${A.task}. The body names the brief (${A.brief}), the quick-check board ${quick.boardUrl || '(none)'} and that the UI is unreviewed by design — the device pass is a separate decision. Never merge, never mark ready. Return the PR url.`
), { label: 'pr', phase: 'Ship', schema: PR_SCHEMA })
log(`build-idea: draft PR ${pr && pr.pr ? pr.pr : 'not opened'}`)

const handback = await agent(withPreamble(
  `Hand task ${A.task} back through the vitrinka handoff skill (Skill tool: vitrinka:handoff). Facts, one per line, for the summary:\n` +
  JSON.stringify({
    brief: A.brief,
    slices: built.map(b => ({ slice: b.slice, done: b.done.length, left: b.left.length })),
    implementationGate: gate && gate.green,
    quickCheck: { board: quick.boardUrl, routes: quick.routes, journey: quick.journey, problems: quick.problems },
    app: { url: prep.baseUrl, where: prep.where, branch: prep.branch },
    offScope,
    pr: pr && pr.pr,
    draft: true,
  }) +
  `\nThe hand-back names the running app url, the parked state (which route the journey ended on) and what to poke at (the routes and the journey). Broken routes are facts in the summary, not children. Off-scope defects (${offScope.length}) become spotted children. \`next\` holds exactly two steps for the human: look at the feature, then run /vitrinka-experimental:test to choose the device pass. Never mark the PR ready. Return the rendered hand-back block verbatim.`
), { label: 'handback', phase: 'Ship' })

return {
  plan: plan.slices.map(s => s.name),
  gate: gate && gate.green,
  app: prep.baseUrl,
  board: quick.boardUrl,
  routes: quick.routes,
  journey: quick.journey.verdict,
  pr: pr && pr.pr,
  handback,
}
