export const meta = {
  name: 'build-idea',
  description: 'From a committed feature brief to a running feature and a DRAFT PR: plan, implement in slices, gate, ONE quick "does it work" check, hand the task to the human — no device pass',
  whenToUse: 'The Exp build: launched from the vitrinka-experimental build-idea skill once the brief is committed; runs unattended until the draft PR is open and the hand-back names what to poke at. The thorough device pass is a separate decision (vitrinka-experimental:test).',
  phases: [
    { title: 'Plan', detail: 'the brief into ≤4 disjoint implementation slices, a scope and a main journey' },
    { title: 'Implement', detail: 'one agent per slice, same worktree, then the gates' },
    { title: 'Quick check', detail: 'start the app, open the changed routes once at desktop, walk the main journey, one small board' },
    { title: 'Ship', detail: 'the draft PR, the hand-back' },
  ],
}
// Code generated by tools/gen-workflows from experimental/workflows-src/flows/build-idea.js. DO NOT EDIT.
// Edit the flow or its lib/ fragments under experimental/workflows-src/, then `go run ./tools/gen-workflows`.
// ---- lib/preamble.js — the lines every Exp agent prompt starts with
// Agents already carry the repo's CLAUDE.md; these name only what a
// workflow stage needs beyond it. Keep it to contracts, never procedure —
// procedure is served by the vitrinka server (`docs {topic}`) and the CLI's
// `--help`. Exp differs from core in ONE line: apps run where the repo's run
// target says, never where a rule of thumb assumes.
const PREAMBLE = [
  'You are one stage of a vitrinka workflow. Your final text IS the return value: return raw data for the schema, never a human-facing report.',
  'Work in the current checkout (a worktree). Never switch branches, never stash, never touch the main checkout.',
  'Apps run where the run target says: the Prepare stage resolved `.claude/vitrinka-workflows.json` → `run.web` and hands you `where` (devbox | local) and `baseUrl`; `devbox` means `devbox run -- \'<cmd>\'` on this branch\'s workspace, `local` means this machine. Simulator work (iOS, Android) always runs on this machine. Say so in `problems` when you had to deviate.',
  'Every vitrinka board/task link you return is the server-returned `url`, verbatim — never composed, never shortened.',
  'Browser work: onyx `browser_start(session: $CLAUDE_CODE_SESSION_ID)` first, headless, then playwright; screenshots land in the capture root you were given, never the repo root.',
  'When a door refuses (4xx with a diagnosis), apply the corrected call it names once; a second refusal is a `problems` entry, not a workaround.',
].join('\n')

function withPreamble(prompt) {
  return PREAMBLE + '\n\n' + prompt
}
// ---- lib/run.js — the run target: where a run starts the app
// `.claude/vitrinka-workflows.json` → `run: { web: "auto" | "devbox" | "local" }`.
// `auto` (the default) picks the devbox when `devbox` resolves a workspace
// for this branch, else this machine. Simulator lanes (iOS, Android) are
// always local — the simulator lives here. Nobody assumes a devbox exists:
// vitrinka is a SaaS and most teams have none.
const RUN_TARGETS = ['auto', 'devbox', 'local']

function resolveRun(override) {
  const web = override && override.run && RUN_TARGETS.indexOf(override.run.web) >= 0 ? override.run.web : 'auto'
  return { web }
}

// The rule the Prepare stage applies, as prompt text. It reads the file
// itself (a script cannot), so the whole ladder travels with the prompt. It
// decides WHERE only; whether and when the app starts is the caller's line.
const RUN_RULE =
  'Run target — where this run\'s web app runs: read `.claude/vitrinka-workflows.json` and take `run.web` (`auto` when the file or the key is absent). ' +
  '`auto`: this branch\'s devbox workspace when `devbox` resolves one (`devbox run -- \'<cmd>\'`), otherwise this machine. ' +
  '`devbox`: the devbox only — an unresolved devbox is a `problems` entry and no app, never a silent local fallback. ' +
  '`local`: this machine only, never a devbox. Return `where` as devbox | local and the file\'s content as `override` ({} when absent).'
// ---- lib/schemas.js — structured-output schemas shared by the Exp flows
const ROUTE = {
  type: 'object',
  properties: {
    path: { type: 'string' },
    title: { type: 'string' },
    file: { type: 'string', description: 'repo-relative implementing file' },
    auth: { type: 'string', description: 'none | user | admin | <role>' },
    setup: { type: 'string', description: 'how to reach it with data on screen (seed, fixture, deep link)' },
  },
  required: ['path', 'title'],
}

const JOURNEY = {
  type: 'object',
  properties: {
    title: { type: 'string' },
    steps: { type: 'array', items: { type: 'string' } },
    roles: { type: 'array', items: { type: 'string' } },
  },
  required: ['title', 'steps'],
}

const TERRAIN_SCHEMA = {
  type: 'object',
  properties: {
    projectType: { type: 'string', enum: ['web', 'expo', 'cli', 'other'] },
    routes: { type: 'array', items: ROUTE },
    journeys: { type: 'array', items: JOURNEY },
    extendPoints: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, file: { type: 'string' }, why: { type: 'string' } }, required: ['what', 'file'] } },
    duplicationRisks: { type: 'array', items: { type: 'object', properties: { risk: { type: 'string' }, existing: { type: 'string' } }, required: ['risk', 'existing'] } },
    openQuestions: { type: 'array', items: { type: 'string' } },
    terrainUrl: { type: 'string' },
    boardUrl: { type: 'string' },
  },
  required: ['projectType', 'routes'],
}

const FINDING = {
  type: 'object',
  properties: {
    key: { type: 'string' },
    id: { type: 'integer', description: 'annotation id from the annotate receipt' },
    cardId: { type: 'integer' },
    route: { type: 'string' },
    lane: { type: 'string', description: 'the lane key the finding was seen in' },
    state: { type: 'string', description: 'capture state for the iOS lane (default | keyboard | scrolled | scroll-end | landscape | overscroll)' },
    area: { type: 'string', description: 'route, component or subsystem the fix lives in' },
    kind: { type: 'string', enum: ['finding', 'suggestion'] },
    severity: { type: 'string', enum: ['blocker', 'major', 'minor'] },
    rule: { type: 'string' },
    summary: { type: 'string' },
    files: { type: 'array', items: { type: 'string' } },
    inScope: { type: 'boolean', description: 'false when the defect lives outside the feature scope the run was given' },
  },
  required: ['key', 'area', 'kind', 'severity', 'summary'],
}

const FINDINGS_SCHEMA = {
  type: 'object',
  properties: {
    lane: { type: 'string' },
    findings: { type: 'array', items: FINDING },
    regressions: { type: 'array', items: { type: 'object', properties: { id: { type: 'integer' }, key: { type: 'string' }, fixed: { type: 'boolean' }, note: { type: 'string' } }, required: ['key', 'fixed'] } },
    // The card id of every card whose pixels the reviewer read: the evidence
    // laneJudged checks against the lane's published cards.
    screensRead: { type: 'array', items: { type: 'integer' } },
    boardUrl: { type: 'string' },
  },
  required: ['findings', 'screensRead'],
}

const SHOOT_SCHEMA = {
  type: 'object',
  properties: {
    lane: { type: 'string' },
    shots: { type: 'array', items: { type: 'object', properties: { route: { type: 'string' }, state: { type: 'string' }, label: { type: 'string' }, file: { type: 'string' } }, required: ['route', 'label'] } },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['lane', 'shots'],
}

const USERTEST_SCHEMA = {
  type: 'object',
  properties: {
    qaTaskUrl: { type: 'string' },
    boardUrl: { type: 'string' },
    cases: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, lane: { type: 'string' }, verdict: { type: 'string', enum: ['pass', 'fail', 'skip'] }, note: { type: 'string' }, files: { type: 'array', items: { type: 'string' } } }, required: ['title', 'verdict'] } },
    bugs: { type: 'array', items: { type: 'string', description: 'task url of each bug filed' } },
  },
  required: ['cases'],
}

const FIX_SCHEMA = {
  type: 'object',
  properties: {
    fixed: { type: 'array', items: { type: 'string', description: 'finding key' } },
    skipped: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, why: { type: 'string' } }, required: ['key', 'why'] } },
    touchedRoutes: { type: 'array', items: { type: 'string' } },
    touchedFiles: { type: 'array', items: { type: 'string' } },
    commits: { type: 'array', items: { type: 'string' } },
  },
  required: ['fixed', 'skipped', 'touchedRoutes', 'touchedFiles'],
}

const GATE_SCHEMA = {
  type: 'object',
  properties: {
    green: { type: 'boolean' },
    ran: { type: 'array', items: { type: 'string' } },
    failures: { type: 'array', items: { type: 'string' } },
    repaired: { type: 'boolean' },
    touchedFiles: { type: 'array', items: { type: 'string' }, description: 'every file a repair commit changed' },
  },
  required: ['green', 'ran'],
}

// The test run's Prepare: the checkout and the run target, never the app —
// which apps start hangs on the lanes this answer resolves (appStarts).
const TARGET_SCHEMA = {
  type: 'object',
  properties: {
    where: { type: 'string', enum: ['devbox', 'local'] },
    branch: { type: 'string' },
    sha: { type: 'string', description: 'short HEAD sha' },
    project: { type: 'string' },
    task: { type: 'string', description: 'vitrinka task id the run is bound to' },
    override: { type: 'object', description: 'parsed .claude/vitrinka-workflows.json or {}' },
    projectType: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['where', 'branch', 'projectType'],
}

// A Prepare that also starts the app at the run target (build-idea's quick check).
const PREPARE_SCHEMA = {
  ...TARGET_SCHEMA,
  properties: {
    baseUrl: { type: 'string', description: 'reachable app url; empty only when the run target could not be honoured' },
    ...TARGET_SCHEMA.properties,
  },
}

// The test run's web app start, once its lanes are known to need it.
const APP_SCHEMA = {
  type: 'object',
  properties: {
    baseUrl: { type: 'string', description: 'reachable app url; empty only when the run target could not be honoured' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['baseUrl'],
}

// The test run's native app start, once a simulator lane needs it.
const NATIVE_SCHEMA = {
  type: 'object',
  properties: {
    ready: { type: 'boolean', description: 'the app itself opened on every simulator — not a dev-client launcher, an error screen or a blank one' },
    scheme: { type: 'string', description: 'the deep-link scheme routes open with, e.g. "myapp"' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['ready'],
}

const PUBLISH_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    section: { type: 'string' },
    cards: { type: 'array', items: { type: 'object', properties: { cardId: { type: 'integer' }, route: { type: 'string' }, lane: { type: 'string' }, state: { type: 'string' }, label: { type: 'string' } }, required: ['cardId'] } },
  },
  required: ['boardUrl', 'boardSlug', 'section', 'cards'],
}

// The quick check of Exp build-idea: one desktop pass plus one journey walk.
const QUICKCHECK_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    routes: { type: 'array', items: { type: 'object', properties: { route: { type: 'string' }, verdict: { type: 'string', enum: ['works', 'broken', 'unreachable'] }, note: { type: 'string' }, cardId: { type: 'integer' } }, required: ['route', 'verdict'] } },
    journey: { type: 'object', properties: { title: { type: 'string' }, verdict: { type: 'string', enum: ['works', 'broken', 'skipped'] }, note: { type: 'string' }, steps: { type: 'array', items: { type: 'object', properties: { step: { type: 'string' }, verdict: { type: 'string' }, note: { type: 'string' } }, required: ['step', 'verdict'] } } }, required: ['verdict'] },
    shots: { type: 'integer' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['routes', 'journey'],
}

// The lanes door receipt: the run board and one child board per lane.
const RUNBOARD_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    lanes: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, slug: { type: 'string' }, url: { type: 'string' } }, required: ['key', 'slug', 'url'] } },
  },
  required: ['boardUrl', 'boardSlug', 'lanes'],
}

// The run door result: the qa task and the bugs it filed.
const RUNDOOR_SCHEMA = {
  type: 'object',
  properties: {
    qaTaskUrl: { type: 'string' },
    lanes: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, published: { type: 'boolean' }, note: { type: 'string' } }, required: ['key', 'published'] } },
    bugs: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, url: { type: 'string' } }, required: ['url'] } },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['lanes', 'bugs'],
}

// The commit the record is filed at, read once after every pass committed.
const HEAD_SCHEMA = {
  type: 'object',
  properties: { head: { type: 'string', description: 'the full `git rev-parse HEAD` of this checkout' } },
  required: ['head'],
}

// Where the branch stands after the code loop, compared with the record's sha.
const HEADS_SCHEMA = {
  type: 'object',
  properties: {
    head: { type: 'string', description: 'the full `git rev-parse HEAD` of this checkout' },
    url: { type: 'string', description: "the pull request's full https url; \"\" when the branch has none" },
    prHead: { type: 'string', description: "the full sha of the pull request's head commit" },
  },
  required: ['head', 'prHead'],
}

// A PR-state step (prOutcome): the PR it acted on and its draft state before
// and after the call — a state it could not read is left out, never guessed —
// or `none`, the lookup's proof the branch has no PR (codeLoopPushHold).
const PR_STATE_SCHEMA = {
  type: 'object',
  properties: {
    url: { type: 'string', description: "the pull request's full https url; \"\" when the branch has none or it could not be read" },
    none: { type: 'boolean', description: 'true only when the lookup answered that the branch has no open pull request (gh exits 1: "no pull requests found")' },
    wasDraft: { type: 'boolean', description: 'whether it was a draft before the call; omitted when it could not be read' },
    isDraft: { type: 'boolean', description: 'whether it is a draft after the call; omitted when it could not be read' },
    why: { type: 'string', description: 'why a call failed' },
  },
  required: ['url'],
}
// ---- lib/helpers.js — plain-code helpers shared by the Exp flows (no agents here)
const SEVERITY_RANK = { blocker: 3, major: 2, minor: 1 }

// Findings the loop fixes on its own: defects at or above the threshold.
// Suggestions and anything below stay staged on the board for the human.
function autoAcceptable(findings, threshold) {
  const min = SEVERITY_RANK[threshold] || SEVERITY_RANK.minor
  return findings.filter(f => f.kind === 'finding' && (SEVERITY_RANK[f.severity] || 0) >= min)
}

// The pass cap a run asked for: absent is 2, a number or numeric string is
// clamped to 1-6. Anything else (true, [], '', 'two') is null — the type is
// checked before any coercion, because Number(true) and Number([]) are
// finite and would pass as a cap nobody asked for.
function parseCap(raw) {
  if (raw === undefined || raw === null) return 2
  const n = typeof raw === 'number' ? raw : typeof raw === 'string' && raw.trim() ? Number(raw) : NaN
  return Number.isFinite(n) ? Math.max(1, Math.min(6, Math.floor(n))) : null
}

// How a pass ends once its fix list is known. A pass is shoot → review →
// accept → fix → gate, the final one included: `cap` bounds the passes, so
// the last pass still fixes what it accepted and only the reshoot that would
// verify it is dropped. 'clean' — nothing left to fix, retried carried
// findings included (see fixListFor); 'reshoot' — fix, gate, shoot again;
// 'last' — fix and gate, then stop; 'rewalk' — nothing to fix, but a fixed
// usertest failure no walk confirmed yet (`unwalked`, see unwalkedFixes: its
// tester died or skipped it) and a pass left: the next pass only walks it
// again — no shots, no review. At the cap it ends 'clean' with the fix
// unverified, which keeps the draft.
function passEnd(pass, cap, toFix, unwalked = 0) {
  if (toFix) return pass < cap ? 'reshoot' : 'last'
  return unwalked && pass < cap ? 'rewalk' : 'clean'
}

// Whether the run converged: it ended on a 'clean' pass (passEnd) with no
// finding left open, no fixed journey left unwalked, and no pass gate red. A
// red gate is sticky — the clean pass fixes nothing, so it runs no gate that
// could clear it — and a run whose gate went red never claims convergence.
function convergedAfter({ clean, open = [], unwalked = [], gateRed }) {
  return !!clean && !open.length && !unwalked.length && !gateRed
}

// A pass's fix list: what it filed and accepted (new findings, functional
// fails, regressions) plus every carried finding still open from earlier
// passes — a skipped finding goes back to a fixer each pass until one fixes
// it or the cap ends the run, since reviewers never refile it. A carried
// off-scope finding (inScope false: its first fixer already had the 2-file
// allowance) is the report's bug, never another attempt. One entry per key,
// the fresh ones first.
function fixListFor(fresh, carried) {
  const byKey = new Map()
  for (const f of [...fresh, ...carried.filter(f => f.inScope !== false)]) if (!byKey.has(f.key)) byKey.set(f.key, f)
  return [...byKey.values()]
}

// A failed usertest case's finding key: its lane and its title (the
// journey's), never the pass or the case's index, so a failure refiled in a
// later pass is the carried finding — fixing it there closes that one.
function usertestKey(title, lane) {
  return `usertest-${slugify(lane)}-${slugify(title)}`
}

// The journeys the next pass walks: every one whose steps pass a route still
// open or just touched, and every one whose failure a fixer claimed fixed
// (`fixed`: those functional findings, still unwalked — see unwalkedFixes),
// matched by its stable usertestKey, never by route: a fixed journey is no
// longer open and its steps need not name a route, so only walking it again
// verifies the fix. A fixed failure no journey matches (an exploratory case)
// adds none — the tester walks it under its own title (rewalkCases). With
// nothing picked, the journeys that failed this pass, and all of them when a
// failure matches none.
function journeysToRerun(allJourneys, openRoutes, fixed, cases) {
  const walks = (j, f) => f.key === usertestKey(j.title, f.lane)
  const picked = allJourneys.filter(j => (j.steps || []).some(s => openRoutes.some(p => p && s.includes(p))) || fixed.some(f => walks(j, f)))
  if (picked.length) return picked
  const failed = cases.filter(c => c.verdict === 'fail')
  const byTitle = allJourneys.filter(j => failed.some(c => c.title === j.title))
  return byTitle.length || !failed.length ? byTitle : allJourneys
}

// The fixed usertest failures still waiting for a walk to confirm them. A
// case the pass walked for the journey on its lane settles one — a pass, or
// a fail refiled as a fresh finding under the same key; a skipped case or
// none leaves it waiting, and a run that ends with one waiting keeps its
// draft (notReadyReasons).
function unwalkedFixes(pending, cases, lane) {
  const walked = new Set(cases.filter(c => c.verdict !== 'skip').map(c => usertestKey(c.title, c.lane || lane)))
  return pending.filter(f => !walked.has(f.key))
}

// A pass's failed usertest cases as functional findings, keyed by lane (none
// named: the usertest lane) and title, and carrying the title itself — the
// one handle a later walk settles it by (unwalkedFixes).
function functionalFindings(cases, lane) {
  return cases.filter(c => c.verdict === 'fail').map(c => ({
    key: usertestKey(c.title, c.lane || lane), title: c.title, route: '', lane: c.lane || lane, area: (c.files && c.files[0]) || 'functional',
    kind: 'finding', severity: 'major', rule: 'functional', summary: `${c.title}: ${c.note || 'failed'}`, files: c.files || [], inScope: true,
  }))
}

// The fixed failures the next tester walks again, each as ONE case under its
// own title: a case no journey matches (an exploratory one) is walked only
// because it is handed over here, and the walk under that title is what
// settles it.
function rewalkCases(fixed) {
  return fixed.map(f => ({ title: f.title, failed: f.summary }))
}

// The case a route gets on one lane where the run leaves no finding open. A
// pass is earned, never assumed: this lane captured the route, a reviewer
// judged that capture, and no fix landed on the route after it. Anything
// less — unreachable, a failed shooter or publish, a shots run, a fix the
// cap left without a reshoot — is a skip naming why.
// captures: [{pass, lane, route, judged}] · fixed: [{pass, route}] — a fix
// has no lane (see affectedRoutes).
function routeVerdict(path, lane, captures, fixed) {
  const latest = list => list.reduce((a, x) => (!a || x.pass >= a.pass ? x : a), null)
  const shot = latest(captures.filter(x => x.lane === lane && x.route === path))
  if (!shot) return { verdict: 'skip', why: 'never captured on this lane' }
  if (!shot.judged) return { verdict: 'skip', why: `captured in pass ${shot.pass}, never reviewed`, pass: shot.pass }
  const fix = latest(fixed.filter(x => x.route === path))
  if (fix && fix.pass >= shot.pass) return { verdict: 'skip', why: `fixed in pass ${fix.pass} after its last capture, never reshot`, pass: shot.pass }
  return { verdict: 'pass', pass: shot.pass }
}

// Whether a lane's reviewer judged its capture: it returned the card ids it
// read, and they cover every card the lane published this pass with a route
// on it — the cards that count as captures; a route-less card (a section
// summary) has no screen to judge. A reply alone — {findings: []} with
// nothing read — proves no card was looked at, so the lane's routes stay
// unjudged (a skip, never a pass).
function laneJudged(review, cards) {
  if (!review || !Array.isArray(review.screensRead)) return false
  const read = new Set(review.screensRead)
  return cards.filter(c => c.route).every(c => read.has(c.cardId))
}

// The routes a pass's fixes may have changed, on EVERY lane — a fix edits
// code every lane renders. The routes they name (the fixed findings' own and
// the fixers' touched ones, sub-routes included) together with the routes
// whose implementing file they touched — a named route never hides a file
// edit elsewhere. A change nobody can place is verified everywhere: a touched
// file no route implements (a shared header, a route with no `file`) and a
// change that places nowhere reach every route. Nothing touched changes
// nothing. The next pass reshoots these, and each stays unverified until a
// capture is judged.
function affectedRoutes(allRoutes, paths, files) {
  const named = paths.filter(Boolean)
  const rel = f => String(f).replace(/^\.\//, '')
  const touched = files.filter(Boolean).map(rel)
  if (!named.length && !touched.length) return []
  // The terrain's file is repo-relative; a fixer may report it absolute.
  const implementsFile = (r, f) => !!r.file && (f === rel(r.file) || f.endsWith('/' + rel(r.file)))
  if (touched.some(f => !allRoutes.some(r => implementsFile(r, f)))) return allRoutes.map(r => r.path)
  const hit = allRoutes.filter(r => named.some(p => r.path === p || r.path.startsWith(p)) || touched.some(f => implementsFile(r, f)))
  return (hit.length ? hit : allRoutes).map(r => r.path)
}

// The files a pass gate's repair commits changed — like the fixers' edits,
// they postdate the pass's captures. [] when it repaired nothing; null when
// it repaired without naming them: a change nobody can place.
function gateRepairFiles(gate) {
  if (!gate || !gate.repaired) return []
  const files = (gate.touchedFiles || []).filter(Boolean)
  return files.length ? files : null
}

// The keys a pass fixed where nobody can place the change: the finding has
// no route of its own (a functional failure's is '', an unknown key has
// none) and the fixer that reported it named no touched route and no
// touched file. Its commit still postdates every capture — empty metadata is
// no proof nothing changed — so, like a gate repair naming no files, it
// unverifies every route (affectedRoutes' "a change nobody can place").
function unplacedFixes(fixResults, fixList) {
  const routeOf = k => (fixList.find(f => f.key === k) || {}).route
  return fixResults
    .filter(r => !(r.touchedRoutes || []).some(Boolean) && !(r.touchedFiles || []).some(Boolean))
    .flatMap(r => (r.fixed || []).filter(k => !routeOf(k)))
}

// What a run that fixes nothing leaves open: every defect it filed, at any
// severity — the threshold is a fix decision and a review-only run makes
// none — and every usertest case that failed (`functional`: the usertest
// stage files each through `finish --bugs direct`). Suggestions are taste,
// never bugs: they stay staged on the board.
function openWithoutFixing(filed, functional) {
  return [...filed.filter(f => f.kind === 'finding'), ...functional]
}

// Why a run's draft PR stays a draft; empty means the run earned "ready".
// Every fix run ends in the code loop's review of the final diff — a run
// whose passes fixed nothing still carries the whole branch diff, and
// nothing before the device pass reviewed it. Returning is not enough: the
// loop must leave nothing for the human and end on a green gate (each round
// gates the same suites, so its LAST round is the branch's state). `lanes`
// are the run's lane keys: a lane the receipt leaves out was not published.
// A published lane is not a judged one: every route case the record files
// must be a pass (routeVerdict) — a lane nobody captured or reviewed, and a
// fix the cap left without a reshoot, keep the draft. The code loop runs
// after the record, so anything it commits — a review fix, a gate repair, a
// push from prm's first round — postdates every capture and names no files
// to place it: a change nobody can place unverifies every route
// (affectedRoutes). So the PR head and the checkout's HEAD must still be the
// commit the record was filed at (`recordSha`, `heads`). A fixed usertest
// failure no later walk of its journey confirmed (`unwalked`) is no pass.
function notReadyReasons(run) {
  const { fixes, code, recordSha, heads } = run
  const why = recordReasons(run)
  if (fixes) {
    const last = code && code.rounds.length ? code.rounds[code.rounds.length - 1] : null
    if (!last) why.push('the code loop did not review the diff')
    else {
      if (code.remaining.length) why.push(`${code.remaining.length} code-review findings left for the human`)
      if (!last.green) why.push("the code loop's last gate is red")
      const same = (a, b) => a.length >= 7 && b.length >= 7 && (a.startsWith(b) || b.startsWith(a))
      if (!recordSha || !heads || !heads.head || !heads.prHead) why.push('the PR head could not be compared with the device record')
      else {
        const moved = [heads.prHead, heads.head].find(s => !same(s, recordSha))
        if (moved) why.push(`the branch moved after the device record (${recordSha.slice(0, 9)} → ${moved.slice(0, 9)}) — no device pass verified the change`)
      }
    }
  }
  return why
}

// The part of notReadyReasons the device record alone decides — known once
// the run door has filed it, before the code loop runs: the reasons the early
// PR-state step names when it returns a PR ready for review to draft before
// code-loop's prm pushes to it (codeLoopPushHold). A clean record has none,
// but the step runs anyway — the code loop's review is still ahead.
function recordReasons({ fixes, open, lanes, report, gateRed, routeCases, unwalked = [] }) {
  const why = []
  if (!fixes) why.push('thoroughness is not "fix"')
  if (open.length) why.push(`${open.length} findings open`)
  if (unwalked.length) why.push(`${unwalked.length} fixed journeys never walked again`)
  if (!report || !lanes.every(k => report.lanes.some(l => l.key === k && l.published))) why.push('the run door did not publish every lane')
  for (const k of lanes) {
    const cases = routeCases[k] || []
    const unearned = cases.filter(c => c.verdict !== 'pass').length
    if (unearned) why.push(`lane ${k}: ${unearned} of ${cases.length} routes earned no pass`)
  }
  if (gateRed) why.push('a pass gate stayed red')
  return why
}

// What a PR-state step left: `want` is the state the run earned ('ready' when
// notReadyReasons is empty, else 'draft'); the step ran the idempotent
// `gh pr ready` or `gh pr ready --undo` whatever state it found — a guessed
// "already a draft" never skips the call — and read the state before
// (wasDraft) and after (isDraft), leaving out one it could not read. The
// earned state holds only when the read-back says so; `demoted` is a PR the
// run took back from ready for review, which the hand-back says.
function prOutcome(want, step) {
  const after = step && typeof step.isDraft === 'boolean' ? step.isDraft : null
  const held = after === (want === 'draft')
  return {
    ready: want === 'ready' && held,
    draft: want === 'draft' && held,
    demoted: want === 'draft' && held && step.wasDraft === false,
    problem: held ? '' : `${want === 'ready' ? 'readying' : 'returning to draft'} failed: ${(step && step.why) || (step ? 'its state could not be read back' : 'no result')}`,
  }
}

// Why the code loop must not push — '' when it may. Its PR phase is prm
// pushing the branch to its PR, and a PR ready for review with auto-merge
// armed (or under MERGE_POLICY=self) can merge on that push. No fix run has
// earned ready before the code loop — even a clean record still awaits its
// review — so every one pushes only where the early PR-state step (`early`)
// proved no ready PR takes the push: the PR reads back a draft, or the branch
// has none (url "" with `none` — the lookup answered "no pull requests found",
// which `gh pr view` reports by exiting 1, so a `why` beside it is that answer,
// not a failure; no PR `named`) and the loop opens its own as a draft. A
// missing result, an unread state, a PR still ready or a url "" nothing
// proved absent holds the push: the loop reviews and gates, and its commits
// stay local.
function codeLoopPushHold(early, named) {
  if (!early || early.url) return prOutcome('draft', early).problem
  if (named) return `pull request ${named} could not be read${early.why ? `: ${early.why}` : ''}`
  if (early.none) return ''
  return `the branch's pull request could not be read: ${early.why || 'no lookup proved it has none'}`
}

// Each lane manifest's stamp, keyed by lane: the ONE head the record is filed
// at — read after every pass fixer and gate repair committed, and the same
// sha readiness compares (notReadyReasons' `recordSha`) — names both the
// manifest's `sha` and its `runId`, which fits the run door's
// ^[A-Za-z0-9._-]{1,64}$ whatever the run is called. `run` is the slug of
// the run board this invocation minted: the door replaces the cards a
// previous publish of the same runId left, so a second run on an unchanged
// commit must never reuse the first one's ids.
function manifestStamps(run, head, lanes) {
  return Object.fromEntries(lanes.map(lane => {
    const tail = `-${head.slice(0, 9)}-${boundedSlug(lane, 32)}`
    return [lane, { runId: boundedSlug(run, 64 - tail.length) + tail, sha: head }]
  }))
}

// A runId part of at most `max` chars: a longer slug keeps its head plus a
// hash of the whole, so two run boards or custom lanes sharing a long prefix
// still get distinct runIds.
function boundedSlug(s, max) {
  const slug = slugify(s)
  if (slug.length <= max) return slug
  let h = 0x811c9dc5
  for (const c of slug) h = Math.imul(h ^ c.charCodeAt(0), 0x01000193) >>> 0
  return `${slug.slice(0, max - 9)}-${h.toString(16).padStart(8, '0')}`
}

// Group findings by area into at most `max` disjoint fix lists. A finding
// whose files also appear in another area is `shared` and runs first, so
// the parallel fixers never edit the same file.
function groupByArea(findings, max) {
  const byArea = new Map()
  for (const f of findings) {
    const area = f.area || 'misc'
    if (!byArea.has(area)) byArea.set(area, [])
    byArea.get(area).push(f)
  }
  const fileOwners = new Map()
  for (const [area, list] of byArea) {
    for (const f of list) for (const file of f.files || []) {
      if (!fileOwners.has(file)) fileOwners.set(file, new Set())
      fileOwners.get(file).add(area)
    }
  }
  const shared = []
  for (const [area, list] of byArea) {
    const keep = []
    for (const f of list) {
      const crosses = (f.files || []).some(file => fileOwners.get(file).size > 1)
      if (crosses) shared.push(f); else keep.push(f)
    }
    byArea.set(area, keep)
  }
  let groups = [...byArea].filter(([, l]) => l.length).map(([area, list]) => ({ area, findings: list }))
  groups.sort((a, b) => b.findings.length - a.findings.length)
  while (groups.length > max) {
    const tail = groups.pop()
    const smallest = groups[groups.length - 1]
    smallest.area = smallest.area + '+' + tail.area
    smallest.findings.push(...tail.findings)
  }
  return { shared: shared.length ? { area: 'shared', findings: shared } : null, groups }
}

function uniq(list) {
  return [...new Set(list.filter(Boolean))]
}

function key(f) {
  return f.key || (f.cardId + ':' + f.summary)
}

function slugify(s) {
  return String(s || '').replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase()
}
// args: { brief: string (repo-relative path), task: string, project?: string, base?: 'main' }
const A = args || {}
if (!A.brief) throw new Error('build-idea: args.brief (the committed brief\'s repo-relative path) is required')
if (!A.task) throw new Error('build-idea: args.task (the epic or story the brief belongs to) is required')
for (const k of ['cap', 'severity', 'matrix', 'lanes']) {
  if (A[k] !== undefined) throw new Error(`build-idea: args.${k} is not a build decision — the Exp build has no device pass; run vitrinka-experimental:test after the human has looked`)
}

const PLAN_SCHEMA = {
  type: 'object',
  properties: {
    slices: {
      type: 'array',
      maxItems: 4,
      items: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          goal: { type: 'string' },
          files: { type: 'array', items: { type: 'string' }, description: 'files this slice owns; disjoint from every other slice' },
          dependsOn: { type: 'array', items: { type: 'string' } },
          acceptance: { type: 'array', items: { type: 'string' } },
          tests: { type: 'array', items: { type: 'string' }, description: 'tests to write or extend, in the repo\'s own framework' },
        },
        required: ['name', 'goal', 'files', 'acceptance'],
      },
    },
    shared: { type: 'object', properties: { goal: { type: 'string' }, files: { type: 'array', items: { type: 'string' } } }, description: 'schema, types, shared components every slice needs — built first, empty when none' },
    scope: { type: 'string', description: 'one paragraph: what a later test run should cover' },
    scopeFiles: { type: 'array', items: { type: 'string' }, description: 'every file the feature owns — the boundary later fixers respect' },
    routes: { type: 'array', items: ROUTE, description: 'routes the feature adds or changes, with how to reach each with data on screen' },
    journey: JOURNEY,
  },
  required: ['slices', 'scope', 'routes', 'journey'],
}

const IMPL_SCHEMA = {
  type: 'object',
  properties: {
    slice: { type: 'string' },
    done: { type: 'array', items: { type: 'string' } },
    left: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, why: { type: 'string' } }, required: ['what', 'why'] } },
    files: { type: 'array', items: { type: 'string' } },
    commits: { type: 'array', items: { type: 'string' } },
  },
  required: ['slice', 'done', 'left', 'files'],
}

const PR_SCHEMA = {
  type: 'object',
  properties: {
    pr: { type: 'string', description: 'the PR url, empty when none was opened' },
    draft: { type: 'boolean' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['pr'],
}

phase('Plan')
const plan = await agent(withPreamble(
  `Read the feature brief at ${A.brief} (and the terrain artifact it links, if any). Plan its implementation for THIS repo as at most 4 slices that can be built in parallel in one worktree: each slice owns a disjoint set of files; anything two slices need (schema/migration, types, a shared component, a door) goes into \`shared\`, built first. Every slice lists its acceptance criteria as observable behaviour and the tests it writes in the repo's own framework. Honour the repo's laws (CLAUDE.md, the project memory files whose triggers match) — a plan that fights a law is wrong. Also return: the routes the feature adds or changes (path, title, file, auth, how to reach each with data on screen), the ONE main journey a human walks to see the feature work (title + concrete steps), the feature's scope files, and one paragraph of what a later test run should cover. Read-only: change nothing.`
), { label: 'plan', phase: 'Plan', schema: PLAN_SCHEMA })
if (!plan || !plan.slices.length) throw new Error('build-idea: planning produced no slices')
log(`build-idea: ${plan.slices.length} slices${plan.shared && plan.shared.files && plan.shared.files.length ? ' + shared' : ''}, ${plan.routes.length} routes, journey "${plan.journey.title || 'main'}"`)

phase('Implement')
const implPrompt = (s, isShared) => withPreamble(
  `Implement ${isShared ? 'the SHARED foundation' : `slice "${s.name}"`} of the feature in ${A.brief} (task ${A.task}), in this worktree.\n` +
  `Goal: ${s.goal}\nFiles you own: ${JSON.stringify(s.files)}\n${s.acceptance ? `Acceptance: ${JSON.stringify(s.acceptance)}\n` : ''}${s.tests ? `Tests to write/extend: ${JSON.stringify(s.tests)}\n` : ''}` +
  (isShared ? 'Other slices build on what you leave; keep it minimal and typed.' : 'Other slices are being built in this same checkout right now: never edit files outside your list, never reformat shared code; a need outside your files is a `left` item with why.') +
  ` A defect you notice outside the feature's scope is NOT yours: name it in \`left\` with why "off-scope" — never fix it here. Commit per coherent unit with a trailer naming the task. Return what is done, what is left and why, files and commits.`
)
const impl = []
if (plan.shared && plan.shared.files && plan.shared.files.length) {
  impl.push(await agent(implPrompt(plan.shared, true), { label: 'implement:shared', phase: 'Implement', schema: IMPL_SCHEMA }))
}
impl.push(...await parallel(plan.slices.map(s => () => agent(implPrompt(s, false), { label: `implement:${s.name}`, phase: 'Implement', schema: IMPL_SCHEMA }))))
const built = impl.filter(Boolean)
const left = built.flatMap(r => r.left.map(l => ({ slice: r.slice, ...l })))
const offScope = left.filter(l => /off-scope/i.test(l.why || ''))
const todo = left.filter(l => !/off-scope/i.test(l.why || ''))
log(`build-idea: ${built.length} slices built, ${todo.length} items left, ${offScope.length} off-scope defects spotted`)

if (todo.length) {
  const sweep = await agent(withPreamble(
    `Finish what the slice builders left in this worktree (feature ${A.brief}, task ${A.task}): ${JSON.stringify(todo)}. Everything is yours now — no other agent edits this checkout. An item that needs a product decision is left with why; an off-scope defect stays off-scope. Commit. Return done/left/files/commits.`
  ), { label: 'implement:sweep', phase: 'Implement', schema: IMPL_SCHEMA })
  if (sweep) built.push(sweep)
}

const gate = await agent(withPreamble(
  `Gate the implementation: run every type/build/test gate CLAUDE.md names, where it says they run, plus the tests the slices wrote. Repair and commit what this branch broke; report what predates it. Return green, what ran, failures.`
), { label: 'gate', phase: 'Implement', schema: GATE_SCHEMA })
if (!gate || !gate.green) log(`build-idea: implementation gate red — ${JSON.stringify((gate && gate.failures) || ['no result'])}; continuing so the quick check shows the state`)

phase('Quick check')
const prep = await agent(withPreamble(
  `Prepare the quick check of the feature on this branch.\n` +
  `1. Report the current branch, the short HEAD sha and the vitrinka project the repo is bound to (\`vitrinka status\` / the repo's .vitrinka descriptor).\n` +
  `2. ${RUN_RULE}\n` +
  `3. Decide projectType (web | expo | cli | other) from the repo.\n` +
  `4. Start the app for this branch there; wait until it answers; return the reachable base URL. The run is bound to task ${A.task}.\n` +
  `Never create tasks, boards or commits here.`
), { label: 'prepare', phase: 'Quick check', schema: PREPARE_SCHEMA })
if (!prep) throw new Error('build-idea: prepare failed')
const run = resolveRun(prep.override)
const boardSlug = `${slugify(prep.branch)}-quick-check`
const captureRoot = '.vitrinka/screenshots/quick-check'
log(`build-idea: quick check on ${prep.branch} at ${prep.baseUrl || '(no app)'} (${prep.where}, run.web=${run.web})`)

let quick = { boardUrl: '', boardSlug, routes: plan.routes.map(r => ({ route: r.path, verdict: 'unreachable', note: 'quick check did not run' })), journey: { title: plan.journey.title, verdict: 'skipped', note: 'quick check did not run' }, shots: 0, problems: [] }
if (!prep.baseUrl) {
  quick.problems = (prep.problems || []).concat(['no app url — the run target could not be honoured'])
  log('build-idea: no app url — the quick check is skipped and the hand-back says so')
} else {
  const shot = await agent(withPreamble(
    `ONE quick "does it work" check of the feature (task ${A.task}) against ${prep.baseUrl} — desktop only, 1440×810@2, mouse. This is not a review: no findings, no matrix, no second pass.\n` +
    `Routes (open every one with data on screen; a route's \`setup\` says how):\n${JSON.stringify(plan.routes)}\n` +
    `Main journey to walk once:\n${JSON.stringify(plan.journey)}\n` +
    `Read \`docs {topic: "guide:publish-capture"}\` first. For each route: open it at exactly that viewport, wait for it to settle, scroll the whole page once, capture 2× and adopt it with \`vitrinka board capture web --file <png> --route <path> --device desktop --viewport 1440x810@2 --label quick/<route-slug> --title "<title>" --note "<what is on screen>" --src <implementing file> --root ${captureRoot} --yes\`; then judge it works | broken | unreachable with one line of why (a console error, a blank region or a failed request is broken). Walk the journey step by step, capturing after each step under label quick/journey/<n>, and judge each step; the journey is broken when any step is.\n` +
    `Then publish everything onto board ${boardSlug}${prep.project ? ` (project ${prep.project})` : ''} bound to task ${A.task}: ONE section "Quick check" — the route shots in route order, the journey shots after them, and beside each route a verdict card (works | broken + the line of why); a summary card at the head naming the branch, the sha ${prep.sha || ''}, the route count and the tally. Return the board's server url and slug, every route verdict with its card id, the journey verdict with its steps, the shot count and problems.`
  ), { label: 'quick-check', phase: 'Quick check', schema: QUICKCHECK_SCHEMA })
  if (shot) quick = shot
}
const broken = quick.routes.filter(r => r.verdict !== 'works')
log(`build-idea: quick check — ${quick.routes.length - broken.length}/${quick.routes.length} routes work, journey ${quick.journey.verdict}${quick.boardUrl ? ` → ${quick.boardUrl}` : ''}`)

phase('Ship')
const pr = await agent(withPreamble(
  `Open a DRAFT pull request for this branch through the prm skill (Skill tool: prm) with \`--draft\`, base ${A.base || 'main'}, bound to task ${A.task}. The body names the brief (${A.brief}), the quick-check board ${quick.boardUrl || '(none)'} and that the UI is unreviewed by design — the device pass is a separate decision. Never merge, never mark ready. Return the PR url.`
), { label: 'pr', phase: 'Ship', schema: PR_SCHEMA })
log(`build-idea: draft PR ${pr && pr.pr ? pr.pr : 'not opened'}`)

const handback = await agent(withPreamble(
  `Hand task ${A.task} back through the vitrinka handoff skill (Skill tool: vitrinka:handoff). Facts, one per line, for the summary:\n` +
  JSON.stringify({
    brief: A.brief,
    slices: built.map(b => ({ slice: b.slice, done: b.done.length, left: b.left.length })),
    implementationGate: gate && gate.green,
    quickCheck: { board: quick.boardUrl, routes: quick.routes, journey: quick.journey, problems: quick.problems },
    app: { url: prep.baseUrl, where: prep.where, branch: prep.branch },
    offScope,
    pr: pr && pr.pr,
    draft: true,
  }) +
  `\nThe hand-back names the running app url, the parked state (which route the journey ended on) and what to poke at (the routes and the journey). Broken routes are facts in the summary, not children. Off-scope defects (${offScope.length}) become spotted children. \`next\` holds exactly two steps for the human: look at the feature, then run /vitrinka-experimental:test to choose the device pass. Never mark the PR ready. Return the rendered hand-back block verbatim.`
), { label: 'handback', phase: 'Ship' })

return {
  plan: plan.slices.map(s => s.name),
  gate: gate && gate.green,
  app: prep.baseUrl,
  board: quick.boardUrl,
  routes: quick.routes,
  journey: quick.journey.verdict,
  pr: pr && pr.pr,
  handback,
}
