export const meta = {
  name: 'test',
  description: 'The ask-first device pass: shoot the chosen lanes (viewports, simulators, iOS 26 Safari), publish each lane as its own tab of one run board, review, accept, fix and reshoot up to the cap, then file the result through the run door',
  whenToUse: 'Launched by the vitrinka-experimental test skill AFTER its one batched question; every argument is an answer the human gave. Unattended: findings at or above the severity threshold are accepted and fixed (thoroughness "fix"); "review" files findings only; "shots" captures and publishes only.',
  phases: [
    { title: 'Prepare', detail: 'branch, run target, app, lanes, task binding' },
    { title: 'Map', detail: 'route inventory and journeys (skipped when passed in)' },
    { title: 'Run board', detail: 'the lanes door: one run board, one tab per lane' },
    { title: 'Pass', detail: 'shoot per lane ∥ usertest → publish per lane → review per lane → accept → fix → gate' },
    { title: 'Report', detail: 'one runner manifest per lane through the run door, the code loop, the PR, the hand-back' },
  ],
}
// Code generated by tools/gen-workflows from experimental/workflows-src/flows/test.js. DO NOT EDIT.
// Edit the flow or its lib/ fragments under experimental/workflows-src/, then `go run ./tools/gen-workflows`.
// ---- lib/preamble.js — the lines every Exp agent prompt starts with
// Agents already carry the repo's CLAUDE.md; these name only what a
// workflow stage needs beyond it. Keep it to contracts, never procedure —
// procedure is served by the vitrinka server (`docs {topic}`) and the CLI's
// `--help`. Exp differs from core in ONE line: apps run where the repo's run
// target says, never where a rule of thumb assumes.
const PREAMBLE = [
  'You are one stage of a vitrinka workflow. Your final text IS the return value: return raw data for the schema, never a human-facing report.',
  'Work in the current checkout (a worktree). Never switch branches, never stash, never touch the main checkout.',
  'Apps run where the run target says: the Prepare stage resolved `.claude/vitrinka-workflows.json` → `run.web` and hands you `where` (devbox | local) and `baseUrl`; `devbox` means `devbox run -- \'<cmd>\'` on this branch\'s workspace, `local` means this machine. Simulator work (iOS, Android) always runs on this machine. Say so in `problems` when you had to deviate.',
  'Every vitrinka board/task link you return is the server-returned `url`, verbatim — never composed, never shortened.',
  'Browser work: onyx `browser_start(session: $CLAUDE_CODE_SESSION_ID)` first, headless, then playwright; screenshots land in the capture root you were given, never the repo root.',
  'When a door refuses (4xx with a diagnosis), apply the corrected call it names once; a second refusal is a `problems` entry, not a workaround.',
].join('\n')

function withPreamble(prompt) {
  return PREAMBLE + '\n\n' + prompt
}
// ---- lib/run.js — the run target: where a run starts the app
// `.claude/vitrinka-workflows.json` → `run: { web: "auto" | "devbox" | "local" }`.
// `auto` (the default) picks the devbox when `devbox` resolves a workspace
// for this branch, else this machine. Simulator lanes (iOS, Android) are
// always local — the simulator lives here. Nobody assumes a devbox exists:
// vitrinka is a SaaS and most teams have none.
const RUN_TARGETS = ['auto', 'devbox', 'local']

function resolveRun(override) {
  const web = override && override.run && RUN_TARGETS.indexOf(override.run.web) >= 0 ? override.run.web : 'auto'
  return { web }
}

// The rule the Prepare stage applies, as prompt text. It reads the file
// itself (a script cannot), so the whole ladder travels with the prompt. It
// decides WHERE only; whether and when the app starts is the caller's line.
const RUN_RULE =
  'Run target — where this run\'s web app runs: read `.claude/vitrinka-workflows.json` and take `run.web` (`auto` when the file or the key is absent). ' +
  '`auto`: this branch\'s devbox workspace when `devbox` resolves one (`devbox run -- \'<cmd>\'`), otherwise this machine. ' +
  '`devbox`: the devbox only — an unresolved devbox is a `problems` entry and no app, never a silent local fallback. ' +
  '`local`: this machine only, never a devbox. Return `where` as devbox | local and the file\'s content as `override` ({} when absent).'
// ---- lib/schemas.js — structured-output schemas shared by the Exp flows
const ROUTE = {
  type: 'object',
  properties: {
    path: { type: 'string' },
    title: { type: 'string' },
    file: { type: 'string', description: 'repo-relative implementing file' },
    auth: { type: 'string', description: 'none | user | admin | <role>' },
    setup: { type: 'string', description: 'how to reach it with data on screen (seed, fixture, deep link)' },
  },
  required: ['path', 'title'],
}

const JOURNEY = {
  type: 'object',
  properties: {
    title: { type: 'string' },
    steps: { type: 'array', items: { type: 'string' } },
    roles: { type: 'array', items: { type: 'string' } },
  },
  required: ['title', 'steps'],
}

const TERRAIN_SCHEMA = {
  type: 'object',
  properties: {
    projectType: { type: 'string', enum: ['web', 'expo', 'cli', 'other'] },
    routes: { type: 'array', items: ROUTE },
    journeys: { type: 'array', items: JOURNEY },
    extendPoints: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, file: { type: 'string' }, why: { type: 'string' } }, required: ['what', 'file'] } },
    duplicationRisks: { type: 'array', items: { type: 'object', properties: { risk: { type: 'string' }, existing: { type: 'string' } }, required: ['risk', 'existing'] } },
    openQuestions: { type: 'array', items: { type: 'string' } },
    terrainUrl: { type: 'string' },
    boardUrl: { type: 'string' },
  },
  required: ['projectType', 'routes'],
}

const FINDING = {
  type: 'object',
  properties: {
    key: { type: 'string' },
    id: { type: 'integer', description: 'annotation id from the annotate receipt' },
    cardId: { type: 'integer' },
    route: { type: 'string' },
    lane: { type: 'string', description: 'the lane key the finding was seen in' },
    state: { type: 'string', description: 'capture state for the iOS lane (default | keyboard | scrolled | scroll-end | landscape | overscroll)' },
    area: { type: 'string', description: 'route, component or subsystem the fix lives in' },
    kind: { type: 'string', enum: ['finding', 'suggestion'] },
    severity: { type: 'string', enum: ['blocker', 'major', 'minor'] },
    rule: { type: 'string' },
    summary: { type: 'string' },
    files: { type: 'array', items: { type: 'string' } },
    inScope: { type: 'boolean', description: 'false when the defect lives outside the feature scope the run was given' },
  },
  required: ['key', 'area', 'kind', 'severity', 'summary'],
}

const FINDINGS_SCHEMA = {
  type: 'object',
  properties: {
    lane: { type: 'string' },
    findings: { type: 'array', items: FINDING },
    regressions: { type: 'array', items: { type: 'object', properties: { id: { type: 'integer' }, key: { type: 'string' }, fixed: { type: 'boolean' }, note: { type: 'string' } }, required: ['key', 'fixed'] } },
    // The card id of every card whose pixels the reviewer read: the evidence
    // laneJudged checks against the lane's published cards.
    screensRead: { type: 'array', items: { type: 'integer' } },
    boardUrl: { type: 'string' },
  },
  required: ['findings', 'screensRead'],
}

const SHOOT_SCHEMA = {
  type: 'object',
  properties: {
    lane: { type: 'string' },
    shots: { type: 'array', items: { type: 'object', properties: { route: { type: 'string' }, state: { type: 'string' }, label: { type: 'string' }, file: { type: 'string' } }, required: ['route', 'label'] } },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['lane', 'shots'],
}

const USERTEST_SCHEMA = {
  type: 'object',
  properties: {
    qaTaskUrl: { type: 'string' },
    boardUrl: { type: 'string' },
    cases: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, lane: { type: 'string' }, verdict: { type: 'string', enum: ['pass', 'fail', 'skip'] }, note: { type: 'string' }, files: { type: 'array', items: { type: 'string' } } }, required: ['title', 'verdict'] } },
    bugs: { type: 'array', items: { type: 'string', description: 'task url of each bug filed' } },
  },
  required: ['cases'],
}

const FIX_SCHEMA = {
  type: 'object',
  properties: {
    fixed: { type: 'array', items: { type: 'string', description: 'finding key' } },
    skipped: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, why: { type: 'string' } }, required: ['key', 'why'] } },
    touchedRoutes: { type: 'array', items: { type: 'string' } },
    touchedFiles: { type: 'array', items: { type: 'string' } },
    commits: { type: 'array', items: { type: 'string' } },
  },
  required: ['fixed', 'skipped', 'touchedRoutes', 'touchedFiles'],
}

const GATE_SCHEMA = {
  type: 'object',
  properties: {
    green: { type: 'boolean' },
    ran: { type: 'array', items: { type: 'string' } },
    failures: { type: 'array', items: { type: 'string' } },
    repaired: { type: 'boolean' },
    touchedFiles: { type: 'array', items: { type: 'string' }, description: 'every file a repair commit changed' },
  },
  required: ['green', 'ran'],
}

// The test run's Prepare: the checkout and the run target, never the app —
// which apps start hangs on the lanes this answer resolves (appStarts).
const TARGET_SCHEMA = {
  type: 'object',
  properties: {
    where: { type: 'string', enum: ['devbox', 'local'] },
    branch: { type: 'string' },
    sha: { type: 'string', description: 'short HEAD sha' },
    project: { type: 'string' },
    task: { type: 'string', description: 'vitrinka task id the run is bound to' },
    override: { type: 'object', description: 'parsed .claude/vitrinka-workflows.json or {}' },
    projectType: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['where', 'branch', 'projectType'],
}

// A Prepare that also starts the app at the run target (build-idea's quick check).
const PREPARE_SCHEMA = {
  ...TARGET_SCHEMA,
  properties: {
    baseUrl: { type: 'string', description: 'reachable app url; empty only when the run target could not be honoured' },
    ...TARGET_SCHEMA.properties,
  },
}

// The test run's web app start, once its lanes are known to need it.
const APP_SCHEMA = {
  type: 'object',
  properties: {
    baseUrl: { type: 'string', description: 'reachable app url; empty only when the run target could not be honoured' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['baseUrl'],
}

// The test run's native app start, once a simulator lane needs it.
const NATIVE_SCHEMA = {
  type: 'object',
  properties: {
    ready: { type: 'boolean', description: 'the app itself opened on every simulator — not a dev-client launcher, an error screen or a blank one' },
    scheme: { type: 'string', description: 'the deep-link scheme routes open with, e.g. "myapp"' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['ready'],
}

const PUBLISH_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    section: { type: 'string' },
    cards: { type: 'array', items: { type: 'object', properties: { cardId: { type: 'integer' }, route: { type: 'string' }, lane: { type: 'string' }, state: { type: 'string' }, label: { type: 'string' } }, required: ['cardId'] } },
  },
  required: ['boardUrl', 'boardSlug', 'section', 'cards'],
}

// The quick check of Exp build-idea: one desktop pass plus one journey walk.
const QUICKCHECK_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    routes: { type: 'array', items: { type: 'object', properties: { route: { type: 'string' }, verdict: { type: 'string', enum: ['works', 'broken', 'unreachable'] }, note: { type: 'string' }, cardId: { type: 'integer' } }, required: ['route', 'verdict'] } },
    journey: { type: 'object', properties: { title: { type: 'string' }, verdict: { type: 'string', enum: ['works', 'broken', 'skipped'] }, note: { type: 'string' }, steps: { type: 'array', items: { type: 'object', properties: { step: { type: 'string' }, verdict: { type: 'string' }, note: { type: 'string' } }, required: ['step', 'verdict'] } } }, required: ['verdict'] },
    shots: { type: 'integer' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['routes', 'journey'],
}

// The lanes door receipt: the run board and one child board per lane.
const RUNBOARD_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    lanes: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, slug: { type: 'string' }, url: { type: 'string' } }, required: ['key', 'slug', 'url'] } },
  },
  required: ['boardUrl', 'boardSlug', 'lanes'],
}

// The run door result: the qa task and the bugs it filed.
const RUNDOOR_SCHEMA = {
  type: 'object',
  properties: {
    qaTaskUrl: { type: 'string' },
    lanes: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, published: { type: 'boolean' }, note: { type: 'string' } }, required: ['key', 'published'] } },
    bugs: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, url: { type: 'string' } }, required: ['url'] } },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['lanes', 'bugs'],
}

// The commit the record is filed at, read once after every pass committed.
const HEAD_SCHEMA = {
  type: 'object',
  properties: { head: { type: 'string', description: 'the full `git rev-parse HEAD` of this checkout' } },
  required: ['head'],
}

// Where the branch stands after the code loop, compared with the record's sha.
const HEADS_SCHEMA = {
  type: 'object',
  properties: {
    head: { type: 'string', description: 'the full `git rev-parse HEAD` of this checkout' },
    url: { type: 'string', description: "the pull request's full https url; \"\" when the branch has none" },
    prHead: { type: 'string', description: "the full sha of the pull request's head commit" },
  },
  required: ['head', 'prHead'],
}

// A PR-state step (prOutcome): the PR it acted on and its draft state before
// and after the call — a state it could not read is left out, never guessed —
// or `none`, the lookup's proof the branch has no PR (codeLoopPushHold).
const PR_STATE_SCHEMA = {
  type: 'object',
  properties: {
    url: { type: 'string', description: "the pull request's full https url; \"\" when the branch has none or it could not be read" },
    none: { type: 'boolean', description: 'true only when the lookup answered that the branch has no open pull request (gh exits 1: "no pull requests found")' },
    wasDraft: { type: 'boolean', description: 'whether it was a draft before the call; omitted when it could not be read' },
    isDraft: { type: 'boolean', description: 'whether it is a draft after the call; omitted when it could not be read' },
    why: { type: 'string', description: 'why a call failed' },
  },
  required: ['url'],
}
// ---- lib/matrix.js — device matrix, review checklist and the iOS 26 checks
// A repo overrides the defaults in `.claude/vitrinka-workflows.json`
// ({projectType, matrix, checklist, exclude, run}); the Prepare stage reads
// that file and the flow merges it over these. The test skill's question
// pre-picks the matrix rows as lanes; the answer arrives as `args.lanes`.
const MATRIX = {
  web: [
    { name: 'iphone', width: 390, height: 844, scale: 3, input: 'touch', mobile: true, safeArea: true },
    { name: 'ipad', width: 1024, height: 768, scale: 2, input: 'touch', mobile: true, safeArea: false },
    { name: 'desktop', width: 1440, height: 810, scale: 2, input: 'mouse', mobile: false, safeArea: false },
  ],
  expo: [
    { name: 'iphone', platform: 'ios', sim: 'iPhone 16', input: 'touch', mobile: true, safeArea: true },
    { name: 'android', platform: 'android', sim: 'Pixel 8', input: 'touch', mobile: true, safeArea: true },
  ],
  cli: [],
}

const CHECKLIST = {
  web: [
    'grid: every edge, gap and control size sits on the 4pt grid',
    'overflow: no text clipped, ellipsised by accident, or overlapping its neighbour at long strings',
    'scroll: no horizontal scrolling at any viewport in the matrix',
    'safe-area: content and fixed bars respect the device safe-area insets (notch, home indicator)',
    'touch: tap targets ≥ 44×44 on touch devices, hover-only affordances have a touch path',
    'navigation: current location is visible, back always works, no dead-end screen',
    'controls: the same action looks and behaves the same on every screen; destructive actions confirm',
    'states: empty, loading, error and long-content states render without layout breaks',
  ],
  expo: [
    'safe-area: content respects notches, home indicator and the keyboard',
    'touch: tap targets ≥ 44×44, gestures do not fight the navigator',
    'navigation: tab and stack state survive a background/foreground cycle',
    'states: empty, loading, error and offline states render without layout breaks',
  ],
  cli: [],
}

// The iOS 26 Simulator Safari checks — each is one capture STATE the
// `vitrinka board capture safari --state` verb produces and one review RULE
// the lane's reviewer judges by. `dock` is the case a bottom dock hides the
// last list item because the list lacks the matching offset.
const IOS_CHECKS = {
  bars: { label: 'Translucent bars blend', state: 'default', rule: 'ios-bars: no solid top bar under the status bar and no solid footer under Safari\'s bottom bar — content scrolls under both (viewport-fit=cover); an opaque fixed header at the top edge breaks the blend' },
  'safe-area': { label: 'Safe-area insets', state: 'default', rule: 'ios-safe-area: fixed headers, footers, FABs and sheets pad by env(safe-area-inset-*); nothing sits under the notch or the home indicator (the shot\'s ledger carries the measured insets)' },
  keyboard: { label: 'Keyboard avoidance', state: 'keyboard', rule: 'ios-keyboard: with the keyboard OPEN the focused input stays visible, a sticky bottom bar follows the keyboard, and blur causes no layout jump' },
  dvh: { label: 'Viewport units', state: 'scrolled', rule: 'ios-dvh: nothing hides behind Safari\'s bottom bar once it collapses on scroll (100dvh, not 100vh, for full-height layouts)' },
  dock: { label: 'Scroll-end under fixed docks', state: 'scroll-end', rule: 'ios-dock: a list under a sticky/fixed bottom dock or header keeps the matching offset — the last item is fully visible and scrolling reaches it' },
  landscape: { label: 'Landscape', state: 'landscape', rule: 'ios-landscape: rotated, the insets move to the sides and nothing clips or overlaps' },
  overscroll: { label: 'Overscroll background', state: 'overscroll', rule: 'ios-overscroll: the rubber-band background matches the page — no white flash above or below' },
}
const IOS_DEFAULT_CHECKS = ['bars', 'safe-area', 'keyboard', 'dvh', 'dock']

function resolveMatrix(projectType, override) {
  const type = (override && override.projectType) || projectType || 'web'
  const matrix = (override && override.matrix) || MATRIX[type] || MATRIX.web
  const checklist = (override && override.checklist) || CHECKLIST[type] || CHECKLIST.web
  return { type, matrix, checklist, exclude: (override && override.exclude) || [] }
}

function parseViewport(v) {
  const m = /^(\d+)x(\d+)(?:@(\d+))?$/i.exec(String(v || ''))
  return m ? { width: Number(m[1]), height: Number(m[2]), scale: Number(m[3] || 2) } : null
}

// resolveLanes turns the test skill's answer (`args.lanes`) into lane
// objects the flow shoots, publishes and reviews. Without an answer the
// matrix rows become viewport (or simulator) lanes. Lane kinds:
//   viewport   — a browser at WxH@S (playwright + `board capture web --file`)
//   simulator  — a native app in the expo matrix's simulator (`board capture ios|android`)
//   ios-safari — a WEB app in Mobile Safari on the iOS Simulator (`board capture safari`)
function resolveLanes(requested, projectType, override) {
  const { type, matrix, checklist, exclude } = resolveMatrix(projectType, override)
  const list = requested && requested.length
    ? requested
    : matrix.map(d => (d.width ? { key: d.name, viewport: d.width + 'x' + d.height + '@' + d.scale } : { key: d.name }))
  const lanes = []
  for (const l of list) {
    const k = String(l.key || '').toLowerCase()
    if (k === 'ios-safari') {
      const checks = (l.checks && l.checks.length ? l.checks : IOS_DEFAULT_CHECKS).filter(c => IOS_CHECKS[c])
      const states = []
      for (const c of checks) if (states.indexOf(IOS_CHECKS[c].state) < 0) states.push(IOS_CHECKS[c].state)
      lanes.push({ key: 'ios-safari', kind: 'ios-safari', label: 'iOS Simulator · Safari', checks, states, rules: checks.map(c => IOS_CHECKS[c].rule) })
      continue
    }
    const base = matrix.find(d => d.name === k) || {}
    const vp = parseViewport(l.viewport) || (base.width ? { width: base.width, height: base.height, scale: base.scale || 2 } : null)
    if (vp) {
      const mobile = base.mobile !== undefined ? base.mobile : vp.width < 900
      lanes.push({
        key: k, kind: 'viewport', label: k + ' ' + vp.width + '×' + vp.height + '@' + vp.scale,
        width: vp.width, height: vp.height, scale: vp.scale,
        input: base.input || (mobile ? 'touch' : 'mouse'), mobile, safeArea: base.safeArea !== undefined ? base.safeArea : vp.width < 500,
      })
      continue
    }
    if (base.platform) {
      lanes.push({ key: k, kind: 'simulator', label: k + ' (' + base.platform + ' simulator ' + base.sim + ')', platform: base.platform, sim: base.sim })
      continue
    }
    throw new Error('test: lane "' + k + '" needs a viewport (WxH@S) or a device of the ' + type + ' matrix; the iOS Simulator web lane is key "ios-safari"')
  }
  return { type, lanes, checklist, exclude }
}

// What a run's RESOLVED lanes need started: `web` when a viewport lane
// browses the web app or the ios-safari lane loads it in Mobile Safari, and
// per simulator a lane opens by deep link, the native app — installed on that
// simulator and, for a development build, its bundler (Metro) serving it from
// this machine, where the simulators live. Asked lanes cannot decide it —
// "iphone" is a viewport on web and a simulator on expo, and no lanes at all
// means the matrix Prepare reads — so the apps start only after resolveLanes.
function appStarts(lanes) {
  const native = []
  for (const l of lanes) {
    if (l.kind === 'simulator' && !native.some(n => n.platform === l.platform && n.sim === l.sim)) native.push({ platform: l.platform, sim: l.sim })
  }
  return { web: lanes.some(l => l.kind !== 'simulator'), native }
}
// ---- lib/helpers.js — plain-code helpers shared by the Exp flows (no agents here)
const SEVERITY_RANK = { blocker: 3, major: 2, minor: 1 }

// Findings the loop fixes on its own: defects at or above the threshold.
// Suggestions and anything below stay staged on the board for the human.
function autoAcceptable(findings, threshold) {
  const min = SEVERITY_RANK[threshold] || SEVERITY_RANK.minor
  return findings.filter(f => f.kind === 'finding' && (SEVERITY_RANK[f.severity] || 0) >= min)
}

// The pass cap a run asked for: absent is 2, a number or numeric string is
// clamped to 1-6. Anything else (true, [], '', 'two') is null — the type is
// checked before any coercion, because Number(true) and Number([]) are
// finite and would pass as a cap nobody asked for.
function parseCap(raw) {
  if (raw === undefined || raw === null) return 2
  const n = typeof raw === 'number' ? raw : typeof raw === 'string' && raw.trim() ? Number(raw) : NaN
  return Number.isFinite(n) ? Math.max(1, Math.min(6, Math.floor(n))) : null
}

// How a pass ends once its fix list is known. A pass is shoot → review →
// accept → fix → gate, the final one included: `cap` bounds the passes, so
// the last pass still fixes what it accepted and only the reshoot that would
// verify it is dropped. 'clean' — nothing left to fix, retried carried
// findings included (see fixListFor); 'reshoot' — fix, gate, shoot again;
// 'last' — fix and gate, then stop; 'rewalk' — nothing to fix, but a fixed
// usertest failure no walk confirmed yet (`unwalked`, see unwalkedFixes: its
// tester died or skipped it) and a pass left: the next pass only walks it
// again — no shots, no review. At the cap it ends 'clean' with the fix
// unverified, which keeps the draft.
function passEnd(pass, cap, toFix, unwalked = 0) {
  if (toFix) return pass < cap ? 'reshoot' : 'last'
  return unwalked && pass < cap ? 'rewalk' : 'clean'
}

// Whether the run converged: it ended on a 'clean' pass (passEnd) with no
// finding left open, no fixed journey left unwalked, and no pass gate red. A
// red gate is sticky — the clean pass fixes nothing, so it runs no gate that
// could clear it — and a run whose gate went red never claims convergence.
function convergedAfter({ clean, open = [], unwalked = [], gateRed }) {
  return !!clean && !open.length && !unwalked.length && !gateRed
}

// A pass's fix list: what it filed and accepted (new findings, functional
// fails, regressions) plus every carried finding still open from earlier
// passes — a skipped finding goes back to a fixer each pass until one fixes
// it or the cap ends the run, since reviewers never refile it. A carried
// off-scope finding (inScope false: its first fixer already had the 2-file
// allowance) is the report's bug, never another attempt. One entry per key,
// the fresh ones first.
function fixListFor(fresh, carried) {
  const byKey = new Map()
  for (const f of [...fresh, ...carried.filter(f => f.inScope !== false)]) if (!byKey.has(f.key)) byKey.set(f.key, f)
  return [...byKey.values()]
}

// A failed usertest case's finding key: its lane and its title (the
// journey's), never the pass or the case's index, so a failure refiled in a
// later pass is the carried finding — fixing it there closes that one.
function usertestKey(title, lane) {
  return `usertest-${slugify(lane)}-${slugify(title)}`
}

// The journeys the next pass walks: every one whose steps pass a route still
// open or just touched, and every one whose failure a fixer claimed fixed
// (`fixed`: those functional findings, still unwalked — see unwalkedFixes),
// matched by its stable usertestKey, never by route: a fixed journey is no
// longer open and its steps need not name a route, so only walking it again
// verifies the fix. A fixed failure no journey matches (an exploratory case)
// adds none — the tester walks it under its own title (rewalkCases). With
// nothing picked, the journeys that failed this pass, and all of them when a
// failure matches none.
function journeysToRerun(allJourneys, openRoutes, fixed, cases) {
  const walks = (j, f) => f.key === usertestKey(j.title, f.lane)
  const picked = allJourneys.filter(j => (j.steps || []).some(s => openRoutes.some(p => p && s.includes(p))) || fixed.some(f => walks(j, f)))
  if (picked.length) return picked
  const failed = cases.filter(c => c.verdict === 'fail')
  const byTitle = allJourneys.filter(j => failed.some(c => c.title === j.title))
  return byTitle.length || !failed.length ? byTitle : allJourneys
}

// The fixed usertest failures still waiting for a walk to confirm them. A
// case the pass walked for the journey on its lane settles one — a pass, or
// a fail refiled as a fresh finding under the same key; a skipped case or
// none leaves it waiting, and a run that ends with one waiting keeps its
// draft (notReadyReasons).
function unwalkedFixes(pending, cases, lane) {
  const walked = new Set(cases.filter(c => c.verdict !== 'skip').map(c => usertestKey(c.title, c.lane || lane)))
  return pending.filter(f => !walked.has(f.key))
}

// A pass's failed usertest cases as functional findings, keyed by lane (none
// named: the usertest lane) and title, and carrying the title itself — the
// one handle a later walk settles it by (unwalkedFixes).
function functionalFindings(cases, lane) {
  return cases.filter(c => c.verdict === 'fail').map(c => ({
    key: usertestKey(c.title, c.lane || lane), title: c.title, route: '', lane: c.lane || lane, area: (c.files && c.files[0]) || 'functional',
    kind: 'finding', severity: 'major', rule: 'functional', summary: `${c.title}: ${c.note || 'failed'}`, files: c.files || [], inScope: true,
  }))
}

// The fixed failures the next tester walks again, each as ONE case under its
// own title: a case no journey matches (an exploratory one) is walked only
// because it is handed over here, and the walk under that title is what
// settles it.
function rewalkCases(fixed) {
  return fixed.map(f => ({ title: f.title, failed: f.summary }))
}

// The case a route gets on one lane where the run leaves no finding open. A
// pass is earned, never assumed: this lane captured the route, a reviewer
// judged that capture, and no fix landed on the route after it. Anything
// less — unreachable, a failed shooter or publish, a shots run, a fix the
// cap left without a reshoot — is a skip naming why.
// captures: [{pass, lane, route, judged}] · fixed: [{pass, route}] — a fix
// has no lane (see affectedRoutes).
function routeVerdict(path, lane, captures, fixed) {
  const latest = list => list.reduce((a, x) => (!a || x.pass >= a.pass ? x : a), null)
  const shot = latest(captures.filter(x => x.lane === lane && x.route === path))
  if (!shot) return { verdict: 'skip', why: 'never captured on this lane' }
  if (!shot.judged) return { verdict: 'skip', why: `captured in pass ${shot.pass}, never reviewed`, pass: shot.pass }
  const fix = latest(fixed.filter(x => x.route === path))
  if (fix && fix.pass >= shot.pass) return { verdict: 'skip', why: `fixed in pass ${fix.pass} after its last capture, never reshot`, pass: shot.pass }
  return { verdict: 'pass', pass: shot.pass }
}

// Whether a lane's reviewer judged its capture: it returned the card ids it
// read, and they cover every card the lane published this pass with a route
// on it — the cards that count as captures; a route-less card (a section
// summary) has no screen to judge. A reply alone — {findings: []} with
// nothing read — proves no card was looked at, so the lane's routes stay
// unjudged (a skip, never a pass).
function laneJudged(review, cards) {
  if (!review || !Array.isArray(review.screensRead)) return false
  const read = new Set(review.screensRead)
  return cards.filter(c => c.route).every(c => read.has(c.cardId))
}

// The routes a pass's fixes may have changed, on EVERY lane — a fix edits
// code every lane renders. The routes they name (the fixed findings' own and
// the fixers' touched ones, sub-routes included) together with the routes
// whose implementing file they touched — a named route never hides a file
// edit elsewhere. A change nobody can place is verified everywhere: a touched
// file no route implements (a shared header, a route with no `file`) and a
// change that places nowhere reach every route. Nothing touched changes
// nothing. The next pass reshoots these, and each stays unverified until a
// capture is judged.
function affectedRoutes(allRoutes, paths, files) {
  const named = paths.filter(Boolean)
  const rel = f => String(f).replace(/^\.\//, '')
  const touched = files.filter(Boolean).map(rel)
  if (!named.length && !touched.length) return []
  // The terrain's file is repo-relative; a fixer may report it absolute.
  const implementsFile = (r, f) => !!r.file && (f === rel(r.file) || f.endsWith('/' + rel(r.file)))
  if (touched.some(f => !allRoutes.some(r => implementsFile(r, f)))) return allRoutes.map(r => r.path)
  const hit = allRoutes.filter(r => named.some(p => r.path === p || r.path.startsWith(p)) || touched.some(f => implementsFile(r, f)))
  return (hit.length ? hit : allRoutes).map(r => r.path)
}

// The files a pass gate's repair commits changed — like the fixers' edits,
// they postdate the pass's captures. [] when it repaired nothing; null when
// it repaired without naming them: a change nobody can place.
function gateRepairFiles(gate) {
  if (!gate || !gate.repaired) return []
  const files = (gate.touchedFiles || []).filter(Boolean)
  return files.length ? files : null
}

// The keys a pass fixed where nobody can place the change: the finding has
// no route of its own (a functional failure's is '', an unknown key has
// none) and the fixer that reported it named no touched route and no
// touched file. Its commit still postdates every capture — empty metadata is
// no proof nothing changed — so, like a gate repair naming no files, it
// unverifies every route (affectedRoutes' "a change nobody can place").
function unplacedFixes(fixResults, fixList) {
  const routeOf = k => (fixList.find(f => f.key === k) || {}).route
  return fixResults
    .filter(r => !(r.touchedRoutes || []).some(Boolean) && !(r.touchedFiles || []).some(Boolean))
    .flatMap(r => (r.fixed || []).filter(k => !routeOf(k)))
}

// What a run that fixes nothing leaves open: every defect it filed, at any
// severity — the threshold is a fix decision and a review-only run makes
// none — and every usertest case that failed (`functional`: the usertest
// stage files each through `finish --bugs direct`). Suggestions are taste,
// never bugs: they stay staged on the board.
function openWithoutFixing(filed, functional) {
  return [...filed.filter(f => f.kind === 'finding'), ...functional]
}

// Why a run's draft PR stays a draft; empty means the run earned "ready".
// Every fix run ends in the code loop's review of the final diff — a run
// whose passes fixed nothing still carries the whole branch diff, and
// nothing before the device pass reviewed it. Returning is not enough: the
// loop must leave nothing for the human and end on a green gate (each round
// gates the same suites, so its LAST round is the branch's state). `lanes`
// are the run's lane keys: a lane the receipt leaves out was not published.
// A published lane is not a judged one: every route case the record files
// must be a pass (routeVerdict) — a lane nobody captured or reviewed, and a
// fix the cap left without a reshoot, keep the draft. The code loop runs
// after the record, so anything it commits — a review fix, a gate repair, a
// push from prm's first round — postdates every capture and names no files
// to place it: a change nobody can place unverifies every route
// (affectedRoutes). So the PR head and the checkout's HEAD must still be the
// commit the record was filed at (`recordSha`, `heads`). A fixed usertest
// failure no later walk of its journey confirmed (`unwalked`) is no pass.
function notReadyReasons(run) {
  const { fixes, code, recordSha, heads } = run
  const why = recordReasons(run)
  if (fixes) {
    const last = code && code.rounds.length ? code.rounds[code.rounds.length - 1] : null
    if (!last) why.push('the code loop did not review the diff')
    else {
      if (code.remaining.length) why.push(`${code.remaining.length} code-review findings left for the human`)
      if (!last.green) why.push("the code loop's last gate is red")
      const same = (a, b) => a.length >= 7 && b.length >= 7 && (a.startsWith(b) || b.startsWith(a))
      if (!recordSha || !heads || !heads.head || !heads.prHead) why.push('the PR head could not be compared with the device record')
      else {
        const moved = [heads.prHead, heads.head].find(s => !same(s, recordSha))
        if (moved) why.push(`the branch moved after the device record (${recordSha.slice(0, 9)} → ${moved.slice(0, 9)}) — no device pass verified the change`)
      }
    }
  }
  return why
}

// The part of notReadyReasons the device record alone decides — known once
// the run door has filed it, before the code loop runs: the reasons the early
// PR-state step names when it returns a PR ready for review to draft before
// code-loop's prm pushes to it (codeLoopPushHold). A clean record has none,
// but the step runs anyway — the code loop's review is still ahead.
function recordReasons({ fixes, open, lanes, report, gateRed, routeCases, unwalked = [] }) {
  const why = []
  if (!fixes) why.push('thoroughness is not "fix"')
  if (open.length) why.push(`${open.length} findings open`)
  if (unwalked.length) why.push(`${unwalked.length} fixed journeys never walked again`)
  if (!report || !lanes.every(k => report.lanes.some(l => l.key === k && l.published))) why.push('the run door did not publish every lane')
  for (const k of lanes) {
    const cases = routeCases[k] || []
    const unearned = cases.filter(c => c.verdict !== 'pass').length
    if (unearned) why.push(`lane ${k}: ${unearned} of ${cases.length} routes earned no pass`)
  }
  if (gateRed) why.push('a pass gate stayed red')
  return why
}

// What a PR-state step left: `want` is the state the run earned ('ready' when
// notReadyReasons is empty, else 'draft'); the step ran the idempotent
// `gh pr ready` or `gh pr ready --undo` whatever state it found — a guessed
// "already a draft" never skips the call — and read the state before
// (wasDraft) and after (isDraft), leaving out one it could not read. The
// earned state holds only when the read-back says so; `demoted` is a PR the
// run took back from ready for review, which the hand-back says.
function prOutcome(want, step) {
  const after = step && typeof step.isDraft === 'boolean' ? step.isDraft : null
  const held = after === (want === 'draft')
  return {
    ready: want === 'ready' && held,
    draft: want === 'draft' && held,
    demoted: want === 'draft' && held && step.wasDraft === false,
    problem: held ? '' : `${want === 'ready' ? 'readying' : 'returning to draft'} failed: ${(step && step.why) || (step ? 'its state could not be read back' : 'no result')}`,
  }
}

// Why the code loop must not push — '' when it may. Its PR phase is prm
// pushing the branch to its PR, and a PR ready for review with auto-merge
// armed (or under MERGE_POLICY=self) can merge on that push. No fix run has
// earned ready before the code loop — even a clean record still awaits its
// review — so every one pushes only where the early PR-state step (`early`)
// proved no ready PR takes the push: the PR reads back a draft, or the branch
// has none (url "" with `none` — the lookup answered "no pull requests found",
// which `gh pr view` reports by exiting 1, so a `why` beside it is that answer,
// not a failure; no PR `named`) and the loop opens its own as a draft. A
// missing result, an unread state, a PR still ready or a url "" nothing
// proved absent holds the push: the loop reviews and gates, and its commits
// stay local.
function codeLoopPushHold(early, named) {
  if (!early || early.url) return prOutcome('draft', early).problem
  if (named) return `pull request ${named} could not be read${early.why ? `: ${early.why}` : ''}`
  if (early.none) return ''
  return `the branch's pull request could not be read: ${early.why || 'no lookup proved it has none'}`
}

// Each lane manifest's stamp, keyed by lane: the ONE head the record is filed
// at — read after every pass fixer and gate repair committed, and the same
// sha readiness compares (notReadyReasons' `recordSha`) — names both the
// manifest's `sha` and its `runId`, which fits the run door's
// ^[A-Za-z0-9._-]{1,64}$ whatever the run is called. `run` is the slug of
// the run board this invocation minted: the door replaces the cards a
// previous publish of the same runId left, so a second run on an unchanged
// commit must never reuse the first one's ids.
function manifestStamps(run, head, lanes) {
  return Object.fromEntries(lanes.map(lane => {
    const tail = `-${head.slice(0, 9)}-${boundedSlug(lane, 32)}`
    return [lane, { runId: boundedSlug(run, 64 - tail.length) + tail, sha: head }]
  }))
}

// A runId part of at most `max` chars: a longer slug keeps its head plus a
// hash of the whole, so two run boards or custom lanes sharing a long prefix
// still get distinct runIds.
function boundedSlug(s, max) {
  const slug = slugify(s)
  if (slug.length <= max) return slug
  let h = 0x811c9dc5
  for (const c of slug) h = Math.imul(h ^ c.charCodeAt(0), 0x01000193) >>> 0
  return `${slug.slice(0, max - 9)}-${h.toString(16).padStart(8, '0')}`
}

// Group findings by area into at most `max` disjoint fix lists. A finding
// whose files also appear in another area is `shared` and runs first, so
// the parallel fixers never edit the same file.
function groupByArea(findings, max) {
  const byArea = new Map()
  for (const f of findings) {
    const area = f.area || 'misc'
    if (!byArea.has(area)) byArea.set(area, [])
    byArea.get(area).push(f)
  }
  const fileOwners = new Map()
  for (const [area, list] of byArea) {
    for (const f of list) for (const file of f.files || []) {
      if (!fileOwners.has(file)) fileOwners.set(file, new Set())
      fileOwners.get(file).add(area)
    }
  }
  const shared = []
  for (const [area, list] of byArea) {
    const keep = []
    for (const f of list) {
      const crosses = (f.files || []).some(file => fileOwners.get(file).size > 1)
      if (crosses) shared.push(f); else keep.push(f)
    }
    byArea.set(area, keep)
  }
  let groups = [...byArea].filter(([, l]) => l.length).map(([area, list]) => ({ area, findings: list }))
  groups.sort((a, b) => b.findings.length - a.findings.length)
  while (groups.length > max) {
    const tail = groups.pop()
    const smallest = groups[groups.length - 1]
    smallest.area = smallest.area + '+' + tail.area
    smallest.findings.push(...tail.findings)
  }
  return { shared: shared.length ? { area: 'shared', findings: shared } : null, groups }
}

function uniq(list) {
  return [...new Set(list.filter(Boolean))]
}

function key(f) {
  return f.key || (f.cardId + ':' + f.summary)
}

function slugify(s) {
  return String(s || '').replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase()
}
// args: { task: string, project?, lanes?: [{key, viewport?, checks?}], thoroughness?: 'shots'|'review'|'fix',
//         cap?: 2, severity?: 'major', routes?, journeys?, projectType?, scope?: string, scopeFiles?: string[],
//         pr?: 'owner/repo#n', base?: 'main', board?: string }
const A = args || {}
if (!A.task) throw new Error('test: args.task (the epic or story the run belongs to) is required — the run door files its record there')
const THOROUGHNESS = ['shots', 'review', 'fix']
const thoroughness = A.thoroughness || 'fix'
if (THOROUGHNESS.indexOf(thoroughness) < 0) throw new Error(`test: args.thoroughness must be one of ${THOROUGHNESS.join(' | ')}, got ${JSON.stringify(A.thoroughness)}`)
const reviews = thoroughness !== 'shots'
const fixes = thoroughness === 'fix'
const capAsked = parseCap(A.cap)
if (capAsked === null) throw new Error(`test: args.cap must be a number of passes 1-6, got ${JSON.stringify(A.cap)}`)
const cap = fixes ? capAsked : 1
const threshold = A.severity || 'major'
if (!SEVERITY_RANK[threshold]) throw new Error(`test: args.severity must be blocker | major | minor, got ${JSON.stringify(A.severity)}`)

phase('Prepare')
// Which lanes a run has hangs on the project type and the repo's matrix, both
// read here — so the apps start below, once the lanes are resolved (appStarts).
const prep = await agent(withPreamble(
  `Prepare this checkout for a device test run (task ${A.task}).\n` +
  `1. Report the current branch, the short HEAD sha and the vitrinka project the repo is bound to (\`vitrinka status\` / the repo's .vitrinka descriptor).\n` +
  `2. ${RUN_RULE} Start nothing here: the run starts what its lanes need once they are known.\n` +
  `3. Decide projectType (web | expo | cli | other) from the repo.\n` +
  `Never create tasks, boards or commits here.`
), { label: 'prepare', phase: 'Prepare', schema: TARGET_SCHEMA })
if (!prep) throw new Error('test: prepare failed')
const task = String(A.task)
const project = A.project || prep.project || ''
const override = prep.override || {}
const run = resolveRun(override)
const { type, lanes, checklist, exclude } = resolveLanes(A.lanes, A.projectType || prep.projectType, override)
if (!lanes.length) throw new Error(`test: no lanes to run — pass args.lanes or give project type ${type} a matrix`)
const starts = appStarts(lanes)
prep.baseUrl = ''
prep.scheme = ''
if (starts.web) {
  const app = await agent(withPreamble(
    `Start the app for branch ${prep.branch} ${prep.where === 'devbox' ? `on this branch's devbox workspace (\`devbox run -- '<cmd>'\`) — never a local fallback` : 'on this machine, never a devbox'} the way CLAUDE.md prescribes; wait until it answers; return the reachable base URL${A.base ? ` (requested: ${A.base})` : ''}.${lanes.some(l => l.kind === 'ios-safari') ? ' The ios-safari lane opens the SAME url from this machine\'s simulator, so a devbox url must be reachable from here.' : ''} A url you cannot reach is baseUrl "" with a \`problems\` line naming why. Never create tasks, boards or commits here.`
  ), { label: 'app', phase: 'Prepare', schema: APP_SCHEMA })
  prep.baseUrl = (app && app.baseUrl) || ''
  if (!prep.baseUrl) throw new Error(`test: no app url — the run target (${run.web}, ${prep.where}) could not be honoured: ${JSON.stringify([...(prep.problems || []), ...((app && app.problems) || ['no result'])])}`)
}
// A simulator lane opens the native app by deep link, and a development build
// shows only its launcher without the bundler serving it — so the app is
// installed and served before any shooter or tester opens it, always on this
// machine (lib/run.js: the simulators live here).
const sims = starts.native.map(s => `the ${s.sim} ${s.platform} simulator`).join(' and ')
if (starts.native.length) {
  const native = await agent(withPreamble(
    `Make the ${type} app of branch ${prep.branch} openable by deep link on ${sims}, on THIS machine — never a devbox. Boot each simulator; build and install the branch's native app the way CLAUDE.md or the repo's scripts prescribe (its development build, or the build the repo ships); start the dev server that build loads its JavaScript from (Metro for Expo / React Native) and leave it running; then open the app once per simulator and confirm it shows the app itself — never a dev-client launcher ("No development servers found"), a red error screen or a blank one. Return ready, the deep-link scheme routes open with, and a \`problems\` line naming anything that failed. Never create tasks, boards or commits here.`
  ), { label: 'native', phase: 'Prepare', schema: NATIVE_SCHEMA })
  if (!native || !native.ready) throw new Error(`test: the native app does not open on ${sims}: ${JSON.stringify((native && native.problems) || ['no result'])}`)
  prep.scheme = native.scheme || ''
}
log(`test: ${type} on ${prep.branch} at ${prep.baseUrl || '(no web app)'}${sims ? `, native app served to ${sims}` : ''} (${prep.where}, run.web=${run.web}); lanes ${lanes.map(l => l.key).join(', ')}; ${thoroughness}, cap ${cap}, threshold ${threshold}`)

phase('Map')
let terrain = A.routes ? { routes: A.routes, journeys: A.journeys || [] } : null
if (!terrain) {
  try {
    terrain = await workflow('vitrinka:map', { scope: 'app', screens: false, project, task, push: false })
  } catch (e) {
    log(`test: map workflow unavailable (${e && e.message}); inventorying inline`)
    terrain = await agent(withPreamble(
      'Read-only: inventory every route/screen a user can reach in this repo (path, title, implementing file, auth, how to reach it with data on screen) and the 3-8 journeys a real user walks. Prefer the repo\'s own route tables and navigators over file-name guesses.'
    ), { label: 'inventory', phase: 'Map', agentType: 'Explore', schema: TERRAIN_SCHEMA })
  }
}
if (!terrain || !terrain.routes || !terrain.routes.length) throw new Error('test: no routes to shoot')
const allRoutes = terrain.routes.filter(r => !exclude.some(x => r.path === x || r.path.startsWith(x.replace(/\*$/, ''))))
const allJourneys = terrain.journeys || []
log(`test: ${allRoutes.length} routes, ${allJourneys.length} journeys`)

phase('Run board')
const runBase = A.board || override.board || `${slugify(prep.branch)}-test-run`
const board = await agent(withPreamble(
  `Mint the run board for this device test run through the lanes door.\n` +
  `1. Count the boards whose slug starts with "${runBase}-" (\`list {kind: "board"${project ? `, project: "${project}"` : ''}}\`); n = that count + 1.\n` +
  `2. \`create {kind: "board", slug: "${runBase}-<n>", title: "Test run <n> · ${prep.branch}", board_type: "review"${project ? `, project: "${project}"` : ''}, meta: {task: "${task}", branch: "${prep.branch}", sha: "${prep.sha || ''}", thoroughness: "${thoroughness}"}, lanes: ${JSON.stringify(lanes.map(l => ({ key: l.key, label: l.label })))}}\` — ONE call: the server mints the run board (the Overview tab) and one child board per lane (each a tab); a 409 on the slug means the run exists — reuse it and read its lanes from the receipt or \`get\`.\n` +
  `Return the run board's server url and slug and, per lane key, the child board's slug and url.`
), { label: 'board', phase: 'Run board', schema: RUNBOARD_SCHEMA })
if (!board || !board.lanes.length) throw new Error('test: the lanes door minted no run board')
const laneBoard = key => board.lanes.find(l => l.key === key)
for (const l of lanes) if (!laneBoard(l.key)) throw new Error(`test: the run board has no tab for lane ${l.key}`)
log(`test: run board ${board.boardUrl} with ${board.lanes.length} lanes`)

const captureRoot = (pass, lane) => `.vitrinka/screenshots/test-run/pass-${pass}/${lane}`
const ledgerTail = (pass, lane) => `--label pass${pass}/${lane}/<route-slug> --title "<title>" --note "<what is on screen>" --src <implementing file> --root ${captureRoot(pass, lane)} --yes`
const shootPrompt = (l, pass, routes) => {
  const head = `Shoot pass ${pass} of a device test run, lane ${l.label} (key ${l.key})${prep.baseUrl ? ` against ${prep.baseUrl}` : ''}.\nRoutes (shoot every one, with data on screen; a route needing setup says how):\n${JSON.stringify(routes)}\nRead \`docs {topic: "guide:publish-capture"}\` first. `
  if (l.kind === 'viewport') {
    return head + `For each route: open it at exactly ${l.width}×${l.height}@${l.scale} (${l.input}${l.safeArea ? ', safe-area insets emulated' : ''}), wait for it to settle, scroll the whole page once so lazy content is present, then capture 2× and adopt it with \`vitrinka board capture web --file <png> --route <path> --device ${l.key} --viewport ${l.width}x${l.height}@${l.scale} ${ledgerTail(pass, l.key)}\`.${l.mobile ? ' Also capture one screen with a menu/sheet open when the route has one.' : ''} Read each saved image back and re-shoot a blank or half-loaded one. Return every shot (state "default"); a route you could not reach is a \`problems\` line naming why.`
  }
  if (l.kind === 'simulator') {
    return head + `For each route: open it in the ${l.sim} simulator through its deep link${prep.scheme ? ` (scheme \`${prep.scheme}://\`)` : ''} and capture it with \`vitrinka board capture ${l.platform} --open <deep link> --route <path> --device ${l.key} ${ledgerTail(pass, l.key)}\`. Read each saved image back and re-shoot a blank one. Return every shot (state "default"); a route you could not reach is a \`problems\` line naming why.`
  }
  return head + `This lane is Mobile Safari on the iOS 26 Simulator, driven through \`vitrinka board capture safari\` (Appium XCUITest — the verb boots the simulator and the driver itself). States to capture per route: ${JSON.stringify(l.states)}. For each route and each state: \`vitrinka board capture safari --url ${prep.baseUrl}<path> --state <state> --route <path> --device ios-safari ${ledgerTail(pass, 'ios-safari').replace('<route-slug>', '<route-slug>/<state>')}\`; for state "keyboard" add \`--type "<selector of the route's first text input>"\` (skip the state on a route without one and say so in problems); the verb writes the png, adopts it and stores the measured safe-area insets in the ledger. Return every shot with its state; a route or state you could not capture is a \`problems\` line naming why.`
}
const utLane = lanes.find(l => l.kind === 'viewport') || lanes[0]
const utPlatform = utLane.kind === 'simulator' ? utLane.platform : 'web'
const utDevice = utLane.kind === 'simulator' ? utLane.key : 'desktop'

let routes = allRoutes
let journeys = allJourneys
let regressList = []
const passes = []
let openFindings = []
// carried: every accepted finding not yet fixed, by key, ACROSS passes — a
// skipped finding rides every later pass's fix list (fixListFor) until one
// fixes it, an off-scope one stays open for the report; a clean later pass
// never forgets either.
const carried = new Map()
let offScopeFindings = []
// Fixed in the pass the cap ended: gated, but no reshoot confirmed them — the
// routes they touched earn no pass, so the draft stays a draft.
let unverified = []
// Fixed usertest failures no later walk of their journey has confirmed yet
// (unwalkedFixes): each next pass walks them (journeysToRerun), and one still
// waiting when the run ends keeps the draft.
let unwalked = []
let clean = false
// A 'rewalk' pass end (passEnd): the next pass only walks the unwalked fixes
// again — nothing changed since the last shots, so it shoots and reviews nothing.
let walkOnly = false
let gateRed = false
let lastPub = {}
// What the run actually judged, for the report's per-route verdicts: every
// route a lane published per pass (judged when that lane's reviewer
// returned), every route a pass's fixes may have changed (on every lane),
// and the shooters' problems.
const captures = []
const fixedLog = []
const problems = {}

for (let pass = 1; pass <= cap; pass++) {
  const ph = `Pass ${pass}`
  phase(ph)
  log(walkOnly ? `${ph}: walking ${unwalked.length} fixed journeys again, nothing to shoot` : `${ph}: shooting ${routes.length} routes on ${lanes.length} lanes${reviews ? `, ${journeys.length} journeys` : ''}`)

  const shooters = walkOnly ? [] : lanes.map(l => () => agent(withPreamble(shootPrompt(l, pass, routes)), { label: `shoot:${l.key}`, phase: ph, schema: SHOOT_SCHEMA }))
  const tester = () => agent(withPreamble(
    `Exploratory usertest, pass ${pass}${prep.baseUrl ? ` against ${prep.baseUrl}` : ''} on ${utLane.label}.\n` +
    `Journeys to walk:\n${JSON.stringify(journeys)}\n${A.scope ? `Focus: ${A.scope}\n` : ''}` +
    (unwalked.length ? `Fixed failures to walk again — each is ONE case under exactly this title (a journey above with the same title is that case), so the run can tell the fix held:\n${JSON.stringify(rewalkCases(unwalked))}\n` : '') +
    `Follow the vitrinka usertest skill's lane 2 (\`vitrinka qa usertest start --task ${task} --app ${type} --platform ${utPlatform} --device ${utDevice} --yes\`, then \`case\`, captures, \`verdict\`, and \`finish --bugs direct --yes\`). One case per journey, titled with the journey's title verbatim (a failure is tracked across passes by that title); a fail carries --note with the exact contract broken and the implementing files. Understand before judging: read the code behind a suspicious behaviour. Never touch production tenants. Return the cases with verdicts and the bug task urls \`finish\` printed.`
  ), { label: 'usertest', phase: ph, schema: USERTEST_SCHEMA })

  const results = (await parallel(reviews && (journeys.length || unwalked.length) ? [...shooters, tester] : shooters)).filter(Boolean)
  const shots = results.filter(r => r.shots)
  const ut = results.find(r => r.cases) || { cases: [], bugs: [] }
  const shotCount = shots.reduce((n, s) => n + s.shots.length, 0)
  if (!shotCount && !walkOnly) throw new Error(`${ph}: no screenshots captured — the app, the browser or the simulator is not reachable`)
  unwalked = unwalkedFixes(unwalked, ut.cases, utLane.key)

  const pubs =(await parallel(lanes.map(l => () => {
    const set = shots.find(s => s.lane === l.key)
    if (!set) return Promise.resolve(null)
    const lb = laneBoard(l.key)
    return agent(withPreamble(
      `Compose pass ${pass} of lane "${l.label}" onto ITS OWN board — slug ${lb.slug} (${lb.url}), a tab of the run board ${board.boardSlug}${project ? `, project ${project}` : ''}, task ${task}.\n` +
      `Set captured this pass (capture root ${captureRoot(pass, l.key)}): ${JSON.stringify(set.shots)}.\n` +
      `Structure: section "Pass ${pass}" — ${l.kind === 'ios-safari' ? 'one row per route, the states of that route side by side in this order: ' + l.states.join(', ') : 'shots in route order, one row'}; a summary card at the section head naming the pass, the lane, the shot count${l.kind === 'ios-safari' ? ' and the measured safe-area insets from the ledger' : ''}. Earlier pass sections stay untouched. Return the board's server url, its slug, the section title and every shot card id with its route, lane and state.`
    ), { label: `publish:${l.key}`, phase: ph, agentType: 'vitrinka:vitrinka-publisher', schema: PUBLISH_SCHEMA })
  }))).filter(Boolean)
  if (!pubs.length && !walkOnly) throw new Error(`${ph}: publishing failed on every lane`)
  for (const p of pubs) lastPub[p.boardSlug] = p

  let filed = []
  let regressions = []
  const judgedLanes = new Set()
  if (reviews) {
    const reviewers = lanes.map(l => () => {
      const p = pubs.find(x => x.boardSlug === laneBoard(l.key).slug)
      if (!p) return Promise.resolve(null)
      // Accepted in an earlier pass and not fixed: filed once, one bug each.
      const stillOpen = [...carried.values()].filter(f => f.lane === l.key && f.route)
      return agent(withPreamble(
        `Local review (you are the reviewer, no server-side judge) of pass ${pass}, lane ${l.label}, on board ${p.boardSlug} (${p.boardUrl}).\n` +
        `Cards in scope: ${JSON.stringify(p.cards)}.\n` +
        `Read \`review_brief${project ? ` {project: "${project}"}` : ''}\` and judge against it PLUS this checklist:\n- ${checklist.join('\n- ')}\n` +
        (l.kind === 'ios-safari' ? `PLUS the iOS 26 rules this lane was asked for (each is one capture state — judge the state that carries it):\n- ${l.rules.join('\n- ')}\n` : '') +
        (A.scope || (A.scopeFiles && A.scopeFiles.length) ? `Feature scope: ${A.scope || ''}${A.scopeFiles && A.scopeFiles.length ? ` — files ${JSON.stringify(A.scopeFiles)}` : ''}. Mark each finding inScope true when its fix lives in that scope, false otherwise (off-scope defects are still filed — they become bugs, not fixes).\n` : '') +
        `Read every card's pixels with get_card_image before filing anything (cross-cutting problems show only across the set). File ONE \`annotate {board, agent: "claude-code", items: [...]}\` batch: each item keyed \`p${pass}-${l.key}-<n>\`, region measured on the source pixels, category = the rule id, severity blocker|major|minor, and detail naming the implementing files and what correct looks like. Sort defects as kind "finding" and taste as "suggestion".\n` +
        (regressList.length ? `Regression check — these findings were fixed last pass; for each, look at the same route in this lane and report fixed true/false with a note:\n${JSON.stringify(regressList.filter(f => f.lane === l.key).map(f => ({ key: f.key, id: f.id, route: f.route, summary: f.summary })))}\n` : '') +
        (stillOpen.length ? `Already filed and still open on this lane (accepted earlier, not fixed) — never file these again, under any key; file only defects not on this list:\n${JSON.stringify(stillOpen.map(f => ({ key: f.key, id: f.id, route: f.route, summary: f.summary })))}\n` : '') +
        `Return every finding with its annotation id from the receipt, its route, lane "${l.key}", state, an \`area\` (the component or route the fix lives in), inScope and the files it names; and \`screensRead\`: the card id of every card whose pixels you read — a card left out is a route you did not judge.`
      ), { label: `review:${l.key}`, phase: ph, schema: FINDINGS_SCHEMA })
    })
    const byLane = await parallel(reviewers)
    // A lane is judged only when its reviewer read every card it published.
    byLane.forEach((r, i) => {
      const k = lanes[i].key
      const p = pubs.find(x => x.boardSlug === laneBoard(k).slug)
      if (!p) return
      if (laneJudged(r, p.cards)) judgedLanes.add(k)
      else if (r) { const shots = p.cards.filter(c => c.route); log(`${ph}: lane ${k} reviewer read ${shots.filter(c => (r.screensRead || []).includes(c.cardId)).length} of ${shots.length} shot cards — its routes stay unjudged`) }
    })
    // A finding belongs to the lane whose reviewer filed it, whatever lane it echoes.
    const revs = byLane.map((r, i) => r && { ...r, findings: r.findings.map(f => ({ ...f, lane: lanes[i].key })) }).filter(Boolean)
    const seen = new Set()
    filed = revs.flatMap(r => r.findings).filter(f => { const k = key(f); if (seen.has(k)) return false; seen.add(k); return true })
    regressions = revs.flatMap(r => r.regressions || [])
  }
  for (const l of lanes) {
    const set = shots.find(s => s.lane === l.key)
    if (set && set.problems && set.problems.length) problems[l.key] = uniq([...(problems[l.key] || []), ...set.problems.map(p => `pass ${pass}: ${p}`)])
    // A route is captured on a lane when its card reached the lane's board —
    // those cards are all the reviewer is shown, never the shooter's list.
    const pub = pubs.find(p => p.boardSlug === laneBoard(l.key).slug)
    if (!pub) continue
    for (const route of uniq(pub.cards.map(c => c.route))) captures.push({ pass, lane: l.key, route, judged: judgedLanes.has(l.key) })
  }
  const regressed = regressList.filter(f => regressions.some(r => r.key === f.key && r.fixed === false))
  const functional = functionalFindings(ut.cases, utLane.key)
  const accepted = fixes ? autoAcceptable(filed, threshold) : []
  const fixList = fixListFor([...accepted, ...functional, ...regressed], [...carried.values()])
  const parked = filed.length - accepted.length
  passes.push({ pass, shots: shotCount, filed: filed.length, functionalFails: functional.length, regressed: regressed.length, toFix: fixes ? fixList.length : 0, parked })
  log(`${ph}: ${shotCount} shots, ${filed.length} findings filed (${parked} left staged for the human), ${functional.length} functional fails, ${regressed.length} regressions, ${carried.size} carried open`)

  // Overview tab: one summary row per lane on the run board itself.
  await agent(withPreamble(
    `Update the Overview of run board ${board.boardSlug} (${board.boardUrl}) for pass ${pass}: section "Pass ${pass}" holding one summary card per lane in this order ${JSON.stringify(lanes.map(l => l.key))} — lane label, shot count, findings filed, accepted, functional fails — each with a portal card (kind "board") to that lane's board (${JSON.stringify(board.lanes)}), plus one verdict card for the pass (${fixes ? 'fixing ' + fixList.length : reviews ? filed.length + ' findings for the human' : 'shots only'}). Earlier pass sections stay untouched. Return the board url.`
  ), { label: 'overview', phase: ph, agentType: 'vitrinka:vitrinka-publisher', effort: 'low' })

  if (!fixes) { openFindings = openWithoutFixing(filed, functional); offScopeFindings = openFindings.filter(f => f.inScope === false); break }
  for (const f of fixList) if (!carried.has(f.key)) carried.set(f.key, f)
  const end = passEnd(pass, cap, fixList.length, unwalked.length)
  if (end === 'clean') {
    clean = true
    openFindings = [...carried.values()]
    log(`${ph}: clean — no new fixable findings${openFindings.length ? `; ${openFindings.length} carried from earlier passes stay open` : unwalked.length ? `; ${unwalked.length} fixed journeys never walked again` : gateRed ? '; a pass gate stayed red, so the run did not converge' : ' — loop converged'}`)
    break
  }
  if (end === 'rewalk') {
    walkOnly = true
    journeys = journeysToRerun(allJourneys, [], unwalked, ut.cases)
    log(`${ph}: nothing to fix, ${unwalked.length} fixed journeys never walked again — the next pass only walks them`)
    continue
  }

  // Only this pass's accepted findings are still staged: the door refuses the
  // whole batch over one carried or regressed id it accepted in an earlier pass.
  const byBoard = new Map()
  for (const f of accepted) if (f.id) { const slug = laneBoard(f.lane || '') ? laneBoard(f.lane).slug : board.boardSlug; if (!byBoard.has(slug)) byBoard.set(slug, []); byBoard.get(slug).push(f.id) }
  await parallel([...byBoard].map(([slug, ids]) => () => agent(withPreamble(
    `Accept these agent findings on board ${slug} on the user's standing instruction for this run (auto-accept ${threshold}+ defects): ids ${JSON.stringify(uniq(ids))}.\n` +
    `Door: POST /api/v1/boards/${slug}/annotations/agent-verdict with body {"action":"accept","ids":[...]} — bearer token from $VITRINKA_TOKEN or \`vitrinka auth token\`, fed through stdin as a header file, never inline in argv. Return the response status and the accepted count.`
  ), { label: `accept:${slug}`, phase: ph, effort: 'low' })))

  const { shared, groups } = groupByArea(fixList, 4)
  const fixPrompt = g => withPreamble(
    `Fix these accepted findings open at pass ${pass} of the device test run (area: ${g.area}) in this worktree, on branch ${prep.branch}${prep.baseUrl ? `, app at ${prep.baseUrl}` : ''} — one filed in an earlier pass was skipped there, so try it again:\n${JSON.stringify(g.findings)}\n` +
    `Scope rule: the feature's scope is ${A.scope ? JSON.stringify(A.scope) : 'the branch\'s own changes'}${A.scopeFiles && A.scopeFiles.length ? ` (files ${JSON.stringify(A.scopeFiles)})` : ''}. A finding with inScope false may be fixed ONLY when the whole fix stays within 2 files; otherwise skip it with why "off-scope" — the report stage files it as a bug.\n` +
    `Rules: touch only the files a finding names or the component that owns the defect; other fixers are working other areas in this same checkout right now, so never reformat, rename or move shared code${g.area === 'shared' ? ' (you ARE the shared fixer — the others wait for you)' : ''}. For each finding with an annotation id: \`set_status working\` when you start, fix, then \`reply\` with the commit and \`set_status in_review\`. Commit per area with a message naming the finding keys. A finding you cannot fix without a design decision is skipped with why — never guess a redesign. Return fixed keys, skipped keys, touched routes and files, commits.`
  )
  let fixResults = []
  if (shared) fixResults.push(await agent(fixPrompt(shared), { label: 'fix:shared', phase: ph, schema: FIX_SCHEMA }))
  fixResults.push(...await parallel(groups.map(g => () => agent(fixPrompt(g), { label: `fix:${g.area}`, phase: ph, schema: FIX_SCHEMA }))))
  fixResults = fixResults.filter(Boolean)
  const fixedKeys = new Set(fixResults.flatMap(r => r.fixed))
  const skipped = fixResults.flatMap(r => r.skipped)
  const touchedRoutes = uniq(fixResults.flatMap(r => r.touchedRoutes))
  const touchedFiles = uniq(fixResults.flatMap(r => r.touchedFiles))
  offScopeFindings = fixList.filter(f => !fixedKeys.has(f.key) && skipped.some(s => s.key === f.key && /off-scope/i.test(s.why || '')))
  log(`${ph}: ${fixedKeys.size} fixed, ${skipped.length} skipped (${offScopeFindings.length} off-scope), ${touchedFiles.length} files, ${touchedRoutes.length} routes touched`)

  const gate = await agent(withPreamble(
    `Gate the fixes of pass ${pass}: run the repo's type/build/test gates from CLAUDE.md (the strict TS gate, the Go build, the unit suites; the e2e suite only for the specs covering ${JSON.stringify(touchedRoutes)}) where CLAUDE.md says they run (the run target is ${prep.where}). A failure caused by this pass's commits (${JSON.stringify(fixResults.flatMap(r => r.commits || []))}) you repair in place and commit, then return repaired true and touchedFiles: every file your repair commits changed; a failure that predates them is reported, not fixed.${prep.baseUrl ? ` Restart the app if the fixes need it and confirm ${prep.baseUrl} answers.` : ''}${sims ? ` Keep the dev server serving the native app on ${sims}; rebuild and reinstall it when the fixes changed native code or app config.` : ''} Return green, what ran, and failures.`
  ), { label: 'gate', phase: ph, schema: GATE_SCHEMA })
  // A red gate is a fact of the RUN, not of one pass: a later green gate
  // covers a different e2e subset (touched routes), so it never clears it.
  if (!gate || !gate.green) gateRed = true
  if (!gate || !gate.green) log(`${ph}: gate red — ${JSON.stringify((gate && gate.failures) || ['no result'])}${end === 'last' ? '' : '; the next pass shoots anyway so the board shows the state'}`)

  regressList = fixList.filter(f => fixedKeys.has(f.key))
  unwalked = [...unwalked.filter(f => !fixedKeys.has(f.key)), ...regressList.filter(f => f.rule === 'functional')]
  // The gate's repairs postdate the captures too; unnamed ones reach every route.
  const repairFiles = gateRepairFiles(gate)
  if (!repairFiles || repairFiles.length) log(`${ph}: the gate repaired ${repairFiles ? repairFiles.length + ' files' : 'files it did not name — every route is unverified'}`)
  // A fix with no route whose fixer named nothing it touched is placed nowhere.
  const unplaced = unplacedFixes(fixResults, fixList)
  if (unplaced.length) log(`${ph}: ${unplaced.join(', ')} fixed with no route or file to place the change — every route is unverified`)
  const changed = repairFiles && !unplaced.length ? affectedRoutes(allRoutes, [...regressList.map(f => f.route), ...touchedRoutes], [...touchedFiles, ...repairFiles]) : allRoutes.map(r => r.path)
  for (const route of changed) fixedLog.push({ pass, route })
  for (const k of fixedKeys) carried.delete(k)
  openFindings = [...carried.values()]
  offScopeFindings = openFindings.filter(f => f.inScope === false)
  if (end === 'last') {
    unverified = regressList
    log(`${ph}: cap reached — ${unverified.length} fixed with no reshoot to verify them, ${openFindings.length} findings open — they stay on the board and reach the task engine as bugs`)
    break
  }
  walkOnly = false
  const openRoutes = uniq([...touchedRoutes, ...openFindings.map(f => f.route)])
  routes = allRoutes.filter(r => changed.includes(r.path) || openRoutes.some(p => p && (r.path === p || r.path.startsWith(p))))
  if (!routes.length) routes = allRoutes
  journeys = journeysToRerun(allJourneys, openRoutes, unwalked, ut.cases)
  log(`${ph}: next pass reshoots ${routes.length} routes, reruns ${journeys.length} journeys`)
}

phase('Report')
// A fixed journey no later walk confirmed is as unverified as a last-pass fix.
unverified = [...unverified, ...unwalked.filter(f => !unverified.some(u => u.key === f.key))]
const bugCandidates = uniq([...openFindings, ...offScopeFindings].map(f => f.key)).map(k => [...openFindings, ...offScopeFindings].find(f => f.key === k))
// Every route with no open finding on a lane takes the verdict its coverage
// earned — never a pass for a route that lane did not capture and judge.
const routeCases = Object.fromEntries(lanes.map(l => [l.key, allRoutes
  .filter(r => !bugCandidates.some(f => f.lane === l.key && f.route === r.path))
  .map(r => Object.assign({ route: r.path }, routeVerdict(r.path, l.key, captures, fixedLog)))]))
const skips = Object.values(routeCases).flat().filter(c => c.verdict === 'skip').length
log(`test: report — ${skips} route case(s) earned no pass (never captured, never reviewed or fixed without a reshoot)`)
// The record names the commit every pass fixer and gate repair left behind —
// prep.sha predates them — and readiness compares the branch with this same sha.
const recorded = await agent(withPreamble(
  'Read-only: return head, the full `git rev-parse HEAD` of this checkout. Change nothing.'
), { label: 'record-head', phase: 'Report', effort: 'low', schema: HEAD_SCHEMA })
const recordSha = (recorded && recorded.head) || ''
if (!recordSha) log('test: HEAD could not be read — no record is filed at a commit nobody read')
const report = recordSha ? await agent(withPreamble(
  `File this device test run's record through the run door, ONE runner manifest per lane (the door takes one device per manifest).\n` +
  `Run: task ${task}, branch ${prep.branch}, sha ${recordSha}${A.pr ? `, pr ${A.pr}` : ''}, runner "vitrinka-experimental:test", app ${project || type}. Lanes: ${JSON.stringify(lanes.map(l => ({ key: l.key, label: l.label, kind: l.kind, platform: l.kind === 'ios-safari' ? 'ios' : (l.platform || 'web') })))}. Routes: ${JSON.stringify(allRoutes.map(r => r.path))}.\n` +
  `Per lane write \`.vitrinka/test-run/<lane>.manifest.json\` in the runner-manifest shape ({version: 1, runId, runner, app, branch, sha, pr?, device: {platform, name: "<lane label>", os?}, specs: [{key: "<route path>", title: "<route title>", cases: [...]}]}), its runId and sha exactly as stamped here per lane key: ${JSON.stringify(manifestStamps(board.boardSlug, recordSha, lanes.map(l => l.key)))}; one spec per route; a case per open finding on that route in that lane (title = the finding summary, verdict "fail", error = the finding detail, shots = the finding's card image paths under ${captureRoot('<N>', '<lane>')}, N the pass its key names p<N>-…); every other route takes exactly the ONE case given here per lane — verdict "pass" (shots from ${captureRoot('<pass>', '<lane>')}) or "skip" (error = its why), never a pass this list does not give: ${JSON.stringify(routeCases)}.${Object.keys(problems).length ? ` Shooter problems per lane (quote the line naming a skipped route in its error): ${JSON.stringify(problems)}.` : ''} Open findings (these become bug tasks under the epic through --bugs direct, each with its shot): ${JSON.stringify(bugCandidates.map(f => ({ key: f.key, lane: f.lane, route: f.route, severity: f.severity, summary: f.summary, files: f.files, inScope: f.inScope })))}.\n` +
  `Publish each with \`vitrinka qa run --task ${task} --results .vitrinka/test-run/<lane>.manifest.json --bugs direct --runner vitrinka-experimental:test${project ? ` --app ${project}` : ''} -- true\` (the door is POST /api/v1/tasks/${task}/run with {manifest, bugs: "direct"}). Return the qa task url the door printed, per lane (by its key) whether it published, and every bug task url with its finding key. Commit nothing here.`
), { label: 'run-door', phase: 'Report', schema: RUNDOOR_SCHEMA }) : null
log(`test: run door — ${report ? `${report.lanes.filter(l => l.published).length}/${lanes.length} lanes published, ${report.bugs.length} bugs` : 'failed'}`)

// A fix run's ONE PR-state step (prOutcome): `gh pr ready` or `gh pr ready
// --undo` runs whatever state the PR is in — both are idempotent, so no
// guessed "already a draft" skips the call — with the state read before and
// after. No PR named: the branch's own, when it has one.
const setPrState = (pr, want, why, label) => agent(withPreamble(
  `${pr ? `Pull request ${pr}` : "This branch's open pull request (`gh pr view` with no argument — when it answers there is none, exiting 1 with \"no pull requests found\", that is the answer, not a failed call: return url \"\" and none true and change nothing; any other failure is url \"\" with why, never none)"}: read its url and draft state as url and wasDraft (\`gh pr view${pr ? ` ${pr}` : ''} --json url,isDraft\`), then ` +
  (want === 'ready'
    ? `mark it ready for review (\`gh pr ready <url>\`) — the device run earned it (${passes.length} pass(es), nothing open, every route on every lane passed) and the code loop reviewed the diff.`
    : `convert it to a draft (\`gh pr ready <url> --undo\`; a draft stays one) — this device run did not earn ready for review: ${why.join('; ')}.`) +
  ` Never merge or close it. Read isDraft back after the call. Return url, wasDraft and isDraft — leave out a state you could not read, never guess one — plus why when a call failed.`
), { label, phase: 'Report', effort: 'low', schema: PR_STATE_SCHEMA })

// The PR leaves draft only when the run actually earned it: every pass gated
// green, no finding left open, every route on every lane earned a pass, the
// run door filed the record, and the code loop reviewed the diff without
// moving the branch past the record (its commits postdate every capture).
// Anything less ends a draft — a PR ready for review goes back to draft — and
// the hand-back says why. Nothing is earned before the code loop — a failing
// record already fails the run, and a clean one still awaits the code
// review — so every fix run returns the PR to draft NOW, before code-loop's
// prm pushes to a PR that could merge on that push; a draft it cannot prove,
// or a branch PR it cannot prove absent, holds that push (codeLoopPushHold).
const laneKeys = lanes.map(l => l.key)
const recordWhy = recordReasons({ fixes, open: openFindings, lanes: laneKeys, report, gateRed, routeCases, unwalked })
const earlyWhy = recordWhy.length ? recordWhy : ['the code loop has not reviewed the diff yet']
const early = fixes ? await setPrState(A.pr || '', 'draft', earlyWhy, 'pr-draft:early') : null
const earlyOut = early && early.url ? prOutcome('draft', early) : null
if (earlyOut) log(`test: ${recordWhy.length ? 'the device record fails the run' : 'the device record is clean, the code review is still ahead'} — ${early.url} ${earlyOut.draft ? `is a draft${earlyOut.demoted ? ' again' : ''}` : `could stay ready (${earlyOut.problem})`} before the code loop`)
// No fix run pushes where it could not prove the PR a draft or absent.
const pushHold = fixes ? codeLoopPushHold(early, A.pr || '') : ''
if (pushHold) log(`test: the code loop runs without its PR phase — ${pushHold}; its commits stay local`)

let code = null
if (fixes) {
  try {
    // A PR the loop opens is a draft; one it adopts keeps its state — the
    // step below readies or demotes either to the state this run earned.
    code = await workflow('vitrinka:code-loop', { base: A.base || 'main', task, cap: 2, draft: true, pr: !pushHold })
    log(`test: code loop ${code.rounds.length} round(s), ${code.remaining.length} for the human, PR ${code.pr || A.pr || 'none'}`)
  } catch (e) {
    log(`test: code loop failed (${e && e.message}) — the PR ends a draft`)
  }
}
// Whatever the code loop committed or prm pushed moved the head past the
// record. A code loop that threw or opened nothing names no PR; the branch's
// own is found here.
const knownPr = (code && code.pr) || A.pr || (early && early.url) || ''
const heads = fixes ? await agent(withPreamble(
  `Read-only: return head, the full \`git rev-parse HEAD\` of this checkout, and from ${knownPr ? `pull request ${knownPr}` : "this branch's open pull request (`gh pr view` with no argument)"} its url and prHead, its head commit (\`gh pr view${knownPr ? ` ${knownPr}` : ''} --json url,headRefOid\`) — url and prHead "" when there is none. Change nothing.`
), { label: 'heads', phase: 'Report', effort: 'low', schema: HEADS_SCHEMA }) : null
const prUrl = knownPr || (heads && heads.url) || ''
const notReady = notReadyReasons({ fixes, open: openFindings, lanes: laneKeys, report, code, gateRed, routeCases, recordSha, heads, unwalked })
const want = notReady.length ? 'draft' : 'ready'
// The step runs after the loop even when the record already forced a draft:
// prm and anyone else may have moved the PR since, so the early read-back
// proves only the order, never the state the run ends in.
const prOut = !fixes || !prUrl ? { ready: false, draft: false, demoted: false, problem: '' }
  : prOutcome(want, await setPrState(prUrl, want, notReady, `pr-${want}`))
const ready = prOut.ready
const demoted = prOut.demoted || !!(earlyOut && earlyOut.demoted && prOut.draft)
const prProblem = prOut.problem
const converged = convergedAfter({ clean, open: openFindings, unwalked, gateRed })

const handback = await agent(withPreamble(
  `Hand task ${task} back through the vitrinka handoff skill (Skill tool: vitrinka:handoff). Facts, one per line, for the summary:\n` +
  JSON.stringify({
    runBoard: board.boardUrl,
    lanes: board.lanes,
    thoroughness, cap, threshold,
    passes,
    converged,
    open: openFindings.map(f => ({ key: f.key, lane: f.lane, summary: f.summary })),
    unverified: unverified.map(f => ({ key: f.key, lane: f.lane, summary: f.summary })),
    qaTask: report && report.qaTaskUrl,
    bugs: report && report.bugs,
    codeLoop: code ? { rounds: code.rounds, remaining: code.remaining.length, ...(pushHold ? { unposted: code.remaining } : {}) } : null,
    pr: prUrl, ready, notReady, demoted, prProblem, pushHeld: pushHold,
  }) +
  `\nThe run board url goes first, bare on its own line.${demoted ? ' The PR was returned to draft: say so, with the notReady reasons.' : ''}${fixes && !recordWhy.length && notReady.length ? ' The device record itself was clean: say the PR stays a draft only because of the code loop (notReady), not a device defect.' : ''}${prProblem ? ' The PR is not in the state the run earned (prProblem): say so.' : ''}${pushHold ? ' The code loop pushed nothing (pushHeld): the PR could not be proven a draft (or absent) before the code loop, so its commits are local only and its remaining findings (codeLoop.unposted) reached no PR comment — say so, and carry those findings in full.' : ''} Open findings are already bugs on the qa task — never spot them as children. Next steps hold only what is the human's: ${ready ? 'the merge' : !fixes ? `the PR, which a ${thoroughness} run leaves as it was` : prUrl ? 'marking the PR ready and the merge' : 'opening or readying the PR'}${pushHold ? ", pushing the code loop's local commits once the PR is a draft" : ''}${openFindings.length ? ', the open findings on the lane boards' : ''}. Return the rendered hand-back block verbatim.`
), { label: 'handback', phase: 'Report' })

return {
  boardUrl: board.boardUrl,
  lanes: board.lanes,
  branch: prep.branch,
  task,
  passes,
  converged,
  open: openFindings.map(f => ({ key: f.key, id: f.id, lane: f.lane, summary: f.summary })),
  unverified: unverified.map(f => ({ key: f.key, id: f.id, lane: f.lane, summary: f.summary })),
  qaTask: report && report.qaTaskUrl,
  bugs: report ? report.bugs : [],
  pr: prUrl,
  ready,
  demoted,
  handback,
}
