export const meta = {
  name: 'build-idea',
  description: 'From a committed feature brief to an opened PR: plan, implement in slices, review-loop the UI, code-loop the diff, hand the task back',
  whenToUse: 'Launched by the make-idea skill once the brainstorm has settled and the brief is committed; runs unattended until the PR is open and the task is handed back — the human merges.',
  phases: [
    { title: 'Plan', detail: 'the brief into ≤4 disjoint implementation slices' },
    { title: 'Implement', detail: 'one agent per slice, same worktree, then the gates' },
    { title: 'Verify', detail: 'map the app, then the review loop' },
    { title: 'Ship', detail: 'the code loop, the PR, the hand-back' },
  ],
}
// Code generated by tools/gen-workflows from workflows-src/flows/build-idea.js. DO NOT EDIT.
// Edit the flow or its lib/ fragments under workflows-src/, then `go run ./tools/gen-workflows`.
// ---- lib/preamble.js — the lines every agent prompt starts with
// Agents already carry the repo's CLAUDE.md; these name only what a
// workflow stage needs beyond it. Keep it to contracts, never procedure —
// procedure is served by the vitrinka server (`docs {topic}`) and the CLI's
// `--help`.
const PREAMBLE = [
  'You are one stage of a vitrinka workflow. Your final text IS the return value: return raw data for the schema, never a human-facing report.',
  'Work in the current checkout (a worktree). Never switch branches, never stash, never touch the main checkout.',
  'Apps and test suites run where the repo\'s CLAUDE.md says — a worktree\'s devbox when one exists (`devbox run -- \'<cmd>\'`), otherwise locally; say which in `problems` when you had to fall back.',
  'Every vitrinka board/task link you return is the server-returned `url`, verbatim — never composed, never shortened.',
  'Browser work: onyx `browser_start(session: $CLAUDE_CODE_SESSION_ID)` first, headless, then playwright; screenshots land in `.vitrinka/mcp/` or the capture root you were given, never the repo root.',
  'When a door refuses (4xx with a diagnosis), apply the corrected call it names once; a second refusal is a `problems` entry, not a workaround.',
].join('\n')

function withPreamble(prompt) {
  return PREAMBLE + '\n\n' + prompt
}
// ---- lib/schemas.js — structured-output schemas shared by the flows
const ROUTE = {
  type: 'object',
  properties: {
    path: { type: 'string' },
    title: { type: 'string' },
    file: { type: 'string', description: 'repo-relative implementing file' },
    auth: { type: 'string', description: 'none | user | admin | <role>' },
    setup: { type: 'string', description: 'how to reach it with data on screen (seed, fixture, deep link)' },
  },
  required: ['path', 'title'],
}

const TERRAIN_SCHEMA = {
  type: 'object',
  properties: {
    projectType: { type: 'string', enum: ['web', 'expo', 'cli', 'other'] },
    routes: { type: 'array', items: ROUTE },
    journeys: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          steps: { type: 'array', items: { type: 'string' } },
          roles: { type: 'array', items: { type: 'string' } },
        },
        required: ['title', 'steps'],
      },
    },
    extendPoints: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, file: { type: 'string' }, why: { type: 'string' } }, required: ['what', 'file'] } },
    duplicationRisks: { type: 'array', items: { type: 'object', properties: { risk: { type: 'string' }, existing: { type: 'string' } }, required: ['risk', 'existing'] } },
    openQuestions: { type: 'array', items: { type: 'string' } },
    terrainUrl: { type: 'string', description: 'server-returned url of the pushed terrain artifact, empty when not pushed' },
    boardUrl: { type: 'string' },
  },
  required: ['projectType', 'routes'],
}

const FINDING = {
  type: 'object',
  properties: {
    key: { type: 'string' },
    id: { type: 'integer', description: 'annotation id from the annotate receipt' },
    cardId: { type: 'integer' },
    route: { type: 'string' },
    device: { type: 'string' },
    area: { type: 'string', description: 'route, component or subsystem the fix lives in' },
    kind: { type: 'string', enum: ['finding', 'suggestion'] },
    severity: { type: 'string', enum: ['blocker', 'major', 'minor'] },
    rule: { type: 'string' },
    summary: { type: 'string' },
    files: { type: 'array', items: { type: 'string' } },
  },
  required: ['key', 'area', 'kind', 'severity', 'summary'],
}

const FINDINGS_SCHEMA = {
  type: 'object',
  properties: {
    findings: { type: 'array', items: FINDING },
    regressions: { type: 'array', items: { type: 'object', properties: { id: { type: 'integer' }, key: { type: 'string' }, fixed: { type: 'boolean' }, note: { type: 'string' } }, required: ['key', 'fixed'] } },
    screensRead: { type: 'integer' },
    boardUrl: { type: 'string' },
  },
  required: ['findings'],
}

const SHOOT_SCHEMA = {
  type: 'object',
  properties: {
    device: { type: 'string' },
    shots: { type: 'array', items: { type: 'object', properties: { route: { type: 'string' }, label: { type: 'string' }, file: { type: 'string' } }, required: ['route', 'label'] } },
    boardUrl: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['device', 'shots'],
}

const USERTEST_SCHEMA = {
  type: 'object',
  properties: {
    qaTaskUrl: { type: 'string' },
    boardUrl: { type: 'string' },
    cases: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, device: { type: 'string' }, verdict: { type: 'string', enum: ['pass', 'fail', 'skip'] }, note: { type: 'string' }, files: { type: 'array', items: { type: 'string' } } }, required: ['title', 'verdict'] } },
    bugs: { type: 'array', items: { type: 'string', description: 'task url of each bug filed' } },
  },
  required: ['cases'],
}

const FIX_SCHEMA = {
  type: 'object',
  properties: {
    fixed: { type: 'array', items: { type: 'string', description: 'finding key' } },
    skipped: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, why: { type: 'string' } }, required: ['key', 'why'] } },
    touchedRoutes: { type: 'array', items: { type: 'string' } },
    touchedFiles: { type: 'array', items: { type: 'string' } },
    commits: { type: 'array', items: { type: 'string' } },
  },
  required: ['fixed', 'skipped', 'touchedRoutes', 'touchedFiles'],
}

const GATE_SCHEMA = {
  type: 'object',
  properties: {
    green: { type: 'boolean' },
    ran: { type: 'array', items: { type: 'string' } },
    failures: { type: 'array', items: { type: 'string' } },
    repaired: { type: 'boolean' },
  },
  required: ['green', 'ran'],
}

const PREPARE_SCHEMA = {
  type: 'object',
  properties: {
    baseUrl: { type: 'string' },
    where: { type: 'string', enum: ['devbox', 'local'] },
    branch: { type: 'string' },
    project: { type: 'string' },
    task: { type: 'string', description: 'vitrinka task id the run is bound to' },
    override: { type: 'object', description: 'parsed .claude/vitrinka-workflows.json or {}' },
    projectType: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['baseUrl', 'where', 'branch', 'projectType'],
}

const PUBLISH_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    section: { type: 'string' },
    cards: { type: 'array', items: { type: 'object', properties: { cardId: { type: 'integer' }, route: { type: 'string' }, device: { type: 'string' }, label: { type: 'string' } }, required: ['cardId'] } },
  },
  required: ['boardUrl', 'boardSlug', 'section', 'cards'],
}
// args: { brief: string (repo-relative path), task: string, project?: string, cap?: 3, severity?: 'minor', matrix?, base?: 'main' }
const A = args || {}
if (!A.brief) throw new Error('build-idea: args.brief (the committed brief\'s repo-relative path) is required')
if (!A.task) throw new Error('build-idea: args.task (the epic or story the brief belongs to) is required')

const PLAN_SCHEMA = {
  type: 'object',
  properties: {
    slices: {
      type: 'array',
      maxItems: 4,
      items: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          goal: { type: 'string' },
          files: { type: 'array', items: { type: 'string' }, description: 'files this slice owns; disjoint from every other slice' },
          dependsOn: { type: 'array', items: { type: 'string' } },
          acceptance: { type: 'array', items: { type: 'string' } },
          tests: { type: 'array', items: { type: 'string' }, description: 'tests to write or extend, in the repo\'s own framework' },
        },
        required: ['name', 'goal', 'files', 'acceptance'],
      },
    },
    shared: { type: 'object', properties: { goal: { type: 'string' }, files: { type: 'array', items: { type: 'string' } } }, description: 'schema, types, shared components every slice needs — built first, empty when none' },
    scope: { type: 'string', description: 'one paragraph: what the review loop should test' },
    routes: { type: 'array', items: { type: 'string' }, description: 'routes the feature adds or changes' },
  },
  required: ['slices', 'scope'],
}

const IMPL_SCHEMA = {
  type: 'object',
  properties: {
    slice: { type: 'string' },
    done: { type: 'array', items: { type: 'string' } },
    left: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, why: { type: 'string' } }, required: ['what', 'why'] } },
    files: { type: 'array', items: { type: 'string' } },
    commits: { type: 'array', items: { type: 'string' } },
  },
  required: ['slice', 'done', 'left', 'files'],
}

phase('Plan')
const plan = await agent(withPreamble(
  `Read the feature brief at ${A.brief} (and the terrain artifact it links, if any). Plan its implementation for THIS repo as at most 4 slices that can be built in parallel in one worktree: each slice owns a disjoint set of files; anything two slices need (schema/migration, types, a shared component, a door) goes into \`shared\`, built first. Every slice lists its acceptance criteria as observable behaviour and the tests it writes in the repo's own framework. Honour the repo's laws (CLAUDE.md, the project memory files whose triggers match) — a plan that fights a law is wrong. Also return the routes the feature adds or changes and one paragraph of what the review loop should test. Read-only: change nothing.`
), { label: 'plan', phase: 'Plan', schema: PLAN_SCHEMA })
if (!plan || !plan.slices.length) throw new Error('build-idea: planning produced no slices')
log(`build-idea: ${plan.slices.length} slices${plan.shared && plan.shared.files && plan.shared.files.length ? ' + shared' : ''}`)

phase('Implement')
const implPrompt = (s, isShared) => withPreamble(
  `Implement ${isShared ? 'the SHARED foundation' : `slice "${s.name}"`} of the feature in ${A.brief} (task ${A.task}), in this worktree.\n` +
  `Goal: ${s.goal}\nFiles you own: ${JSON.stringify(s.files)}\n${s.acceptance ? `Acceptance: ${JSON.stringify(s.acceptance)}\n` : ''}${s.tests ? `Tests to write/extend: ${JSON.stringify(s.tests)}\n` : ''}` +
  (isShared ? 'Other slices build on what you leave; keep it minimal and typed.' : 'Other slices are being built in this same checkout right now: never edit files outside your list, never reformat shared code; a need outside your files is a `left` item with why.') +
  ` Commit per coherent unit with a trailer naming the task. Return what is done, what is left and why, files and commits.`
)
const impl = []
if (plan.shared && plan.shared.files && plan.shared.files.length) {
  impl.push(await agent(implPrompt(plan.shared, true), { label: 'implement:shared', phase: 'Implement', schema: IMPL_SCHEMA }))
}
impl.push(...await parallel(plan.slices.map(s => () => agent(implPrompt(s, false), { label: `implement:${s.name}`, phase: 'Implement', schema: IMPL_SCHEMA }))))
const built = impl.filter(Boolean)
const left = built.flatMap(r => r.left.map(l => ({ slice: r.slice, ...l })))
log(`build-idea: ${built.length} slices built, ${left.length} items left`)

if (left.length) {
  const sweep = await agent(withPreamble(
    `Finish what the slice builders left in this worktree (feature ${A.brief}, task ${A.task}): ${JSON.stringify(left)}. Everything is yours now — no other agent edits this checkout. An item that needs a product decision is left with why. Commit. Return done/left/files/commits.`
  ), { label: 'implement:sweep', phase: 'Implement', schema: IMPL_SCHEMA })
  if (sweep) built.push(sweep)
}

const gate = await agent(withPreamble(
  `Gate the implementation: run every type/build/test gate CLAUDE.md names, where it says they run, plus the tests the slices wrote. Repair and commit what this branch broke; report what predates it. Return green, what ran, failures.`
), { label: 'gate', phase: 'Implement', schema: GATE_SCHEMA })
if (!gate || !gate.green) log(`build-idea: implementation gate red — ${JSON.stringify((gate && gate.failures) || ['no result'])}; continuing so the board shows the state`)

phase('Verify')
let terrain = null
try {
  terrain = await workflow('vitrinka:map', { scope: 'app', project: A.project, task: A.task, push: false })
} catch (e) {
  log(`build-idea: map workflow unavailable (${e && e.message}); the review loop inventories inline`)
}
let loop = { boardUrl: '', passes: [], converged: false, open: [], error: '' }
try {
  loop = await workflow('vitrinka:review-loop', {
    routes: terrain ? terrain.routes : undefined,
    journeys: terrain ? terrain.journeys : undefined,
    projectType: terrain ? terrain.projectType : undefined,
    task: A.task, project: A.project, cap: A.cap || 3, severity: A.severity || 'minor', matrix: A.matrix, scope: plan.scope,
  })
  log(`build-idea: review loop ${loop.converged ? 'converged' : `stopped with ${loop.open.length} open`} after ${loop.passes.length} pass(es) → ${loop.boardUrl}`)
} catch (e) {
  loop.error = (e && e.message) || String(e)
  log(`build-idea: review loop failed (${loop.error}) — the UI is UNVERIFIED; continuing to the code loop so the hand-back says so`)
}

phase('Ship')
const code = await workflow('vitrinka:code-loop', { base: A.base || 'main', task: A.task, cap: 2 })
log(`build-idea: code loop ${code.rounds.length} round(s), ${code.remaining.length} for the human, PR ${code.pr || 'not opened'}`)

const handback = await agent(withPreamble(
  `Hand task ${A.task} back through the vitrinka handoff skill (Skill tool: vitrinka:handoff). Facts, one per line, for the summary:\n` +
  JSON.stringify({
    brief: A.brief,
    slices: built.map(b => ({ slice: b.slice, done: b.done.length, left: b.left.length })),
    implementationGate: gate && gate.green,
    reviewLoop: { board: loop.boardUrl, passes: loop.passes, converged: loop.converged, open: loop.open, error: loop.error },
    codeLoop: { rounds: code.rounds, remaining: code.remaining.length },
    pr: code.pr,
  }) +
  `\nOpen items (${loop.open.length + code.remaining.length}) become spotted children, not prose. Next steps hold only what is the human's: the merge${loop.open.length ? ', the open findings on the board' : ''}. Return the rendered hand-back block verbatim.`
), { label: 'handback', phase: 'Ship' })

return { plan: plan.slices.map(s => s.name), gate: gate && gate.green, board: loop.boardUrl, converged: loop.converged, pr: code.pr, handback }
