export const meta = {
  name: 'build-idea',
  description: 'From a committed feature brief to an opened PR: plan, implement in slices, review-loop the UI, code-loop the diff, hand the task back',
  whenToUse: 'Launched by the make-idea skill once the brainstorm has settled and the brief is committed; runs unattended until the PR is open and the task is handed back — the human merges.',
  phases: [
    { title: 'Plan', detail: 'the brief into ≤4 disjoint implementation slices' },
    { title: 'Foundation', detail: 'shared types and contracts before their consumers' },
    { title: 'Implement', detail: 'up to four sequential slice writers in one worktree' },
    { title: 'Finish', detail: 'resolve implementation leftovers' },
    { title: 'Gate', detail: 'verify implementation before the UI pass' },
    { title: 'Verify', detail: 'map the app, then the review loop' },
    { title: 'Ship', detail: 'the code loop, the PR, the hand-back' },
  ],
}
// Code generated by tools/gen-workflows from workflows-src/flows/build-idea.js. DO NOT EDIT.
// Edit the flow or its lib/ fragments under workflows-src/, then `go run ./tools/gen-workflows`.
// ---- lib/preamble.js — the lines every agent prompt starts with
// Agents already carry the repo's CLAUDE.md; these name only what a
// workflow stage needs beyond it. Keep it to contracts, never procedure —
// procedure is served by the vitrinka server (`docs {topic}`) and the CLI's
// `--help`.
const PREAMBLE = [
  'You are one stage of a vitrinka workflow. Your final text IS the return value: return raw data for the schema, never a human-facing report.',
  'Work in the current checkout (a worktree). Never switch branches, never stash, never touch the main checkout.',
  'Apps and test suites run where the repo\'s CLAUDE.md says — a worktree\'s devbox when one exists (`devbox run -- \'<cmd>\'`), otherwise locally; say which in `problems` when you had to fall back.',
  'Every vitrinka board/task link you return is the server-returned `url`, verbatim — never composed, never shortened.',
  'Browser work: onyx `browser_start(session: $CLAUDE_CODE_SESSION_ID)` first, headless, then playwright; screenshots land in `.vitrinka/mcp/` or the capture root you were given, never the repo root.',
  'When a door refuses (4xx with a diagnosis), apply the corrected call it names once; a second refusal is a `problems` entry, not a workaround.',
].join('\n')

function withPreamble(prompt) {
  return PREAMBLE + '\n\n' + prompt
}
// The runtime journals agent returns. Keep accounting deterministic on replay,
// share the allowance with child workflows, and bound every fan-out to four.
function workflowRun(input = {}, callAgent = agent, callWorkflow = typeof workflow === 'function' ? workflow : null) {
  const supplied = input.agentBudget || { limit: 10, used: 0 }
  const limit = supplied.limit
  let used = supplied.used
  if (!Number.isInteger(limit) || limit < 1 || limit > 10 || !Number.isInteger(used) || used < 0 || used > limit) {
    throw new Error('workflow: agentBudget must have integer limit 1..10 and used 0..limit')
  }
  const remaining = () => limit - used
  const reserve = n => {
    if (n > remaining()) throw new Error(`workflow: agent budget exhausted (${used}/${limit}); continue with the returned next args as a new run`)
  }
  return {
    remaining,
    ensureBudget: reserve,
    async agent(prompt, options) {
      reserve(1)
      used++
      return await callAgent(prompt, options)
    },
    async workflow(name, args) {
      if (!callWorkflow) throw new Error('workflow: no child-workflow runtime is available')
      const result = await callWorkflow(name, Object.assign({}, args, { agentBudget: { limit, used } }))
      if (!result || !result.agentBudget || result.agentBudget.limit !== limit || !Number.isInteger(result.agentBudget.used) || result.agentBudget.used < used || result.agentBudget.used > limit) {
        throw new Error(`workflow: ${name} returned no valid shared agent-budget receipt`)
      }
      used = result.agentBudget.used
      return result
    },
    async parallel(tasks) {
      reserve(tasks.length)
      const results = []
      for (let i = 0; i < tasks.length; i += 4) results.push(...await parallel(tasks.slice(i, i + 4)))
      return results
    },
    async serial(tasks) {
      reserve(tasks.length)
      const results = []
      for (const task of tasks) results.push(await task())
      return results
    },
    finish(result) { return Object.assign({}, result, { agentBudget: { limit, used } }) },
  }
}

function completionReceipt({ complete = false, problems = [], open = [], unverified = [], evidence = [] } = {}) {
  const blockers = [...problems, ...open.map(x => x.summary || x.title || String(x)), ...unverified.map(x => x.summary || x.title || String(x))]
  const status = complete && !blockers.length && evidence.length ? 'complete' : 'incomplete'
  if (status === 'incomplete' && !blockers.length) blockers.push('stage is unfinished or lacks verification evidence')
  return { v: 1, status, evidence, blockers }
}

function gatePassed(gate) {
  return !!(gate && gate.green && gate.headSha && gate.ran && gate.ran.length && Number.isInteger(gate.testsExecuted) && gate.testsExecuted > 0 && !(gate.failures || []).length)
}

function coverageProblems(routes, matrix, shots, journeys, cases, reviews, walkOnly, cards = []) {
  const problems = []
  if (!walkOnly) {
    for (const device of matrix) for (const route of routes) {
      if (!shots.some(s => s.device === device.name && s.shots.some(x => x.route === route.path))) problems.push(`missing capture: ${device.name} ${route.path}`)
      if (!cards.some(c => c.device === device.name && c.route === route.path)) problems.push(`missing published capture: ${device.name} ${route.path}`)
    }
    const read = new Set(reviews.flatMap(r => r.cardsRead || []))
    if (!cards.length || cards.some(c => !read.has(c.cardId))) problems.push('the reviewer did not read every published card')
  }
  for (const device of matrix) for (const journey of journeys) {
    if (!cases.some(c => c.title === journey.title && c.device === device.name && ['pass', 'fail'].includes(c.verdict))) problems.push(`journey not executed: ${device.name} ${journey.title}`)
  }
  return problems
}
// ---- lib/schemas.js — structured-output schemas shared by the flows
const ROUTE = {
  type: 'object',
  properties: {
    path: { type: 'string' },
    title: { type: 'string' },
    file: { type: 'string', description: 'repo-relative implementing file' },
    auth: { type: 'string', description: 'none | user | admin | <role>' },
    setup: { type: 'string', description: 'how to reach it with data on screen (seed, fixture, deep link)' },
  },
  required: ['path', 'title'],
}

const TERRAIN_SCHEMA = {
  type: 'object',
  properties: {
    projectType: { type: 'string', enum: ['web', 'expo', 'cli', 'other'] },
    routes: { type: 'array', items: ROUTE },
    journeys: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          steps: { type: 'array', items: { type: 'string' } },
          roles: { type: 'array', items: { type: 'string' } },
        },
        required: ['title', 'steps'],
      },
    },
    extendPoints: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, file: { type: 'string' }, why: { type: 'string' } }, required: ['what', 'file'] } },
    duplicationRisks: { type: 'array', items: { type: 'object', properties: { risk: { type: 'string' }, existing: { type: 'string' } }, required: ['risk', 'existing'] } },
    openQuestions: { type: 'array', items: { type: 'string' } },
    terrainUrl: { type: 'string', description: 'server-returned url of the pushed terrain artifact, empty when not pushed' },
    boardUrl: { type: 'string' },
  },
  required: ['projectType', 'routes'],
}

const FINDING = {
  type: 'object',
  properties: {
    key: { type: 'string' },
    id: { type: 'integer', description: 'annotation id from the annotate receipt' },
    cardId: { type: 'integer' },
    route: { type: 'string' },
    device: { type: 'string' },
    area: { type: 'string', description: 'route, component or subsystem the fix lives in' },
    kind: { type: 'string', enum: ['finding', 'suggestion'] },
    severity: { type: 'string', enum: ['blocker', 'major', 'minor'] },
    rule: { type: 'string' },
    summary: { type: 'string' },
    files: { type: 'array', items: { type: 'string' } },
  },
  required: ['key', 'area', 'kind', 'severity', 'summary'],
}

const FINDINGS_SCHEMA = {
  type: 'object',
  properties: {
    findings: { type: 'array', items: FINDING },
    regressions: { type: 'array', items: { type: 'object', properties: { id: { type: 'integer' }, key: { type: 'string' }, fixed: { type: 'boolean' }, note: { type: 'string' } }, required: ['key', 'fixed'] } },
    screensRead: { type: 'integer' },
    cardsRead: { type: 'array', items: { type: 'integer' }, description: 'every cardId whose pixels were read' },
    boardUrl: { type: 'string' },
  },
  required: ['findings', 'cardsRead'],
}

const SHOOT_SCHEMA = {
  type: 'object',
  properties: {
    device: { type: 'string' },
    shots: { type: 'array', items: { type: 'object', properties: { route: { type: 'string' }, label: { type: 'string' }, file: { type: 'string' } }, required: ['route', 'label'] } },
    boardUrl: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['device', 'shots'],
}

const USERTEST_SCHEMA = {
  type: 'object',
  properties: {
    qaTaskUrl: { type: 'string' },
    boardUrl: { type: 'string' },
    cases: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, device: { type: 'string' }, verdict: { type: 'string', enum: ['pass', 'fail', 'skip'] }, note: { type: 'string' }, files: { type: 'array', items: { type: 'string' } } }, required: ['title', 'device', 'verdict'] } },
    bugs: { type: 'array', items: { type: 'string', description: 'task url of each bug filed' } },
  },
  required: ['cases'],
}

const FIX_SCHEMA = {
  type: 'object',
  properties: {
    fixed: { type: 'array', items: { type: 'string', description: 'finding key' } },
    skipped: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, why: { type: 'string' } }, required: ['key', 'why'] } },
    touchedRoutes: { type: 'array', items: { type: 'string' } },
    touchedFiles: { type: 'array', items: { type: 'string' } },
    commits: { type: 'array', items: { type: 'string' } },
  },
  required: ['fixed', 'skipped', 'touchedRoutes', 'touchedFiles'],
}

const GATE_SCHEMA = {
  type: 'object',
  properties: {
    green: { type: 'boolean' },
    ran: { type: 'array', items: { type: 'string' } },
    failures: { type: 'array', items: { type: 'string' } },
    repaired: { type: 'boolean' },
    testsExecuted: { type: 'integer', minimum: 0, description: 'sum of tests actually executed, read from runner output; never inferred from a success banner' },
    headSha: { type: 'string', description: 'git rev-parse HEAD after every repair and verification' },
  },
  required: ['green', 'ran', 'headSha', 'testsExecuted'],
}

const PREPARE_SCHEMA = {
  type: 'object',
  properties: {
    baseUrl: { type: 'string' },
    where: { type: 'string', enum: ['devbox', 'local'] },
    branch: { type: 'string' },
    headSha: { type: 'string' },
    project: { type: 'string' },
    task: { type: 'string', description: 'vitrinka task id the run is bound to' },
    override: { type: 'object', description: 'parsed .claude/vitrinka-workflows.json or {}' },
    projectType: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['baseUrl', 'where', 'branch', 'headSha', 'projectType'],
}

const PUBLISH_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    section: { type: 'string' },
    cards: { type: 'array', items: { type: 'object', properties: { cardId: { type: 'integer' }, route: { type: 'string' }, device: { type: 'string' }, label: { type: 'string' } }, required: ['cardId', 'route', 'device'] } },
  },
  required: ['boardUrl', 'boardSlug', 'section', 'cards'],
}
// args: { brief: string (repo-relative path), task: string, project?: string, cap?: 3, severity?: 'minor', matrix?, base?: 'main' }
const A = args || {}
const run = workflowRun(A)
const stage = A.stage || 'implement'
if (!['implement', 'verify', 'ship'].includes(stage)) throw new Error('build-idea: stage must be implement | verify | ship')
const state = A.state || {}
const nextStage = (next, data) => run.finish({ stage, receipt: completionReceipt(), next: { name: 'vitrinka:build-idea', args: Object.assign({}, A, { stage: next, state: Object.assign({}, data, { brief: A.brief, task: A.task }), agentBudget: undefined }) } })
if (!A.brief) throw new Error('build-idea: args.brief (the committed brief\'s repo-relative path) is required')
if (!A.task) throw new Error('build-idea: args.task (the epic or story the brief belongs to) is required')

const PLAN_SCHEMA = {
  type: 'object',
  properties: {
    slices: {
      type: 'array',
      maxItems: 4,
      items: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          goal: { type: 'string' },
          files: { type: 'array', items: { type: 'string' }, description: 'files this slice owns; disjoint from every other slice' },
          dependsOn: { type: 'array', items: { type: 'string' } },
          acceptance: { type: 'array', items: { type: 'string' } },
          tests: { type: 'array', items: { type: 'string' }, description: 'tests to write or extend, in the repo\'s own framework' },
        },
        required: ['name', 'goal', 'files', 'acceptance'],
      },
    },
    shared: { type: 'object', properties: { goal: { type: 'string' }, files: { type: 'array', items: { type: 'string' } } }, description: 'schema, types, shared components every slice needs — built first, empty when none' },
    scope: { type: 'string', description: 'one paragraph: what the review loop should test' },
    routes: { type: 'array', items: { type: 'string' }, description: 'routes the feature adds or changes' },
  },
  required: ['slices', 'scope'],
}

const IMPL_SCHEMA = {
  type: 'object',
  properties: {
    slice: { type: 'string' },
    done: { type: 'array', items: { type: 'string' } },
    left: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, why: { type: 'string' } }, required: ['what', 'why'] } },
    files: { type: 'array', items: { type: 'string' } },
    commits: { type: 'array', items: { type: 'string' } },
  },
  required: ['slice', 'done', 'left', 'files'],
}

let plan = state.plan
let built = state.built || []
let gate = state.gate
let loop = state.loop
let implementationLeft = state.implementationLeft || []
if (stage !== 'implement' && (state.brief !== A.brief || state.task !== A.task)) throw new Error('build-idea: continuation belongs to a different brief or task')
if (stage === 'implement') {
run.ensureBudget(8) // plan + shared + four slices + sweep + gate
phase('Plan')
plan = await run.agent(withPreamble(
  `Read the feature brief at ${A.brief} (and the terrain artifact it links, if any). Plan its implementation for THIS repo as at most 4 slices ordered so dependencies precede consumers, built sequentially in one worktree: each slice owns a disjoint set of files; anything two slices need (schema/migration, types, a shared component, a door) goes into \`shared\`, built first. Every slice lists its acceptance criteria as observable behaviour and the tests it writes in the repo's own framework. Honour the repo's laws (CLAUDE.md, the project memory files whose triggers match) — a plan that fights a law is wrong. Also return the routes the feature adds or changes and one paragraph of what the review loop should test. Read-only: change nothing.`
), { label: 'plan', phase: 'Plan', schema: PLAN_SCHEMA })
if (!plan || !plan.slices.length) throw new Error('build-idea: planning produced no slices')
log(`build-idea: ${plan.slices.length} slices${plan.shared && plan.shared.files && plan.shared.files.length ? ' + shared' : ''}`)

const implPrompt = (s, isShared) => withPreamble(
  `Implement ${isShared ? 'the SHARED foundation' : `slice "${s.name}"`} of the feature in ${A.brief} (task ${A.task}), in this worktree.\n` +
  `Goal: ${s.goal}\nFiles you own: ${JSON.stringify(s.files)}\n${s.acceptance ? `Acceptance: ${JSON.stringify(s.acceptance)}\n` : ''}${s.tests ? `Tests to write/extend: ${JSON.stringify(s.tests)}\n` : ''}` +
  (isShared ? 'Other slices build on what you leave; keep it minimal and typed.' : 'Slices run sequentially: you are the ONLY writer and committer in this checkout. Never revert earlier slices, never edit files outside your list; a need outside your files is a `left` item with why.') +
  ` Commit per coherent unit with a trailer naming the task. Return what is done, what is left and why, files and commits.`
)
const impl = []
if (plan.shared && plan.shared.files && plan.shared.files.length) {
  phase('Foundation')
  const shared = await run.agent(implPrompt(plan.shared, true), { label: 'implement:shared', phase: 'Foundation', schema: IMPL_SCHEMA })
  if (!shared) throw new Error('build-idea: shared foundation failed; resume before building its consumers')
  impl.push(shared)
}
phase('Implement')
impl.push(...await run.serial(plan.slices.map(s => () => run.agent(implPrompt(s, false), { label: `implement:${s.name}`, phase: 'Implement', schema: IMPL_SCHEMA }))))
built = impl.filter(Boolean)
if (built.length !== plan.slices.length + (plan.shared && plan.shared.files && plan.shared.files.length ? 1 : 0)) throw new Error('build-idea: a builder failed; resume the same run before verification')
const left = built.flatMap(r => r.left.map(l => ({ slice: r.slice, ...l })))
log(`build-idea: ${built.length} slices built, ${left.length} items left`)

if (left.length) {
  phase('Finish')
  const sweep = await run.agent(withPreamble(
    `Finish what the slice builders left in this worktree (feature ${A.brief}, task ${A.task}): ${JSON.stringify(left)}. Everything is yours now — no other agent edits this checkout. An item that needs a product decision is left with why. Commit. Return done/left/files/commits.`
  ), { label: 'implement:sweep', phase: 'Finish', schema: IMPL_SCHEMA })
  if (!sweep) throw new Error('build-idea: leftover sweep failed; resume this run')
  built.push(sweep)
  implementationLeft = sweep.left.map(l => `${l.what}: ${l.why}`)
}

phase('Gate')
gate = await run.agent(withPreamble(
  `Gate the implementation: run every type/build/test gate CLAUDE.md names, where it says they run, plus the tests the slices wrote. Repair and commit what this branch broke; report what predates it. Report testsExecuted from the runner counts; zero executed tests cannot pass an expected suite. Return green, what ran, failures and headSha from git rev-parse HEAD after verification.`
), { label: 'gate', phase: 'Gate', schema: GATE_SCHEMA })
if (!gate || !gate.green) log(`build-idea: implementation gate red — ${JSON.stringify((gate && gate.failures) || ['no result'])}; continuing so the board shows the state`)
return nextStage('verify', { plan, built, gate, implementationLeft, codeReverifications: state.codeReverifications || 0 })
}
if (!plan || !gate || !gate.headSha) throw new Error('build-idea: the previous stage state and verified headSha are required; use its returned next.args')

if (stage === 'verify') {
phase('Verify')
loop = { boardUrl: '', passes: [], converged: false, gateRed: false, open: [], unverified: [], error: '' }
loop = await run.workflow('vitrinka:review-loop', {
    mode: 'routes',
    expectedHead: gate.headSha,
    continuation: state.continuation,
    routes: state.routes, journeys: state.journeys,
    task: A.task, project: A.project, cap: A.cap || 3, severity: A.severity || 'minor', matrix: A.matrix, scope: plan.scope,
  })
  log(`build-idea: review loop ${loop.converged ? 'converged' : `stopped with ${loop.open.length} open${loop.gateRed ? ' and a red gate' : ''}`} after ${loop.passes.length} pass(es) → ${loop.boardUrl}`)
if (loop.next) return nextStage('verify', { plan, built, gate: Object.assign({}, gate, { headSha: loop.headSha || gate.headSha }), continuation: loop.next.args.continuation, routes: loop.next.args.routes, journeys: loop.next.args.journeys, implementationLeft, codeReverifications: state.codeReverifications || 0 })
return nextStage('ship', { plan, built, gate: Object.assign({}, gate, { headSha: loop.headSha || gate.headSha }), loop, implementationLeft, codeReverifications: state.codeReverifications || 0 })
}

phase('Ship')
if (!loop) throw new Error('build-idea: verification state is required; use the verify stage next.args')
const code = await run.workflow('vitrinka:code-loop', { base: A.base || 'main', task: A.task, cap: 2, expectedHead: gate.headSha })
log(`build-idea: code loop ${code.rounds.length} round(s), ${code.remaining.length} for the human, PR ${code.pr || 'not opened'}`)
if (code.headSha && code.headSha !== loop.headSha && (state.codeReverifications || 0) < 2) {
  return nextStage('verify', { plan, built, gate: Object.assign({}, gate, { headSha: code.headSha }), implementationLeft, codeReverifications: (state.codeReverifications || 0) + 1 })
}

const handback = await run.agent(withPreamble(
  `Hand task ${A.task} back through the vitrinka handoff skill (Skill tool: vitrinka:handoff). Facts, one per line, for the summary:\n` +
  JSON.stringify({
    brief: A.brief,
    slices: built.map(b => ({ slice: b.slice, done: b.done.length, leftBeforeSweep: b.left.length })),
    implementationGate: gate && gate.green,
    reviewLoop: { board: loop.boardUrl, passes: loop.passes, converged: loop.converged, gateRed: !!loop.gateRed, open: loop.open, unverified: loop.unverified || [], error: loop.error },
    codeLoop: { rounds: code.rounds, remaining: code.remaining.length, receipt: code.receipt },
    implementationLeft,
    uiRevisionStillVerified: code.headSha === loop.headSha,
    pr: code.pr,
  }) +
  `\nOpen items (${loop.open.length + code.remaining.length}) become spotted children, not prose. Next steps hold only what is the human's: the merge${loop.open.length ? ', the open findings on the board' : ''}. Return the rendered hand-back block verbatim.`
), { label: 'handback', phase: 'Ship' })

return run.finish({ plan: plan.slices.map(s => s.name), gate: gatePassed(code.gate), board: loop.boardUrl, converged: loop.converged, pr: code.pr, handback, next: null, receipt: completionReceipt({ complete: loop.receipt.status === 'complete' && code.receipt.status === 'complete' && code.headSha === loop.headSha && !!handback, problems: [...implementationLeft, ...(loop.receipt.blockers || []), ...(code.receipt.blockers || []), ...(code.headSha !== loop.headSha ? ['code-loop changed the UI revision after the visual pass; verify the new head before claiming completion'] : [])], open: loop.open, unverified: loop.unverified, evidence: [{ headSha: code.headSha, pr: code.pr, board: loop.boardUrl }] }) })
