export const meta = {
  name: 'cleanup',
  description: 'Clean a project\'s task engine against reality: inventory every open task, group duplicates, verify each suspect against code, PRs and QA, apply what is proven, propose the rest — one report page',
  whenToUse: 'When a project\'s tasks have piled up — duplicates, stale statuses, epics nobody closed, orphans outside their epic. Launched by the cleanup skill (/vitrinka:cleanup); unattended: proven corrections are applied through the engine doors, judgment calls land as plan proposals for a human verdict, new work as intake drafts.',
  phases: [
    { title: 'Prepare', detail: 'project binding, vocabulary, counts before, pending proposals' },
    { title: 'Inventory', detail: 'every open task distilled into one file', model: 'opus' },
    { title: 'Group', detail: 'two independent readers: duplicates, suspects, orphans, epics, stale, ideas', model: 'opus' },
    { title: 'Verify', detail: 'each flagged item against code, PRs and QA — batched reviewers', model: 'opus' },
    { title: 'Apply', detail: 'proven changes through the doors, judgment calls as proposals, ideas as drafts' },
    { title: 'Report', detail: 'counts after, the cleanup page' },
  ],
}
// Code generated by tools/gen-workflows from workflows-src/flows/cleanup.js. DO NOT EDIT.
// Edit the flow or its lib/ fragments under workflows-src/, then `go run ./tools/gen-workflows`.
// ---- lib/preamble.js — the lines every agent prompt starts with
// Agents already carry the repo's CLAUDE.md; these name only what a
// workflow stage needs beyond it. Keep it to contracts, never procedure —
// procedure is served by the vitrinka server (`docs {topic}`) and the CLI's
// `--help`.
const PREAMBLE = [
  'You are one stage of a vitrinka workflow. Your final text IS the return value: return raw data for the schema, never a human-facing report.',
  'Work in the current checkout (a worktree). Never switch branches, never stash, never touch the main checkout.',
  'Apps and test suites run where the repo\'s CLAUDE.md says — a worktree\'s devbox when one exists (`devbox run -- \'<cmd>\'`), otherwise locally; say which in `problems` when you had to fall back.',
  'Every vitrinka board/task link you return is the server-returned `url`, verbatim — never composed, never shortened.',
  'Browser work: onyx `browser_start(session: $CLAUDE_CODE_SESSION_ID)` first, headless, then playwright; screenshots land in `.vitrinka/mcp/` or the capture root you were given, never the repo root.',
  'When a door refuses (4xx with a diagnosis), apply the corrected call it names once; a second refusal is a `problems` entry, not a workaround.',
].join('\n')

function withPreamble(prompt) {
  return PREAMBLE + '\n\n' + prompt
}
// args: { now: 'YYYY-MM-DD' | ISO stamp (REQUIRED — scripts cannot read the clock),
//         project?: string (default: the checkout's binding), trust?: 'evidence' | 'all' | 'none',
//         types?: string[] (default task, bug, story, epic), staleDays?: 45, focus?: string (prose narrowing),
//         readers?: 1 | 2, reviewers?: 1..4, model?: string (the long-context tier, default 'opus[1m]', falls back to 'opus') }
const A = args || {}
if (!A.now) throw new Error('cleanup: args.now (today as YYYY-MM-DD or an ISO stamp) is required — a workflow script cannot read the clock')
const TRUST = ['evidence', 'all', 'none'].includes(A.trust) ? A.trust : 'evidence'
const TYPES = Array.isArray(A.types) && A.types.length ? A.types : ['task', 'bug', 'story', 'epic']
const STALE_DAYS = Math.max(7, Math.min(365, A.staleDays || 45))
const READERS = A.readers === 1 ? 1 : 2
const REVIEWERS = Math.max(1, Math.min(4, A.reviewers || 3))
// The long-context tier for Inventory, Group and Verify. The 1M-context
// spelling is what the heavy reads want; an account without it gets the
// plain alias after the first heavy call dies (see Inventory).
let HEAVY = A.model || 'opus[1m]'
const focus = A.focus || ''
const stamp = String(A.now).replace(/[^0-9A-Za-z]+/g, '-').replace(/-+$/, '')
const DIR = `.vitrinka/cleanup/${stamp}`

// ---- schemas (this flow's own; nothing here is shared with the other flows)
const COUNT = { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, count: { type: 'integer' } }, required: ['key', 'count'] } }
const COUNTS = { type: 'object', properties: { total: { type: 'integer' }, byState: COUNT, byType: COUNT }, required: ['total', 'byState', 'byType'] }
const PROBLEMS = { type: 'array', items: { type: 'string' } }

const PREP_SCHEMA = {
  type: 'object',
  properties: {
    project: { type: 'string' },
    workspace: { type: 'string' },
    repo: { type: 'string', description: 'owner/repo of the checkout\'s origin; empty when none' },
    states: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, group: { type: 'string' } }, required: ['key', 'group'] } },
    before: COUNTS,
    pendingProposals: { type: 'integer', description: 'plan proposals already pending on the project' },
    override: { type: 'object', description: 'the cleanup section of .claude/vitrinka-workflows.json, {} when absent' },
    problems: PROBLEMS,
  },
  required: ['project', 'before', 'pendingProposals'],
}

const INVENTORY_SCHEMA = {
  type: 'object',
  properties: {
    path: { type: 'string', description: 'repo-relative path of inventory.json' },
    donePath: { type: 'string', description: 'repo-relative path of done.json' },
    count: { type: 'integer' },
    doneCount: { type: 'integer' },
    byType: COUNT,
    epics: { type: 'array', items: { type: 'object', properties: { id: { type: 'integer' }, title: { type: 'string' }, status: { type: 'string' }, childOpen: { type: 'integer' }, childDone: { type: 'integer' }, ledgerState: { type: 'string' } }, required: ['id', 'title', 'status'] } },
    problems: PROBLEMS,
  },
  required: ['path', 'count', 'byType', 'epics'],
}

const CLUSTER = { type: 'object', properties: { ids: { type: 'array', items: { type: 'integer' }, minItems: 2 }, survivor: { type: 'integer', description: 'the task the others fold into (0 when unsure)' }, why: { type: 'string' }, confidence: { type: 'string', enum: ['certain', 'likely', 'possible'] } }, required: ['ids', 'why', 'confidence'] }
const FLAG = { type: 'object', properties: { id: { type: 'integer' }, looksLike: { type: 'string', description: 'the reading: the status/state it should probably have, the epic it belongs to, the reason it is stale' }, why: { type: 'string' } }, required: ['id', 'looksLike', 'why'] }
const EPIC_FLAG = { type: 'object', properties: { id: { type: 'integer' }, verdict: { type: 'string', enum: ['close', 'refine', 'split', 'ok'] }, why: { type: 'string' } }, required: ['id', 'verdict', 'why'] }
const IDEA = { type: 'object', properties: { title: { type: 'string' }, why: { type: 'string' }, evidence: { type: 'string', description: 'the task ids and facts the idea rests on' }, type: { type: 'string', enum: ['task', 'bug', 'story', 'epic'] } }, required: ['title', 'why', 'evidence'] }
const GROUP_SCHEMA = {
  type: 'object',
  properties: {
    clusters: { type: 'array', items: CLUSTER },
    suspects: { type: 'array', items: FLAG },
    orphans: { type: 'array', items: FLAG },
    epics: { type: 'array', items: EPIC_FLAG },
    stale: { type: 'array', items: FLAG },
    ideas: { type: 'array', items: IDEA },
    problems: PROBLEMS,
  },
  required: ['clusters', 'suspects', 'orphans', 'epics', 'stale', 'ideas'],
}

const ACTION = {
  type: 'object',
  properties: {
    kind: { type: 'string', enum: ['status', 'duplicate', 'reparent', 'epic', 'relate', 'propose', 'none'] },
    id: { type: 'integer', description: 'the task the action is about (absent for propose)' },
    to: { type: 'string', enum: ['backlog', 'todo', 'in_progress', 'in_review', 'done', 'cancelled'], description: 'status: the corrected status' },
    into: { type: 'integer', description: 'duplicate: the task that survives' },
    parentId: { type: 'integer', description: 'reparent: the epic to file under' },
    rel: { type: 'string', enum: ['relates', 'blocks'], description: 'relate: the relation from id to into' },
    fields: { type: 'object', description: 'epic: the feature-preset patch — ledger_state, next_action, waiting_on (only the keys that change)' },
    close: { type: 'boolean', description: 'epic: also move it to done' },
    title: { type: 'string', description: 'propose: the new task\'s title' },
    body: { type: 'string', description: 'propose: markdown body — what, why now, the evidence' },
    type: { type: 'string', enum: ['task', 'bug', 'story', 'epic'] },
    priority: { type: 'string', enum: ['urgent', 'high', 'medium', 'low'] },
    evidence: { type: 'string', description: 'citable proof: PR (owner/repo#n, merged on), commit, run id, file path, comment' },
    certainty: { type: 'string', enum: ['proven', 'likely', 'unclear'] },
    why: { type: 'string' },
  },
  required: ['kind', 'certainty', 'why'],
}
const VERIFY_SCHEMA = {
  type: 'object',
  properties: {
    actions: { type: 'array', items: ACTION },
    reviewed: { type: 'array', items: { type: 'integer' }, description: 'every task id the reviewer actually checked' },
    problems: PROBLEMS,
  },
  required: ['actions', 'reviewed'],
}

const RECEIPT = { type: 'object', properties: { kind: { type: 'string' }, id: { type: 'integer' }, ok: { type: 'boolean' }, url: { type: 'string' }, note: { type: 'string', description: 'the refusal\'s diagnosis, "already pending", or the dedupe verdict of a draft' } }, required: ['kind', 'ok'] }
const APPLY_SCHEMA = {
  type: 'object',
  properties: { receipts: { type: 'array', items: RECEIPT }, problems: PROBLEMS },
  required: ['receipts'],
}

const REPORT_SCHEMA = {
  type: 'object',
  properties: { after: COUNTS, reportUrl: { type: 'string' }, boardUrl: { type: 'string' }, problems: PROBLEMS },
  required: ['after', 'reportUrl'],
}

// ---- plain code
const RANK = { certain: 3, likely: 2, possible: 1 }
const NAME = { 3: 'certain', 2: 'likely', 1: 'possible' }
const CERT = { proven: 3, likely: 2, unclear: 1 }

function sortIds(ids) {
  return [...new Set((ids || []).map(Number).filter(n => n > 0))].sort((a, b) => a - b)
}

// Two readers saw the same inventory. A cluster both found (sharing at least
// two ids) is kept as their intersection one confidence notch up; a cluster
// only one found is kept, capped at likely — never certain on one reading.
function reconcileClusters(a, b) {
  const used = new Set()
  const out = []
  for (const ca of a) {
    const idsA = sortIds(ca.ids)
    if (idsA.length < 2) continue
    let best = -1
    let bestShared = 0
    b.forEach((cb, i) => {
      if (used.has(i)) return
      const shared = sortIds(cb.ids).filter(id => idsA.includes(id)).length
      if (shared >= 2 && shared > bestShared) { best = i; bestShared = shared }
    })
    if (best >= 0) {
      used.add(best)
      const cb = b[best]
      const ids = idsA.filter(id => sortIds(cb.ids).includes(id))
      const conf = Math.min(3, Math.max(RANK[ca.confidence] || 1, RANK[cb.confidence] || 1) + 1)
      out.push({ ids, survivor: ca.survivor === cb.survivor ? (ca.survivor || 0) : 0, why: `${ca.why} | ${cb.why}`, confidence: NAME[conf], agreed: true })
    } else {
      out.push({ ids: idsA, survivor: ca.survivor || 0, why: ca.why, confidence: NAME[Math.min(2, RANK[ca.confidence] || 1)], agreed: false })
    }
  }
  b.forEach((cb, i) => {
    const ids = sortIds(cb.ids)
    if (used.has(i) || ids.length < 2) return
    out.push({ ids, survivor: cb.survivor || 0, why: cb.why, confidence: NAME[Math.min(2, RANK[cb.confidence] || 1)], agreed: false })
  })
  return out.sort((x, y) => x.ids[0] - y.ids[0])
}

// Flags (suspects, orphans, stale, epics) union by id; a flag both readers
// raised is marked agreed and carries both readings.
function unionFlags(a, b) {
  const byId = new Map()
  for (const f of a) if (f && f.id) byId.set(f.id, { ...f, agreed: false })
  for (const f of b) {
    if (!f || !f.id) continue
    const have = byId.get(f.id)
    if (have) {
      have.agreed = true
      if (f.why && !have.why.includes(f.why)) have.why = `${have.why} | ${f.why}`
      if (f.verdict && have.verdict !== f.verdict) have.verdict = have.verdict === 'ok' ? f.verdict : have.verdict
    } else byId.set(f.id, { ...f, agreed: false })
  }
  return [...byId.values()].sort((x, y) => x.id - y.id)
}

// Ideas union by normalized title.
function unionIdeas(a, b) {
  const seen = new Map()
  for (const i of [...a, ...b]) {
    const k = (i.title || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()
    if (!k) continue
    if (!seen.has(k)) seen.set(k, { ...i, agreed: false })
    else seen.get(k).agreed = true
  }
  return [...seen.values()]
}

// Round-robin over a deterministic order so every reviewer carries a similar
// load and a resume replays the same batches.
function batches(items, n) {
  const out = Array.from({ length: Math.min(n, Math.max(1, items.length)) }, () => [])
  items.forEach((it, i) => out[i % out.length].push(it))
  return out.filter(b => b.length)
}

// Where an action goes under the trust level. `proposable` names the two
// ops the engine's proposal door knows for a live task: close and merge.
function proposable(a) {
  return (a.kind === 'status' && (a.to === 'done' || a.to === 'cancelled')) || a.kind === 'duplicate'
}
function route(a) {
  if (a.kind === 'none') return 'reviewed'
  if (a.kind === 'propose') return 'draft'
  const c = CERT[a.certainty] || 1
  const minApply = TRUST === 'all' ? 2 : TRUST === 'evidence' ? 3 : 4
  if (c >= minApply) return 'apply'
  if (proposable(a) && (c >= 2 || TRUST === 'all')) return 'propose'
  return 'report'
}

// One decision per task: a duplicate verdict outranks a status verdict on
// the same id, two verdicts of one kind on one task keep the surer one
// (a status tie into report), a duplicate pair pointing at each other is a
// report entry, never a cycle. Reviewers overlap (a cluster and a suspect
// can name the same task), so every kind is keyed and never filed twice.
function settle(actions) {
  const dupFrom = new Map()
  for (const a of actions) if (a.kind === 'duplicate' && a.id && a.into && a.id !== a.into) dupFrom.set(a.id, a.into)
  // Only a duplicate that survives settling outranks a status verdict; a
  // mutual pair lands in conflicts, so its tasks keep their status readings.
  const merged = new Set([...dupFrom].filter(([id, into]) => dupFrom.get(into) !== id).map(([id]) => id))
  const conflicts = []
  const out = []
  const byKey = new Map()
  const keyOf = a => a.kind === 'duplicate' ? `duplicate:${a.id}>${a.into}` : a.kind === 'relate' ? `relate:${a.id}>${a.into}` : `${a.kind}:${a.id}`
  const surer = (a, b) => (CERT[a.certainty] || 1) > (CERT[b.certainty] || 1)
  for (const a of actions) {
    if (a.kind === 'propose') { out.push(a); continue }
    if (a.kind === 'duplicate') {
      if (!a.id || !a.into || a.id === a.into) { conflicts.push({ ...a, why: `malformed duplicate: ${a.why}` }); continue }
      if (dupFrom.get(a.into) === a.id) { conflicts.push({ ...a, why: `mutual duplicate #${a.id} ⇄ #${a.into}: ${a.why}` }); continue }
    }
    if (a.kind === 'status') {
      if (!a.id || !a.to) { conflicts.push({ ...a, why: `malformed status: ${a.why}` }); continue }
      if (merged.has(a.id)) continue
    }
    if (!a.id) { conflicts.push({ ...a, why: `malformed ${a.kind} without id: ${a.why}` }); continue }
    const k = keyOf(a)
    const have = byKey.get(k)
    if (!have) { byKey.set(k, a); continue }
    if (surer(a, have)) { byKey.set(k, a); continue }
    if (a.kind === 'status' && !surer(have, a) && have.to !== a.to) {
      conflicts.push({ ...have, why: `two readings: ${have.to} (${have.why}) vs ${a.to} (${a.why})` })
      byKey.delete(k)
    }
  }
  out.push(...byKey.values())
  return { actions: out.sort((x, y) => (x.id || 0) - (y.id || 0)), conflicts }
}

// ---- Prepare
phase('Prepare')
const prep = await agent(withPreamble(
  `Prepare a task cleanup run for ${A.project ? `vitrinka project "${A.project}"` : 'the vitrinka project this checkout is bound to'}. Read-only: create, change and comment nothing.\n` +
  `1. Resolve the project slug${A.project ? '' : ' (`vitrinka status --json`, else the root vitrinka.config.json `project`)'} and its workspace; the checkout's origin as owner/repo (empty when none).\n` +
  `2. \`list {kind: "state", project}\` — every state key with its group.\n` +
  `3. \`summarize_tasks {project}\` grouped by state and again by type — the counts BEFORE.\n` +
  `4. \`list {kind: "intake", project, view: "summary"}\` — the pending plan proposals are the plan and stale group counts.\n` +
  `5. Read \`.claude/vitrinka-workflows.json\` if it exists and return its \`cleanup\` object as \`override\` ({} when absent or without one).\n` +
  `Return the structured result; anything you could not determine is a \`problems\` line.`
), { label: 'prepare', phase: 'Prepare', schema: PREP_SCHEMA })
if (!prep) throw new Error('cleanup: prepare failed')
const project = prep.project
const override = prep.override || {}
const staleDays = override.staleDays && !A.staleDays ? Math.max(7, Math.min(365, override.staleDays)) : STALE_DAYS
const protect = Array.isArray(override.protectLabels) ? override.protectLabels : []
log(`cleanup: ${project} — ${prep.before.total} tasks, ${prep.pendingProposals} proposals pending, trust ${TRUST}, stale after ${staleDays} days, types ${TYPES.join('/')}`)

// ---- Inventory
phase('Inventory')
const inventoryPrompt = withPreamble(
  `Inventory the open tasks of vitrinka project "${project}" into files under ${DIR}/ (create the directory; .vitrinka/ is git-ignored). Read-only against the server.\n` +
  `OPEN SET: page \`list {kind: "task", project: "${project}", fields: "full", limit: 40, budget: 30000, f: {groups: ["backlog", "unstarted", "started"], types: ${JSON.stringify(TYPES)}}}\`, passing nextCursor back as cursor until it is empty; use \`select\` to keep only id, title, body, type, state, status, parentId, labels, priority, assignee, createdAt, updatedAt, prs, runs, childCount, fields, url. Never stop at one page; never sample. Your context is finite and the pages are not: the moment a page arrives, write its distilled records to ${DIR}/pages/open-<n>.json (a JSON array) and move on — never echo a page back, never hold more than one in flight; at the end merge the pages in order into the inventory file (\`jq -s 'add | sort_by(.id)' ${DIR}/pages/open-*.json > ${DIR}/inventory.json\`).\n` +
  `Write ${DIR}/inventory.json — a JSON array, one record per task, sorted by id:\n` +
  `{id, type, state, status, title, parentId, labels, priority, assignee, createdAt, updatedAt, url, prs: [{ref, state, merged}], runs, childCount: {total, done}, fields: {ledger_state, next_action, waiting_on, outcome} (epics only, ≤ 200 chars each), gist: "≤ 30 words — what the task asks for, distilled from the body; never a copy of the title", evidence: "one line naming what the body cites — PRs, commits, files, boards, runs — or empty"}.\n` +
  `DONE SET: page \`list {kind: "task", project: "${project}", fields: "summary", limit: 200, budget: 30000, f: {groups: ["completed"], types: ${JSON.stringify(TYPES)}, order: "created"}}\` the same way (select id, title, type, parentId, updatedAt, prs) and write ${DIR}/done.json as [{id, title, type, parentId, updatedAt, merged: <true when a pr ref is merged>}] sorted by id. It is the reference for "already done".\n` +
  `Return the paths, counts, the count by type, and every open epic with its child counts (from childCount) and ledger_state. A page that fails after the corrected call is a \`problems\` line naming the cursor — the run must know the inventory is partial.`
)
let inv = await agent(inventoryPrompt, { label: 'inventory', phase: 'Inventory', schema: INVENTORY_SCHEMA, model: HEAVY })
if (!inv && HEAVY !== 'opus') {
  // A dead first heavy agent is the model spelling, not the project: the
  // plain alias is documented everywhere the 1M variant is not.
  log(`cleanup: the inventory agent died on model ${HEAVY} — retrying on opus, which the rest of the run keeps`)
  HEAVY = 'opus'
  inv = await agent(inventoryPrompt, { label: 'inventory:retry', phase: 'Inventory', schema: INVENTORY_SCHEMA, model: HEAVY })
}
// Zero open tasks is a clean project, not a failed inventory: it runs on to
// "nothing flagged" and the report.
if (!inv) throw new Error('cleanup: inventory produced nothing')
log(`cleanup: ${inv.count} open tasks in ${inv.path}, ${inv.doneCount || 0} done, ${inv.epics.length} open epics${(inv.problems || []).length ? ` — ${inv.problems.length} problem(s)` : ''}`)

// ---- Group
phase('Group')
const groupPrompt = (n) => withPreamble(
  `Reader ${n} of ${READERS}: read ${inv.path} (every open task of project "${project}", ${inv.count} records) and ${inv.donePath || `${DIR}/done.json`} (what is already done) in full — the whole files, never a sample — and report what a cleanup should look at. Today is ${A.now}; stale means untouched for ${staleDays} days. Read-only: touch nothing on the server.\n` +
  (focus ? `Focus: ${focus}\n` : '') +
  (protect.length ? `Tasks labelled ${JSON.stringify(protect)} are protected: never list them.\n` : '') +
  `Report, each with a one-line why that names the ids and facts:\n` +
  `- clusters: tasks asking for the SAME thing (the same bug, the same feature, the same chore) — duplicates or overlaps to fold into one. Same area is not the same ask; a parent and its child, an epic and its story, a qa plan and its journeys are never duplicates. Name the survivor (the one with the most evidence, history or the epic's own child) and your confidence.\n` +
  `- suspects: tasks whose status contradicts their own row — a merged PR ref on a task not done; in_review without a PR or run; in_progress untouched for ${staleDays} days; a backlog/todo task whose gist a done.json entry already covers (name that id); a story/task with every child done but itself open.\n` +
  `- orphans: open tasks with no parentId whose gist plainly belongs to one open epic (name it in looksLike).\n` +
  `- epics: every open epic — close (all children done and the outcome met, or nothing left to do), refine (children open but next_action/waiting_on/ledger_state are stale, empty or contradicted by the children), split (more than 15 open children with distinct themes), or ok.\n` +
  `- stale: open tasks untouched for ${staleDays} days with no PR, no run, no assignee and no epic activity — cancel candidates.\n` +
  `- ideas: what the shape of this backlog says the team should really do next — several bugs in one area that want an epic, a recurring ask nobody filed, a missing gate — each with the ids as evidence. At most 8.\n` +
  `Be exhaustive on clusters and suspects, precise on why; certainty is claimed only when the rows alone prove it.`
)
const readings = (await parallel(Array.from({ length: READERS }, (_, i) => () => agent(groupPrompt(i + 1), { label: `group:${i + 1}`, phase: 'Group', schema: GROUP_SCHEMA, model: HEAVY })))).filter(Boolean)
if (!readings.length) throw new Error('cleanup: every grouping reader failed')
const g = readings.length === 2
  ? {
    clusters: reconcileClusters(readings[0].clusters, readings[1].clusters),
    suspects: unionFlags(readings[0].suspects, readings[1].suspects),
    orphans: unionFlags(readings[0].orphans, readings[1].orphans),
    epics: unionFlags(readings[0].epics, readings[1].epics).filter(e => e.verdict !== 'ok'),
    stale: unionFlags(readings[0].stale, readings[1].stale),
    ideas: unionIdeas(readings[0].ideas, readings[1].ideas),
  }
  : {
    clusters: reconcileClusters(readings[0].clusters, []),
    suspects: unionFlags(readings[0].suspects, []),
    orphans: unionFlags(readings[0].orphans, []),
    epics: unionFlags(readings[0].epics, []).filter(e => e.verdict !== 'ok'),
    stale: unionFlags(readings[0].stale, []),
    ideas: unionIdeas(readings[0].ideas, []),
  }
if (readings.length < READERS) log(`cleanup: only ${readings.length} of ${READERS} readers answered — nothing is marked agreed`)
log(`cleanup: ${g.clusters.length} clusters, ${g.suspects.length} suspects, ${g.orphans.length} orphans, ${g.epics.length} epics to close/refine/split, ${g.stale.length} stale, ${g.ideas.length} ideas`)

// ---- Verify
phase('Verify')
const items = [
  ...g.clusters.map(c => ({ kind: 'cluster', ...c })),
  ...g.suspects.map(s => ({ kind: 'suspect', ...s })),
  ...g.orphans.map(o => ({ kind: 'orphan', ...o })),
  ...g.epics.map(e => ({ kind: 'epic', ...e })),
  ...g.stale.map(s => ({ kind: 'stale', ...s })),
]
const ideaItems = g.ideas.map(i => ({ kind: 'idea', ...i }))
let verified = []
if (items.length || ideaItems.length) {
  const lanes = batches(items, REVIEWERS)
  if (ideaItems.length) (lanes[0] || (lanes[0] = [])).push(...ideaItems)
  const verifyPrompt = (batch, n) => withPreamble(
    `Reviewer ${n} of ${lanes.length} in a cleanup of vitrinka project "${project}" (today ${A.now}${prep.repo ? `, repo ${prep.repo}` : ''}). Two readers flagged these items from the inventory (${inv.path} holds every open task's row and gist; ${inv.donePath || `${DIR}/done.json`} what is done). Verify EACH against reality and return one action per item — the reading is a hypothesis, never a finding. Read-only: change nothing on the server.\n` +
    `Items:\n${JSON.stringify(batch)}\n\n` +
    `Reality, in this order, stopping when the evidence is decisive: (1) the task itself — \`get {kind: "task", id, include: ["refs", "links", "children", "comments"]}\` (PR refs carry meta.merged; runs and journey verdicts are the QA record); (2) this checkout — \`git log --all --grep 'vt-<id>' --oneline\` and \`git log --all --grep 'Vitrinka-Task: vt-<id>'\`, then whether the code or file the task names exists now; (3) GitHub when the row has no PR ref — \`gh pr list --state all --search 'vt-<id>' --json number,state,mergedAt,title\`; (4) for an epic, its children's statuses and the feature preset (outcome, gates, next_action, waiting_on). Never pull transcripts; \`ask_task\` only when a single question decides an item.\n` +
    `Actions and their certainty:\n` +
    `- status {id, to, evidence}: proven only with a merged PR, a passing run, a commit trailer, or the thing visibly existing/removed; a stale in_progress without evidence is likely at most.\n` +
    `- duplicate {id, into, evidence}: the survivor keeps history; proven when both ask for the same thing and one already carries the work (PR, comments, epic child), likely when the asks match and neither has work, unclear when they merely overlap (then prefer relate).\n` +
    `- reparent {id, parentId}: proven when the epic's outcome names the ask or the task's own body/refs name the epic.\n` +
    `- epic {id, close?: true, fields}: close only with every child done or cancelled AND the outcome met (say how); refine sets next_action/waiting_on/ledger_state to what the children say now (ledger_state: scheduled | active | waiting | superseded | closed); a split is always unclear (report only).\n` +
    `- relate {id, into, rel}: relates | blocks for overlaps that are not duplicates.\n` +
    `- propose {title, body, type, priority, evidence}: ONE draft per idea item (or per gap you prove while verifying) — the "we should really do this" list; body says what, why now, and cites the ids.\n` +
    `- none {id, why}: checked, nothing to change — say what you checked.\n` +
    `Every action cites its evidence as something a human can open (PR ref, commit sha, run id, file path, task id). \`reviewed\` lists every task id you actually read.`
  )
  verified = (await parallel(lanes.map((batch, i) => () => agent(verifyPrompt(batch, i + 1), { label: `verify:${i + 1}`, phase: 'Verify', schema: VERIFY_SCHEMA, model: HEAVY })))).filter(Boolean)
  if (verified.length < lanes.length) log(`cleanup: ${lanes.length - verified.length} of ${lanes.length} reviewers failed — their items are unverified and stay out of the plan`)
} else {
  log('cleanup: nothing flagged — the project reads clean')
}
const reviewedIds = sortIds(verified.flatMap(v => v.reviewed || []))
const settled = settle(verified.flatMap(v => v.actions || []))

// ---- Plan (plain code)
const plan = { apply: [], propose: [], draft: [], report: [], reviewed: [] }
for (const a of settled.actions) plan[route(a)].push(a)
plan.report.push(...settled.conflicts.map(c => ({ ...c, certainty: 'unclear' })))
log(`cleanup: plan — apply ${plan.apply.length}, propose ${plan.propose.length}, drafts ${plan.draft.length}, report-only ${plan.report.length}, no change ${plan.reviewed.length}${settled.conflicts.length ? `, ${settled.conflicts.length} conflict(s)` : ''}`)

// ---- Apply
phase('Apply')
const receipts = []
const ws = prep.workspace || ''
const idOf = ws ? `"${ws}/<id>" (this grant may reach several workspaces — every id-only door takes the workspace-spelled id)` : '<id>'
const applyPrompt = (work, n, of) => withPreamble(
  `Apply lane ${n} of ${of} of the cleanup of vitrinka project "${project}" (stamp ${stamp}). Every write goes through the engine doors below, nothing else. Task ids on id-only doors are spelled ${idOf}; titles come from the inventory at ${inv.path} (jq by id) — never guessed, never refiled. A refusal names the corrected call: apply it once, then record the outcome; never invent a second path.\n` +
  (work.apply.length ? `APPLY (${work.apply.length}) — every applied change lands ONE comment \`create {kind: "comment", id, body}\` on the task, starting with "Cleanup ${A.now}:" and stating the change and its evidence — the comment is the record. Before a status close or a duplicate, find any pending proposal whose source ref starts with "cleanup:" and that names the same op and target (\`list {kind: "intake", project: "${project}", group: "plan"}\` then \`group: "stale"\`, each paged with select id,source,proposal — the proposal list door is the brief's short list) and decline it (\`proposal_verdict {id, verdict: "decline"}\`) — a change applied directly supersedes its own earlier proposal. If the verdict door answers forbidden (a member grant cannot verdict), list those proposal ids in the receipt note and go on: the report hands them to an admin.\n${JSON.stringify(work.apply)}\n` +
    `- status → group ids by target status and call \`bulk_update_tasks {ids, patch: {status}}\` once per status (epics included; if the door refuses bare ids on this grant, \`update {kind: "task", id, status}\` per task), then the comments.\n` +
    `- duplicate → \`create_task_link {id, toTaskId: into, rel: "duplicates"}\`, then \`update {kind: "task", id, status: "cancelled"}\`; comment on id ("cancelled as a duplicate of #into — evidence") AND on into ("#id folded here — its gist and any evidence it carried").\n` +
    `- reparent → \`update {kind: "task", id, parentId}\` + comment.\n` +
    `- epic → \`update {kind: "task", id, fields}\` (partial merge — only the keys given), plus \`status: "done"\` when close is true; comment with the evidence.\n` +
    `- relate → \`create_task_link {id, toTaskId: into, rel}\` + one comment on id.\n` : '') +
  (work.propose.length ? `PROPOSE (${work.propose.length}) — judgment calls for a human verdict, ONE call each, no comment on the task (the draft body is the record): \`propose_tasks {project: "${project}", source: {kind: "eve:plan", ref: "cleanup:${stamp}", meta: {proposal: {op, target, into?, group?, reason}}}, drafts: [{title, body}]}\` where status done → {op: "close", target: id, group: "completed"}, status cancelled → {op: "close", target: id, group: "cancelled"}, duplicate → {op: "merge", target: id, into}; title "Close #id — <task title>" or "Merge #id into #into — <task title>", body = why + evidence. A 409 saying the change is already proposed is a receipt {ok: true, note: "already pending"}, not a retry. The draft's dedupe verdict will read likely-duplicate against its own target (the title quotes it) — expected, not a finding.\n${JSON.stringify(work.propose)}\n` : '') +
  (work.draft.length ? `DRAFTS (${work.draft.length}) — new work for the human to accept. First \`list {kind: "intake", project: "${project}", group: "cleanup"}\`: a pending draft with the same title already filed from source ref "${stamp}" is a receipt {ok: true, note: "already filed"}, never refiled (a rerun the same day must not double the intake). Then ONE \`propose_tasks {project: "${project}", source: {kind: "cleanup", ref: "${stamp}"}, drafts: [...]}\` call (≤ 50 per call) with {title, body, type, priority}; keep each draft's dedupe verdict in its receipt note.\n${JSON.stringify(work.draft)}\n` : '') +
  `Return one receipt per item: APPLY items keep their action kind (status · duplicate · reparent · epic · relate), PROPOSE items are kind "proposal", DRAFTS items kind "draft"; id (the task acted on, the target for a proposal), ok, the server-returned url (the task for an applied change, the draft for a proposal or draft), note.`
)
const split = plan.apply.length + plan.propose.length > 80 ? 2 : 1
const lanesToApply = []
if (split === 1) lanesToApply.push(plan)
else {
  lanesToApply.push({ apply: plan.apply.filter((_, i) => i % 2 === 0), propose: plan.propose.filter((_, i) => i % 2 === 0), draft: plan.draft })
  lanesToApply.push({ apply: plan.apply.filter((_, i) => i % 2 === 1), propose: plan.propose.filter((_, i) => i % 2 === 1), draft: [] })
}
if (plan.apply.length || plan.propose.length || plan.draft.length) {
  const applied = (await parallel(lanesToApply.map((work, i) => () => agent(applyPrompt(work, i + 1, lanesToApply.length), { label: `apply:${i + 1}`, phase: 'Apply', schema: APPLY_SCHEMA })))).filter(Boolean)
  for (const r of applied) receipts.push(...(r.receipts || []))
  const failed = receipts.filter(r => !r.ok)
  log(`cleanup: ${receipts.length - failed.length} receipts ok${failed.length ? `, ${failed.length} refused` : ''}`)
} else {
  log('cleanup: nothing to apply, propose or draft')
}

// ---- Report
phase('Report')
const facts = {
  project, stamp: A.now, trust: TRUST, staleDays, types: TYPES, focus,
  before: prep.before, pendingProposalsBefore: prep.pendingProposals,
  inventory: { open: inv.count, done: inv.doneCount || 0, epics: inv.epics.length, problems: inv.problems || [] },
  readers: readings.length,
  flagged: { clusters: g.clusters.length, suspects: g.suspects.length, orphans: g.orphans.length, epics: g.epics.length, stale: g.stale.length, ideas: g.ideas.length },
  reviewed: reviewedIds.length,
  plan: { apply: plan.apply, propose: plan.propose, draft: plan.draft, reportOnly: plan.report, noChange: plan.reviewed },
  receipts,
  problems: [].concat(prep.problems || [], inv.problems || [], ...readings.map(r => r.problems || []), ...verified.map(v => v.problems || [])),
}
const report = await agent(withPreamble(
  `Close the cleanup of vitrinka project "${project}" (${A.now}). First \`summarize_tasks {project: "${project}"}\` by state and by type — the counts AFTER. Then author ONE artifact page through the vitrinka artifact skill (Skill tool: vitrinka:artifact) titled "Cleanup — ${project} — ${A.now}" on the project's documentation board, from these facts:\n${JSON.stringify(facts)}\n` +
  `Sections, in this order, each a table or a list a PM scans in a minute: Counts (before → after by state); Applied (task · action · evidence · link, from the receipts with ok); Proposed for a verdict (op · target · reason — and where: the project's Proposals view); New work drafted (title · dedupe verdict); Report only (what needs a human reading: conflicts, unclear items, split candidates, refused writes with their diagnosis); Reviewed with no change (ids, one line); Not checked (types and groups outside the run, inventory problems, reviewers that failed). Every task link is the server-returned url. Return the artifact's url as reportUrl and its board as boardUrl.`
), { label: 'report', phase: 'Report', schema: REPORT_SCHEMA })
if (!report) log('cleanup: the report page was not written — the receipts are the record')

const okReceipts = receipts.filter(r => r.ok)
return {
  project,
  trust: TRUST,
  before: prep.before,
  after: report ? report.after : null,
  applied: okReceipts.filter(r => ['status', 'duplicate', 'reparent', 'epic', 'relate'].includes(r.kind)).length,
  proposed: okReceipts.filter(r => r.kind === 'proposal').length,
  drafted: okReceipts.filter(r => r.kind === 'draft').length,
  refused: receipts.filter(r => !r.ok).length,
  reportOnly: plan.report.length,
  reportUrl: report ? report.reportUrl : '',
  boardUrl: report ? report.boardUrl || '' : '',
}
