export const meta = {
  name: 'map',
  description: 'Map the terrain an idea or a review pass stands on: routes, model and doors, components, tests — one terrain artifact on the board',
  whenToUse: 'Before brainstorming an idea in a big project (scope: idea) or before a full-app review pass (scope: app). make-idea and review-loop call it; run it alone to refresh the map.',
  phases: [
    { title: 'Explore', detail: 'four readers, one per layer' },
    { title: 'Synthesize', detail: 'one terrain artifact, extend points, duplication risks' },
  ],
}
// Code generated by tools/gen-workflows from workflows-src/flows/map.js. DO NOT EDIT.
// Edit the flow or its lib/ fragments under workflows-src/, then `go run ./tools/gen-workflows`.
// ---- lib/preamble.js — the lines every agent prompt starts with
// Agents already carry the repo's CLAUDE.md; these name only what a
// workflow stage needs beyond it. Keep it to contracts, never procedure —
// procedure is served by the vitrinka server (`docs {topic}`) and the CLI's
// `--help`.
const PREAMBLE = [
  'You are one stage of a vitrinka workflow. Your final text IS the return value: return raw data for the schema, never a human-facing report.',
  'Work in the current checkout (a worktree). Never switch branches, never stash, never touch the main checkout.',
  'Apps and test suites run where the repo\'s CLAUDE.md says — a worktree\'s devbox when one exists (`devbox run -- \'<cmd>\'`), otherwise locally; say which in `problems` when you had to fall back.',
  'Every vitrinka board/task link you return is the server-returned `url`, verbatim — never composed, never shortened.',
  'Browser work: onyx `browser_start(session: $CLAUDE_CODE_SESSION_ID)` first, headless, then playwright; screenshots land in `.vitrinka/mcp/` or the capture root you were given, never the repo root.',
  'When a door refuses (4xx with a diagnosis), apply the corrected call it names once; a second refusal is a `problems` entry, not a workaround.',
].join('\n')

function withPreamble(prompt) {
  return PREAMBLE + '\n\n' + prompt
}
// ---- lib/schemas.js — structured-output schemas shared by the flows
const ROUTE = {
  type: 'object',
  properties: {
    path: { type: 'string' },
    title: { type: 'string' },
    file: { type: 'string', description: 'repo-relative implementing file' },
    auth: { type: 'string', description: 'none | user | admin | <role>' },
    setup: { type: 'string', description: 'how to reach it with data on screen (seed, fixture, deep link)' },
  },
  required: ['path', 'title'],
}

const TERRAIN_SCHEMA = {
  type: 'object',
  properties: {
    projectType: { type: 'string', enum: ['web', 'expo', 'cli', 'other'] },
    routes: { type: 'array', items: ROUTE },
    journeys: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          steps: { type: 'array', items: { type: 'string' } },
          roles: { type: 'array', items: { type: 'string' } },
        },
        required: ['title', 'steps'],
      },
    },
    extendPoints: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, file: { type: 'string' }, why: { type: 'string' } }, required: ['what', 'file'] } },
    duplicationRisks: { type: 'array', items: { type: 'object', properties: { risk: { type: 'string' }, existing: { type: 'string' } }, required: ['risk', 'existing'] } },
    openQuestions: { type: 'array', items: { type: 'string' } },
    terrainUrl: { type: 'string', description: 'server-returned url of the pushed terrain artifact, empty when not pushed' },
    boardUrl: { type: 'string' },
  },
  required: ['projectType', 'routes'],
}

const FINDING = {
  type: 'object',
  properties: {
    key: { type: 'string' },
    id: { type: 'integer', description: 'annotation id from the annotate receipt' },
    cardId: { type: 'integer' },
    route: { type: 'string' },
    device: { type: 'string' },
    area: { type: 'string', description: 'route, component or subsystem the fix lives in' },
    kind: { type: 'string', enum: ['finding', 'suggestion'] },
    severity: { type: 'string', enum: ['blocker', 'major', 'minor'] },
    rule: { type: 'string' },
    summary: { type: 'string' },
    files: { type: 'array', items: { type: 'string' } },
  },
  required: ['key', 'area', 'kind', 'severity', 'summary'],
}

const FINDINGS_SCHEMA = {
  type: 'object',
  properties: {
    findings: { type: 'array', items: FINDING },
    regressions: { type: 'array', items: { type: 'object', properties: { id: { type: 'integer' }, key: { type: 'string' }, fixed: { type: 'boolean' }, note: { type: 'string' } }, required: ['key', 'fixed'] } },
    screensRead: { type: 'integer' },
    boardUrl: { type: 'string' },
  },
  required: ['findings'],
}

const SHOOT_SCHEMA = {
  type: 'object',
  properties: {
    device: { type: 'string' },
    shots: { type: 'array', items: { type: 'object', properties: { route: { type: 'string' }, label: { type: 'string' }, file: { type: 'string' } }, required: ['route', 'label'] } },
    boardUrl: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['device', 'shots'],
}

const USERTEST_SCHEMA = {
  type: 'object',
  properties: {
    qaTaskUrl: { type: 'string' },
    boardUrl: { type: 'string' },
    cases: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, device: { type: 'string' }, verdict: { type: 'string', enum: ['pass', 'fail', 'skip'] }, note: { type: 'string' }, files: { type: 'array', items: { type: 'string' } } }, required: ['title', 'verdict'] } },
    bugs: { type: 'array', items: { type: 'string', description: 'task url of each bug filed' } },
  },
  required: ['cases'],
}

const FIX_SCHEMA = {
  type: 'object',
  properties: {
    fixed: { type: 'array', items: { type: 'string', description: 'finding key' } },
    skipped: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, why: { type: 'string' } }, required: ['key', 'why'] } },
    touchedRoutes: { type: 'array', items: { type: 'string' } },
    touchedFiles: { type: 'array', items: { type: 'string' } },
    commits: { type: 'array', items: { type: 'string' } },
  },
  required: ['fixed', 'skipped', 'touchedRoutes', 'touchedFiles'],
}

const GATE_SCHEMA = {
  type: 'object',
  properties: {
    green: { type: 'boolean' },
    ran: { type: 'array', items: { type: 'string' } },
    failures: { type: 'array', items: { type: 'string' } },
    repaired: { type: 'boolean' },
  },
  required: ['green', 'ran'],
}

const PREPARE_SCHEMA = {
  type: 'object',
  properties: {
    baseUrl: { type: 'string' },
    where: { type: 'string', enum: ['devbox', 'local'] },
    branch: { type: 'string' },
    project: { type: 'string' },
    task: { type: 'string', description: 'vitrinka task id the run is bound to' },
    override: { type: 'object', description: 'parsed .claude/vitrinka-workflows.json or {}' },
    projectType: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['baseUrl', 'where', 'branch', 'projectType'],
}

const PUBLISH_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    section: { type: 'string' },
    cards: { type: 'array', items: { type: 'object', properties: { cardId: { type: 'integer' }, route: { type: 'string' }, device: { type: 'string' }, label: { type: 'string' } }, required: ['cardId'] } },
  },
  required: ['boardUrl', 'boardSlug', 'section', 'cards'],
}
// args: { scope: 'idea' | 'app', requirements?: string, project?: string, task?: string, push?: boolean }
const scope = (args && args.scope) || 'app'
const requirements = (args && args.requirements) || ''
const project = (args && args.project) || ''
const task = (args && args.task) || ''
const push = !(args && args.push === false)

const LAYERS = [
  { key: 'routes', ask: 'every route/screen a user can reach: path, title, implementing file, auth needed, how to reach it with data on screen; plus the 3-8 end-to-end journeys a real user walks (title, steps, roles).' },
  { key: 'model', ask: 'the data model and the doors around it: entities, their store/tables, the API/MCP/CLI doors that read and write them, and the ONE door each write is supposed to go through.' },
  { key: 'components', ask: 'the component and design-system layer: shared components, layout shells, tokens/scales, the pattern a new screen is expected to copy, and the places two implementations of one thing already exist.' },
  { key: 'tests', ask: 'the test estate: frameworks in use, where e2e/unit tests live, fixtures and seeds a test can rely on, and what has no coverage.' },
]

const LAYER_SCHEMA = {
  type: 'object',
  properties: {
    layer: { type: 'string' },
    projectType: { type: 'string', enum: ['web', 'expo', 'cli', 'other'] },
    routes: TERRAIN_SCHEMA.properties.routes,
    journeys: TERRAIN_SCHEMA.properties.journeys,
    facts: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, file: { type: 'string' }, note: { type: 'string' } }, required: ['what', 'file'] } },
    extendPoints: TERRAIN_SCHEMA.properties.extendPoints,
    duplicationRisks: TERRAIN_SCHEMA.properties.duplicationRisks,
    openQuestions: TERRAIN_SCHEMA.properties.openQuestions,
  },
  required: ['layer', 'facts'],
}

phase('Explore')
const focus = scope === 'idea'
  ? `The idea under consideration:\n${requirements}\nRead for what this idea would touch, reuse or duplicate — the parts of the system it should EXTEND rather than rebuild.`
  : 'Read for a full review pass of the whole app: completeness matters more than depth — every reachable route counts.'

const layers = (await parallel(LAYERS.map(l => () => agent(withPreamble(
  `Read-only exploration of this repository, layer: ${l.key}.\n${focus}\n\nReport ${l.ask}\nEvery fact names a real repo-relative file. Prefer the repo's own route tables, navigators, generators and docs over guessing from file names. Say what you could not determine as an open question.`
), { label: `explore:${l.key}`, phase: 'Explore', agentType: 'Explore', schema: LAYER_SCHEMA })))).filter(Boolean)

if (!layers.length) throw new Error('map: every explorer failed — nothing to synthesize')
log(`map: ${layers.length}/${LAYERS.length} layers read`)

phase('Synthesize')
const terrain = await agent(withPreamble(
  `Synthesize ONE terrain for scope "${scope}"${project ? ` of project ${project}` : ''} from these layer reports:\n${JSON.stringify(layers)}\n\n` +
  (scope === 'idea' ? `Idea requirements:\n${requirements}\n\n` : '') +
  `Produce: the route inventory (deduplicated, every entry with a file), the journeys, the extend points (where the idea/pass should build on what exists), the duplication risks (an existing thing the idea would re-implement), and the open questions a brainstorm must settle.\n` +
  (push
    ? `Then push it as a vitrinka artifact page titled "Terrain — ${scope === 'idea' ? (requirements.slice(0, 60) || 'idea') : 'app'}" following the vitrinka artifact skill (Skill tool: vitrinka:artifact)${task ? `, attached to task ${task}` : ''}${project ? `, project ${project}` : ''}; the page holds the same content as readable sections with file references. Return the server-returned artifact url as terrainUrl and its board as boardUrl.`
    : 'Do not push anything; return the terrain only.')
), { label: 'terrain', phase: 'Synthesize', schema: TERRAIN_SCHEMA })

if (!terrain) throw new Error('map: synthesis failed')
log(`map: ${terrain.routes.length} routes, ${(terrain.journeys || []).length} journeys, ${(terrain.duplicationRisks || []).length} duplication risks${terrain.terrainUrl ? ' → ' + terrain.terrainUrl : ''}`)
return terrain
