export const meta = {
  name: 'map',
  description: 'Map the terrain an idea or a review pass stands on: routes, model and doors, components, tests — one terrain artifact on the board. In a repo with a uiLoop section it extends the ui-loop screen manifest instead',
  whenToUse: 'Before brainstorming an idea in a big project (scope: idea) or before a full-app review pass (scope: app). make-idea and review-loop call it; run it alone to refresh the map. scope: screens (or scope: app in a repo whose vybava.config.ts carries uiLoop) produces or refreshes the typed ui-loop screen manifest — every route × tab × overlay × state with a recipe — validated by `vybava ui-loop check` and rendered by `vybava ui-loop map`, before a ui-loop review-loop pass.',
  phases: [
    { title: 'Detect', detail: 'ui-loop configured? (scope app/screens only)' },
    { title: 'Explore', detail: 'four readers, one per layer — screens: sequential manifest extenders' },
    { title: 'Synthesize', detail: 'one terrain artifact, extend points, duplication risks' },
    { title: 'Validate', detail: 'screens: vybava ui-loop check, then vybava ui-loop map' },
  ],
}
// Code generated by tools/gen-workflows from workflows-src/flows/map.js. DO NOT EDIT.
// Edit the flow or its lib/ fragments under workflows-src/, then `go run ./tools/gen-workflows`.
// ---- lib/preamble.js — the lines every agent prompt starts with
// Agents already carry the repo's CLAUDE.md; these name only what a
// workflow stage needs beyond it. Keep it to contracts, never procedure —
// procedure is served by the vitrinka server (`docs {topic}`) and the CLI's
// `--help`.
const PREAMBLE = [
  'You are one stage of a vitrinka workflow. Your final text IS the return value: return raw data for the schema, never a human-facing report.',
  'Work in the current checkout (a worktree). Never switch branches, never stash, never touch the main checkout.',
  'Apps and test suites run where the repo\'s CLAUDE.md says — a worktree\'s devbox when one exists (`devbox run -- \'<cmd>\'`), otherwise locally; say which in `problems` when you had to fall back.',
  'Every vitrinka board/task link you return is the server-returned `url`, verbatim — never composed, never shortened.',
  'Browser work: onyx `browser_start(session: $CLAUDE_CODE_SESSION_ID)` first, headless, then playwright; screenshots land in `.vitrinka/mcp/` or the capture root you were given, never the repo root.',
  'When a door refuses (4xx with a diagnosis), apply the corrected call it names once; a second refusal is a `problems` entry, not a workaround.',
].join('\n')

function withPreamble(prompt) {
  return PREAMBLE + '\n\n' + prompt
}
// The runtime journals agent returns. Keep accounting deterministic on replay,
// share the allowance with child workflows, and bound every fan-out to four.
function workflowRun(input = {}, callAgent = agent, callWorkflow = typeof workflow === 'function' ? workflow : null) {
  const supplied = input.agentBudget || { limit: 10, used: 0 }
  const limit = supplied.limit
  let used = supplied.used
  if (!Number.isInteger(limit) || limit < 1 || limit > 10 || !Number.isInteger(used) || used < 0 || used > limit) {
    throw new Error('workflow: agentBudget must have integer limit 1..10 and used 0..limit')
  }
  const remaining = () => limit - used
  const reserve = n => {
    if (n > remaining()) throw new Error(`workflow: agent budget exhausted (${used}/${limit}); continue with the returned next args as a new run`)
  }
  return {
    remaining,
    ensureBudget: reserve,
    async agent(prompt, options) {
      reserve(1)
      used++
      return await callAgent(prompt + '\n\nWork INLINE in this agent. Never spawn subagents, workflows or background agent sessions, including from an invoked skill. The workflow script owns all delegation and the shared budget.', options)
    },
    async workflow(name, args) {
      if (!callWorkflow) throw new Error('workflow: no child-workflow runtime is available')
      const result = await callWorkflow(name, Object.assign({}, args, { agentBudget: { limit, used } }))
      if (!result || !result.agentBudget || result.agentBudget.limit !== limit || !Number.isInteger(result.agentBudget.used) || result.agentBudget.used < used || result.agentBudget.used > limit) {
        throw new Error(`workflow: ${name} returned no valid shared agent-budget receipt`)
      }
      used = result.agentBudget.used
      return result
    },
    async parallel(tasks) {
      reserve(tasks.length)
      const results = []
      for (let i = 0; i < tasks.length; i += 4) results.push(...await parallel(tasks.slice(i, i + 4)))
      return results
    },
    async serial(tasks) {
      reserve(tasks.length)
      const results = []
      for (const task of tasks) results.push(await task())
      return results
    },
    finish(result) { return Object.assign({}, result, { agentBudget: { limit, used } }) },
  }
}

function completionReceipt({ complete = false, problems = [], open = [], unverified = [], evidence = [] } = {}) {
  const blockers = [...problems, ...open.map(x => x.summary || x.title || String(x)), ...unverified.map(x => x.summary || x.title || String(x))]
  const status = complete && !blockers.length && evidence.length ? 'complete' : 'incomplete'
  if (status === 'incomplete' && !blockers.length) blockers.push('stage is unfinished or lacks verification evidence')
  return { v: 1, status, evidence, blockers }
}

function gatePassed(gate) {
  return !!(gate && gate.green && gate.headSha && gate.ran && gate.ran.length && Number.isInteger(gate.testsExecuted) && gate.testsExecuted > 0 && !(gate.failures || []).length)
}

function coverageProblems(routes, matrix, shots, journeys, cases, reviews, walkOnly, cards = []) {
  const problems = []
  if (!walkOnly) {
    for (const device of matrix) for (const route of routes) {
      if (!shots.some(s => s.device === device.name && s.shots.some(x => x.route === route.path))) problems.push(`missing capture: ${device.name} ${route.path}`)
      if (!cards.some(c => c.device === device.name && c.route === route.path)) problems.push(`missing published capture: ${device.name} ${route.path}`)
    }
    const read = new Set(reviews.flatMap(r => r.cardsRead || []))
    if (!cards.length || cards.some(c => !read.has(c.cardId))) problems.push('the reviewer did not read every published card')
  }
  for (const device of matrix) for (const journey of journeys) {
    if (!cases.some(c => c.title === journey.title && c.device === device.name && ['pass', 'fail'].includes(c.verdict))) problems.push(`journey not executed: ${device.name} ${journey.title}`)
  }
  return problems
}
// ---- lib/schemas.js — structured-output schemas shared by the flows
const ROUTE = {
  type: 'object',
  properties: {
    path: { type: 'string' },
    title: { type: 'string' },
    file: { type: 'string', description: 'repo-relative implementing file' },
    auth: { type: 'string', description: 'none | user | admin | <role>' },
    setup: { type: 'string', description: 'how to reach it with data on screen (seed, fixture, deep link)' },
  },
  required: ['path', 'title'],
}

const TERRAIN_SCHEMA = {
  type: 'object',
  properties: {
    projectType: { type: 'string', enum: ['web', 'expo', 'cli', 'other'] },
    routes: { type: 'array', items: ROUTE },
    journeys: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          steps: { type: 'array', items: { type: 'string' } },
          roles: { type: 'array', items: { type: 'string' } },
        },
        required: ['title', 'steps'],
      },
    },
    extendPoints: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, file: { type: 'string' }, why: { type: 'string' } }, required: ['what', 'file'] } },
    duplicationRisks: { type: 'array', items: { type: 'object', properties: { risk: { type: 'string' }, existing: { type: 'string' } }, required: ['risk', 'existing'] } },
    openQuestions: { type: 'array', items: { type: 'string' } },
    terrainUrl: { type: 'string', description: 'server-returned url of the pushed terrain artifact, empty when not pushed' },
    boardUrl: { type: 'string' },
  },
  required: ['projectType', 'routes'],
}

const FINDING = {
  type: 'object',
  properties: {
    key: { type: 'string' },
    id: { type: 'integer', description: 'annotation id from the annotate receipt' },
    cardId: { type: 'integer' },
    route: { type: 'string' },
    device: { type: 'string' },
    area: { type: 'string', description: 'route, component or subsystem the fix lives in' },
    kind: { type: 'string', enum: ['finding', 'suggestion'] },
    severity: { type: 'string', enum: ['blocker', 'major', 'minor'] },
    rule: { type: 'string' },
    summary: { type: 'string' },
    files: { type: 'array', items: { type: 'string' } },
  },
  required: ['key', 'area', 'kind', 'severity', 'summary'],
}

const FINDINGS_SCHEMA = {
  type: 'object',
  properties: {
    findings: { type: 'array', items: FINDING },
    regressions: { type: 'array', items: { type: 'object', properties: { id: { type: 'integer' }, key: { type: 'string' }, fixed: { type: 'boolean' }, note: { type: 'string' } }, required: ['key', 'fixed'] } },
    screensRead: { type: 'integer' },
    cardsRead: { type: 'array', items: { type: 'integer' }, description: 'every cardId whose pixels were read' },
    boardUrl: { type: 'string' },
  },
  required: ['findings', 'cardsRead'],
}

const SHOOT_SCHEMA = {
  type: 'object',
  properties: {
    device: { type: 'string' },
    sourceUnchanged: { type: 'boolean', description: 'tracked and untracked application source matches the prepared HEAD before and after capture' },
    shots: { type: 'array', items: { type: 'object', properties: { route: { type: 'string' }, label: { type: 'string' }, file: { type: 'string' } }, required: ['route', 'label'] } },
    boardUrl: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['device', 'shots', 'sourceUnchanged'],
}

const USERTEST_SCHEMA = {
  type: 'object',
  properties: {
    qaTaskUrl: { type: 'string' },
    boardUrl: { type: 'string' },
    cases: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, device: { type: 'string' }, verdict: { type: 'string', enum: ['pass', 'fail', 'skip'] }, note: { type: 'string' }, files: { type: 'array', items: { type: 'string' } } }, required: ['title', 'device', 'verdict'] } },
    bugs: { type: 'array', items: { type: 'string', description: 'task url of each bug filed' } },
  },
  required: ['cases'],
}

const FIX_SCHEMA = {
  type: 'object',
  properties: {
    fixed: { type: 'array', items: { type: 'string', description: 'finding key' } },
    skipped: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, why: { type: 'string' } }, required: ['key', 'why'] } },
    touchedRoutes: { type: 'array', items: { type: 'string' } },
    touchedFiles: { type: 'array', items: { type: 'string' } },
    commits: { type: 'array', items: { type: 'string' } },
  },
  required: ['fixed', 'skipped', 'touchedRoutes', 'touchedFiles'],
}

const GATE_SCHEMA = {
  type: 'object',
  properties: {
    green: { type: 'boolean' },
    ran: { type: 'array', items: { type: 'string' } },
    failures: { type: 'array', items: { type: 'string' } },
    repaired: { type: 'boolean' },
    testsExecuted: { type: 'integer', minimum: 0, description: 'sum of tests actually executed, read from runner output; never inferred from a success banner' },
    headSha: { type: 'string', description: 'git rev-parse HEAD after every repair and verification' },
  },
  required: ['green', 'ran', 'headSha', 'testsExecuted'],
}

const PREPARE_SCHEMA = {
  type: 'object',
  properties: {
    baseUrl: { type: 'string' },
    where: { type: 'string', enum: ['devbox', 'local'] },
    branch: { type: 'string' },
    headSha: { type: 'string' },
    project: { type: 'string' },
    task: { type: 'string', description: 'vitrinka task id the run is bound to' },
    override: { type: 'object', description: 'parsed .claude/vitrinka-workflows.json or {}' },
    projectType: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['baseUrl', 'where', 'branch', 'headSha', 'projectType'],
}

const PUBLISH_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    section: { type: 'string' },
    cards: { type: 'array', items: { type: 'object', properties: { cardId: { type: 'integer' }, route: { type: 'string' }, device: { type: 'string' }, label: { type: 'string' } }, required: ['cardId', 'route', 'device'] } },
  },
  required: ['boardUrl', 'boardSlug', 'section', 'cards'],
}
// ---- lib/uiloop.js — the ui-loop mode's rules and plain-code decisions (no agents here)
// `vybava ui-loop` (Výbava docs/uiloop.md) owns the deterministic half of the
// UI polish loop: the screen manifest, capture, split/publish, scoreboard.
// The map and review-loop flows own the judgment half and drive it through
// these helpers. A pass is too big for one run (≤ 4 agents a phase, ≤ 10 a
// run), so review-loop runs it as stages that resume from the files the
// previous stage left in the pass directory — nextStage reads them back.

// The operational rules every ui-loop agent carries. Each one cost a real
// incident (Reservine vt-1339, voke); docs/uiloop.md "Operational rules".
const UILOOP_RULES = [
  'You are one agent of a ui-loop stage. Nobody can message you and you message nobody: never SendMessage an agent a running workflow owns. Decide, state the assumption in `problems`, keep going.',
  'DB migrations, reseeds and stack re-wiring are outside your brief: never run one, never recreate a volume or container. A screen that needs data it does not have is reported, not seeded.',
  'Never restart the capture container. A pass cut short (oomd, a usage limit) is finished with `vybava ui-loop run --resume`, never by restarting anything.',
  'An e2e or capture run never leaves seed data changed: back up first (the repo\'s backup script), reach empty/error/loading states with the request mocks in `states.ts`, and run destructive recipes only with `--destructive`.',
  'Keep the shared dev server green: every lane shares one. Fix the provider before its consumer; a red build on your own edit that is not green again within 5 minutes is reverted by you. Never restart a server on a red tree — it comes back with no listener.',
  'One deploy lock and one e2e lock per workspace: take the lock the repo names before a deploy or an e2e run and release it after.',
  'The capture harness shoots on Chrome\'s GPU path (`--enable-gpu --use-angle=swiftshader` in vendor/playwright.config.ts); never drop the flags, or glass is silently missing from every shot.',
  'Owner decisions written in the spec are final — never re-litigate them.',
]

const UILOOP_FIX_RULES = [
  'One item at a time, with a green build between items: the provider before the consumer, the class half before the template half. Commit path-limited (only your files, never `git add -A`, never a bare `git commit`) and never leave your own uncommitted work in the tree.',
  'Never edit a file that holds another lane\'s uncommitted edits. Shared files (i18n, recipes) are edited surgically.',
  'After every item write its checkpoint file (the path you were given) and commit it with the item, so a cutoff loses at most one item. A checkpoint that already says done or skipped means the item is finished — skip it.',
  'After a usage-limit cutoff the successor maps the dirty files to lanes (git status against the checkpoints), commits an in-flight map, and resumes from the first item without a checkpoint.',
  '`cn`/`cx` (tailwind-merge) drop a position or display class beside a recipe that sets one: put layout on a wrapper or extend the recipe. A focus ring follows its control\'s radius; grouped rows take an inset ring.',
]

function withUiLoop(prompt, fix) {
  const rules = fix ? [...UILOOP_RULES, ...UILOOP_FIX_RULES] : UILOOP_RULES
  return 'ui-loop rules:\n- ' + rules.join('\n- ') + '\n\n' + prompt
}

const UILOOP_SEVERITY = { broken: 3, 'needs-work': 2, polish: 1 }
const UILOOP_VERDICT = { 'not-met': 3, partly: 2, met: 1 }

// A backlog finding is open work unless its acceptance was met.
function isOpenItem(f) {
  return f.status !== 'met'
}

// A fresh finding's backlog key: its screen and title, so the same defect
// filed by two reviewers (two viewports of one screen) is one item.
function backlogKey(screen, title) {
  const slug = s => String(s || '').replace(/[^a-z0-9]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase()
  return (slug(screen) + '-' + slug(title)).slice(0, 80).replace(/-+$/, '')
}

// Deterministic reviewer batches: each area's screens, sorted by id, in
// chunks of `size`, in the config's area order. A batch id is stable across
// runs, so a resumed review skips the batches whose raw file exists.
function reviewBatches(screens, areas, size = 14) {
  size = Math.max(1, Math.floor(Number(size)) || 14)
  const order = [...areas, ...uniqAreas(screens).filter(a => !areas.includes(a))]
  const out = []
  for (const area of order) {
    const ids = screens.filter(s => s.area === area).map(s => s.id).sort()
    for (let i = 0; i < ids.length; i += size) out.push({ id: `${area}-${i / size + 1}`, area, screens: ids.slice(i, i + size) })
  }
  return out
}

function uniqAreas(screens) {
  return [...new Set(screens.map(s => s.area))]
}

// The pass's backlog from its reviewers' raw output and the previous pass's
// backlog, in the `vybava ui-loop scoreboard` contract (v1, strict keys).
// A previous open item keeps its key and takes its worst verdict across the
// batches that judged it; one nobody judged stays not-met and is listed in
// `unjudged`. A fresh finding is keyed by screen + title (backlogKey), two
// of them merge (worst severity, unioned viewports/themes/shots/files), and
// one whose key is a previous item's is that item, never a second one. A
// fresh finding missing its title, acceptance or files goes to `problems`
// for the synthesis agent to repair.
function mergeBacklog(pass, previous, raw) {
  const prevOpen = (previous || []).filter(isOpenItem)
  const verdicts = new Map()
  for (const r of raw) for (const a of r.acceptance || []) {
    const cur = verdicts.get(a.key)
    if (!cur || (UILOOP_VERDICT[a.verdict] || 0) > (UILOOP_VERDICT[cur] || 0)) verdicts.set(a.key, a.verdict)
  }
  const out = new Map()
  const unjudged = []
  for (const p of prevOpen) {
    const v = verdicts.get(p.key)
    if (!v) unjudged.push(p.key)
    out.set(p.key, pickBacklog(Object.assign({}, p, { status: v || 'not-met' })))
  }
  const problems = []
  for (const r of raw) for (const f of r.findings || []) {
    if (!f.title || !f.acceptance || !(f.files || []).length) { problems.push(f); continue }
    const k = f.key || backlogKey(f.screen, f.title)
    const cur = out.get(k)
    if (!cur) { out.set(k, pickBacklog(Object.assign({}, f, { key: k, status: 'open' }))); continue }
    if (cur.status !== 'open') continue
    if ((UILOOP_SEVERITY[f.severity] || 0) > (UILOOP_SEVERITY[cur.severity] || 0)) cur.severity = f.severity
    for (const field of ['viewports', 'themes', 'shots', 'files']) {
      const merged = [...new Set([...(cur[field] || []), ...(f[field] || [])])]
      if (merged.length) cur[field] = merged
    }
  }
  return { backlog: { v: 1, pass, findings: [...out.values()] }, unjudged, problems }
}

const BACKLOG_KEYS = ['key', 'screen', 'area', 'severity', 'status', 'title', 'detail', 'files', 'acceptance', 'viewports', 'themes', 'shots', 'refs']

// The backlog contract rejects unknown keys: keep only its own.
function pickBacklog(f) {
  const o = {}
  for (const k of BACKLOG_KEYS) if (f[k] !== undefined && f[k] !== '' && !(Array.isArray(f[k]) && !f[k].length && k !== 'files')) o[k] = f[k]
  if (!o.files) o.files = []
  return o
}

// The fix round's lanes. A finding is a primitive when one of its files sits
// under a `primitives` prefix, is named by findings of two areas, or is
// named by another primitive finding; the
// primitive lanes run first, then the primitive files are frozen and the
// area lanes run. Items linked by a shared file ride one lane (union-find),
// so parallel lanes never edit one file, and lanes are packed to at most
// `max` per phase. Within a lane: worst severity first, carried items
// (not-met, partly) before fresh ones, then key.
function planLanes(findings, primitives = [], max = 4) {
  const open = findings.filter(isOpenItem)
  const fileAreas = new Map()
  for (const f of open) for (const file of f.files || []) {
    if (!fileAreas.has(file)) fileAreas.set(file, new Set())
    fileAreas.get(file).add(f.area)
  }
  const seed = f => (f.files || []).some(file => primitives.some(p => file.startsWith(p)) || fileAreas.get(file).size > 1)
  // Closed over shared files: an item naming any file a primitive item
  // names is a primitive too, or an area lane would edit a frozen file.
  const primSet = new Set(open.filter(seed))
  for (let grew = true; grew;) {
    grew = false
    const primFiles = new Set([...primSet].flatMap(f => f.files || []))
    for (const f of open) if (!primSet.has(f) && (f.files || []).some(file => primFiles.has(file))) { primSet.add(f); grew = true }
  }
  const prim = open.filter(f => primSet.has(f))
  const rest = open.filter(f => !primSet.has(f))
  const frozen = [...new Set(prim.flatMap(f => f.files || []))].sort()
  return {
    frozen,
    primitives: packLanes(prim, f => primitiveFamily(f, primitives), max, 'prim'),
    areas: packLanes(rest, f => f.area, max, 'area'),
  }
}

// A primitive's family: the directory of its first primitive file.
function primitiveFamily(f, primitives) {
  const file = (f.files || []).find(x => primitives.some(p => x.startsWith(p))) || (f.files || [])[0] || f.area
  const parts = file.split('/')
  return parts.length > 1 ? parts[parts.length - 2] : parts[0]
}

function packLanes(items, groupOf, max, prefix) {
  const parent = new Map()
  const find = g => { while (parent.get(g) !== g) g = parent.get(g); return g }
  const union = (a, b) => { const ra = find(a), rb = find(b); if (ra !== rb) parent.set(rb, ra) }
  const fileGroup = new Map()
  for (const f of items) {
    const g = groupOf(f)
    if (!parent.has(g)) parent.set(g, g)
    for (const file of f.files || []) {
      if (fileGroup.has(file)) union(fileGroup.get(file), g); else fileGroup.set(file, g)
    }
  }
  const byRoot = new Map()
  for (const f of items) {
    const r = find(groupOf(f))
    if (!byRoot.has(r)) byRoot.set(r, { groups: new Set(), items: [] })
    byRoot.get(r).groups.add(groupOf(f))
    byRoot.get(r).items.push(f)
  }
  let lanes = [...byRoot.values()].map(l => ({ groups: [...l.groups].sort(), items: l.items }))
  lanes.sort((a, b) => b.items.length - a.items.length || a.groups[0].localeCompare(b.groups[0]))
  while (lanes.length > max) {
    const tail = lanes.pop()
    const last = lanes[lanes.length - 1]
    last.groups.push(...tail.groups)
    last.items.push(...tail.items)
  }
  return lanes.map(l => ({ lane: `${prefix}-${l.groups.join('+')}`.slice(0, 60), items: orderItems(l.items) }))
}

function orderItems(items) {
  const carried = f => (f.status === 'open' ? 0 : 1)
  return [...items].sort((a, b) =>
    (UILOOP_SEVERITY[b.severity] || 0) - (UILOOP_SEVERITY[a.severity] || 0) || carried(b) - carried(a) || a.key.localeCompare(b.key))
}

// A checkpoint that finishes its item for this round: done, skipped (with
// why), or blocked on a primitive change the frozen API refused — a blocked
// item stays open in the backlog and returns in the next pass's round.
function finishedKeys(checkpoints) {
  return new Set((checkpoints || []).filter(c => c.status === 'done' || c.status === 'skipped' || c.status === 'blocked').map(c => c.key))
}

// A lane's items still to do: every item without a finishing checkpoint. A
// lane with none left is dropped, so a resumed round relaunches only
// unfinished lanes, each from its first open item.
function remainingLanes(lanes, checkpoints) {
  const finished = finishedKeys(checkpoints)
  return lanes.map(l => ({ lane: l.lane, items: l.items.filter(f => !finished.has(f.key)) })).filter(l => l.items.length)
}

// The checkpoint file of one item.
function checkpointPath(passDir, key) {
  return `${passDir}/fix/${key}.json`
}

// The next pass's `--only`: the screens a fix touched plus every screen an
// open backlog item names, so the verify pass judges each fix and each
// item still open.
function verifySelection(findings, checkpoints) {
  const touched = (checkpoints || []).filter(c => c.status === 'done').flatMap(c => c.screens || [])
  const open = (findings || []).filter(isOpenItem).map(f => f.screen)
  return [...new Set([...touched, ...open].filter(Boolean))].sort()
}

// Which stage a pass is at, read back from the files its stages left:
// capture (no shots, or shots not yet published — then resume), review
// (published, some area unreviewed), fix (open items without a checkpoint),
// verify (the round is checkpointed and something was fixed), done (no open
// item, or the cap is reached). `s` is the Prepare agent's report.
function nextStage(s, cap = 6) {
  if (!s.pass || !s.shots) return { stage: 'capture', resume: false, reason: 'no pass with shots yet' }
  if (!s.published) return { stage: 'capture', resume: true, reason: `pass ${s.pass} has shots that are not published` }
  const unreviewed = (s.areas || []).filter(a => !(s.reviewedAreas || []).includes(a))
  if (!s.backlog || unreviewed.length) return { stage: 'review', resume: !!s.backlog, reason: unreviewed.length ? `areas not reviewed: ${unreviewed.join(', ')}` : 'no backlog yet' }
  const open = s.backlog.filter(isOpenItem)
  if (!open.length) return { stage: 'done', resume: false, reason: `pass ${s.pass} backlog has no open item — converged` }
  const finished = finishedKeys(s.checkpoints)
  const todo = open.filter(f => !finished.has(f.key))
  if (todo.length) return { stage: 'fix', resume: finished.size > 0, reason: `${todo.length} of ${open.length} open items without a checkpoint` }
  if (s.pass >= cap) return { stage: 'done', resume: false, reason: `cap of ${cap} passes reached with ${open.length} items open` }
  if (!(s.checkpoints || []).some(c => c.status === 'done')) return { stage: 'done', resume: false, reason: 'the fix round fixed nothing — the open items need a human' }
  return { stage: 'verify', resume: false, reason: `fix round of pass ${s.pass} is checkpointed` }
}
// ---- lib/uiloop-schemas.js — the ui-loop mode's detect prompt and structured-output schemas
// The ui-loop mode runs when the repo's vybava.config.ts carries a `uiLoop`
// section. A script cannot read files, so one low-effort agent answers.
const UILOOP_DETECT_PROMPT =
  'Read-only: does this repo drive the Výbava ui-loop applet? Run `vybava ui-loop check --json --no-ts` from the repo root. ' +
  'A CONFIG_MISSING diagnostic (or no vybava.config.ts, or no `vybava` binary) means configured=false — say which in reason. ' +
  'Otherwise configured=true: read the uiLoop section with `vybava config show --json` and return dir, out, spec, appMap, areas (in config order), the app names and vitrinka {project, boardPrefix}. Change nothing.'

const UILOOP_CONFIG = {
  type: 'object',
  properties: {
    dir: { type: 'string' },
    out: { type: 'string' },
    spec: { type: 'string' },
    appMap: { type: 'string' },
    areas: { type: 'array', items: { type: 'string' } },
    apps: { type: 'array', items: { type: 'string' } },
    project: { type: 'string', description: 'uiLoop.vitrinka.project' },
    boardPrefix: { type: 'string', description: 'uiLoop.vitrinka.boardPrefix' },
  },
  required: ['dir', 'out', 'areas', 'apps'],
}

const UILOOP_DETECT_SCHEMA = {
  type: 'object',
  properties: { configured: { type: 'boolean' }, reason: { type: 'string' }, config: UILOOP_CONFIG },
  required: ['configured'],
}

const UILOOP_ITEM = {
  type: 'object',
  description: 'one backlog finding in the `vybava ui-loop scoreboard` contract (docs/uiloop.md)',
  properties: {
    key: { type: 'string' }, screen: { type: 'string' }, area: { type: 'string' },
    severity: { type: 'string', enum: ['broken', 'needs-work', 'polish'] },
    status: { type: 'string', enum: ['open', 'met', 'partly', 'not-met'] },
    title: { type: 'string' }, detail: { type: 'string' }, acceptance: { type: 'string' },
    files: { type: 'array', items: { type: 'string' } },
    viewports: { type: 'array', items: { type: 'string' } },
    themes: { type: 'array', items: { type: 'string' } },
    shots: { type: 'array', items: { type: 'string' } },
    refs: { type: 'array', items: { type: 'string' } },
  },
  required: ['key', 'screen', 'area', 'severity', 'status', 'title', 'acceptance', 'files'],
}

const UILOOP_CHECKPOINT = {
  type: 'object',
  properties: {
    key: { type: 'string' },
    lane: { type: 'string' },
    basis: { type: 'string' },
    valid: { type: 'boolean', description: 'commit is an ancestor of HEAD and the recorded fix is still present' },
    status: { type: 'string', enum: ['done', 'skipped', 'blocked'] },
    commit: { type: 'string' },
    screens: { type: 'array', items: { type: 'string' } },
    note: { type: 'string' },
  },
  required: ['key', 'status'],
}

const UILOOP_RAW = {
  type: 'object',
  properties: {
    batch: { type: 'string' },
    basis: { type: 'string' },
    area: { type: 'string' },
    findings: { type: 'array', items: { type: 'object' } },
    acceptance: { type: 'array', items: { type: 'object' } },
    screensRead: { type: 'array', items: { type: 'string' } },
    unreviewed: { type: 'array', items: { type: 'string' } },
  },
  required: ['batch', 'area', 'basis', 'screensRead'],
}

const UILOOP_PREP_SCHEMA = {
  type: 'object',
  properties: {
    configured: { type: 'boolean' },
    branch: { type: 'string' },
    config: UILOOP_CONFIG,
    headSha: { type: 'string' },
    capturedHeadSha: { type: 'string', description: 'capture.json revision, empty for legacy passes' },
    sourceUnchanged: { type: 'boolean', description: 'application tree matches captured revision, including uncommitted changes' },
    reviewBasis: { type: 'string', description: 'SHA256 of sorted pass capture files, manifest and spec contents; empty only without a pass' },
    backlogBasis: { type: 'string' },
    workspace: { type: 'string', description: 'the devbox workspace name from `devbox url --json`, empty when none' },
    pass: { type: 'integer', description: 'the pass inspected; 0 when <out> holds none' },
    passDir: { type: 'string' },
    shots: { type: 'integer', description: 'shot records under <passDir>/shots' },
    published: { type: 'boolean', description: 'publish/index.json exists and every set in plan.json is pushed with no refused captures' },
    screens: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, area: { type: 'string' } }, required: ['id', 'area'] } },
    reviewedAreas: { type: 'array', items: { type: 'string' }, description: 'areas every batch of which has a raw review file' },
    raw: { type: 'array', items: UILOOP_RAW, description: 'every <passDir>/review/raw/*.json, verbatim' },
    hasBacklog: { type: 'boolean', description: '<passDir>/review/backlog.json exists' },
    backlog: { type: 'array', items: UILOOP_ITEM, description: 'its findings, [] when absent' },
    previousBacklog: { type: 'array', items: UILOOP_ITEM, description: 'the findings of the newest earlier pass that has a backlog, [] when none' },
    checkpoints: { type: 'array', items: UILOOP_CHECKPOINT, description: 'every <passDir>/fix/*.json' },
    boards: { type: 'array', description: 'the area set boards of publish/boards.json', items: { type: 'object', properties: { area: { type: 'string' }, url: { type: 'string' } }, required: ['area', 'url'] } },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['configured', 'branch', 'headSha', 'capturedHeadSha', 'sourceUnchanged', 'reviewBasis', 'pass', 'shots', 'published'],
}

const UILOOP_CAPTURE_SCHEMA = {
  type: 'object',
  properties: {
    pass: { type: 'integer' },
    passDir: { type: 'string' },
    shots: { type: 'integer' },
    capturedHeadSha: { type: 'string' },
    sourceUnchanged: { type: 'boolean' },
    byStatus: { type: 'object' },
    published: { type: 'boolean' },
    sets: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, area: { type: 'string' }, url: { type: 'string' }, status: { type: 'string' } }, required: ['key', 'status'] } },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['pass', 'shots', 'published', 'capturedHeadSha', 'sourceUnchanged'],
}

const UILOOP_BOARDS_SCHEMA = {
  type: 'object',
  properties: {
    boards: { type: 'array', description: 'one row per area: its set board, never a new board', items: { type: 'object', properties: { area: { type: 'string' }, url: { type: 'string', description: 'the set board url, server-returned' }, slug: { type: 'string', description: 'the set board slug' }, section: { type: 'string', description: 'the title of this pass\'s first section' } }, required: ['area', 'url'] } },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['boards'],
}

const UILOOP_REVIEW_SCHEMA = {
  type: 'object',
  properties: {
    batch: { type: 'string' },
    basis: { type: 'string' },
    screensRead: { type: 'array', items: { type: 'string' } },
    area: { type: 'string' },
    findings: {
      type: 'array',
      items: {
        type: 'object',
        properties: Object.assign({}, UILOOP_ITEM.properties, { systemic: { type: 'boolean', description: 'a shared primitive or token is the cause' } }),
        required: ['screen', 'area', 'severity', 'title', 'acceptance', 'files'],
      },
    },
    acceptance: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, screen: { type: 'string' }, verdict: { type: 'string', enum: ['met', 'partly', 'not-met'] }, note: { type: 'string' } }, required: ['key', 'verdict'] } },
    unreviewed: { type: 'array', items: { type: 'string' } },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['batch', 'area', 'basis', 'screensRead', 'findings', 'acceptance'],
}

const UILOOP_SYNTH_SCHEMA = {
  type: 'object',
  properties: {
    backlogFile: { type: 'string' },
    findings: { type: 'integer' },
    open: { type: 'integer', description: 'findings whose status is not met' },
    merged: { type: 'integer', description: 'items folded into another as one root cause' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['backlogFile', 'findings', 'open'],
}

const UILOOP_SCORE_SCHEMA = {
  type: 'object',
  properties: {
    scoreboardFile: { type: 'string' },
    totals: { type: 'object' },
    posted: { type: 'array', items: { type: 'object', properties: { area: { type: 'string' }, url: { type: 'string' } }, required: ['area', 'url'] } },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['scoreboardFile', 'posted'],
}

const UILOOP_LANE_SCHEMA = {
  type: 'object',
  properties: {
    lane: { type: 'string' },
    done: { type: 'array', items: { type: 'string' } },
    skipped: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, why: { type: 'string' } }, required: ['key', 'why'] } },
    blocked: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, ask: { type: 'string', description: 'the exact primitive change it needs' } }, required: ['key', 'ask'] } },
    commits: { type: 'array', items: { type: 'string' } },
    touchedScreens: { type: 'array', items: { type: 'string' } },
    apiChanges: { type: 'array', items: { type: 'string' }, description: 'primitive lanes: every public API addition, additive only' },
    treeCleanOfMine: { type: 'boolean' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['lane', 'done', 'skipped', 'commits', 'treeCleanOfMine'],
}

const UILOOP_MANIFEST_SCHEMA = {
  type: 'object',
  properties: {
    areas: { type: 'array', items: { type: 'string' } },
    files: { type: 'array', items: { type: 'string' } },
    before: { type: 'integer', description: 'screens in these areas before you started' },
    added: { type: 'integer' },
    unreachable: { type: 'array', items: { type: 'string' }, description: 'screens added with `unreachable`, each with why' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['areas', 'files', 'added'],
}

const UILOOP_MAP_SCHEMA = {
  type: 'object',
  properties: {
    ok: { type: 'boolean', description: '`vybava ui-loop check --json` ends ok' },
    screens: { type: 'integer' },
    captures: { type: 'integer' },
    perArea: { type: 'array', items: { type: 'object', properties: { area: { type: 'string' }, screens: { type: 'integer' } }, required: ['area', 'screens'] } },
    appMap: { type: 'string' },
    commit: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['ok', 'screens', 'appMap'],
}
// args: { scope: 'idea' | 'app' | 'screens', requirements?: string, project?: string, task?: string, push?: boolean,
//         screens?: false (scope app: never switch to the manifest — the terrain is wanted), areas?: string[] (screens: only these),
//         commit?: boolean (screens: commit the manifest and app map, default true) }
const run = workflowRun(args || {})
const scope = (args && args.scope) || 'app'
const requirements = (args && args.requirements) || ''
const project = (args && args.project) || ''
const task = (args && args.task) || ''
const push = !(args && args.push === false)

if (scope === 'screens' || (scope === 'app' && !(args && args.screens === false))) {
  phase('Detect')
  const detected = await run.agent(withPreamble(UILOOP_DETECT_PROMPT), { label: 'detect', phase: 'Detect', effort: 'low', schema: UILOOP_DETECT_SCHEMA })
  if (detected && detected.configured) return await mapScreens(detected.config)
  if (scope === 'screens') throw new Error(`map: scope screens needs a uiLoop section in vybava.config.ts (${(detected && detected.reason) || 'detect failed'}) — \`vybava ui-loop init\` scaffolds it`)
  log(`map: no ui-loop here (${(detected && detected.reason) || 'detect failed'}); mapping the terrain`)
}

// The ui-loop screen manifest (Výbava docs/uiloop.md "The manifest
// contract"): explorers EXTEND <dir>/screens/<area>.ts, one area group each,
// so no two write one file; one validator checks and renders the app map.
// ≤ 4 sequential extenders + Detect + Validate = 6 agents a run.
async function mapScreens(cfg) {
  const want = args && args.areas ? [].concat(args.areas) : []
  const areas = (cfg.areas || []).filter(a => !want.length || want.includes(a))
  if (!areas.length) throw new Error(`map: no uiLoop area to map${want.length ? ` among ${want.join(', ')}` : ''}`)
  const writers = Math.min(4, run.remaining() - 1)
  if (writers < 1) throw new Error('map: no agent budget for a manifest writer and validator')
  const per = Math.ceil(areas.length / writers)
  const groups = []
  for (let i = 0; i < areas.length; i += per) groups.push(areas.slice(i, i + per))
  const explorer = g => () => run.agent(withPreamble(withUiLoop(
    `Extend the ui-loop screen manifest for area${g.length > 1 ? 's' : ''} ${g.join(', ')} (apps: ${cfg.apps.join(', ')}).\n` +
    `The API is \`${cfg.dir}/vendor/manifest.ts\` + \`${cfg.dir}/vendor/project.ts\` (defineScreens, Screen, Step, Recipe) and \`${cfg.dir}/vendor/states.ts\`; the repo's hooks are \`${cfg.dir}/project.ts\`. Your files: ${JSON.stringify(g.map(a => `${cfg.dir}/screens/${a}.ts`))} — a missing one is created in the style of its siblings; never write any other area's file.\n` +
    `Inventory the area from the app's own route tables, navigators and components: every route × tab × overlay (dialog, drawer, menu, popover, phone sheet, stacked layer) × state — empty / error / loading through the \`states.ts\` request mocks (\`listStates\` for a list), unsaved changes, a validation error, denied and read-only personas (\`as\`). Add a Screen for each one the manifest lacks, with the recipe that reaches it (\`before\` mocks, \`open\` steps ending in a wait, \`ready\`), \`sourceFiles\` that exist, \`parentId\`/\`variantOf\` for overlays and states, \`app\` when there are several apps. One that cannot be reached with the seed data gets \`unreachable: '<why>'\`; one whose recipe writes gets \`destructive: true\`.\n` +
    `EXTEND ONLY: never delete, rename, reorder or rewrite an existing entry — one you believe wrong is a problems line naming its id. Run \`vybava ui-loop check --json\` and fix what it reports in the entries you added. You are the ONLY writer while this group runs; other groups run sequentially. Never run a capture, never commit.\n` +
    `Return your areas, files, the screen count before, how many you added and the unreachable ones with why.`
  )), { label: `screens:${g.join('+')}`, phase: 'Explore', schema: UILOOP_MANIFEST_SCHEMA })
  phase('Explore')
  run.ensureBudget(groups.length + 1)
  const reports = (await run.serial(groups.map(explorer))).filter(Boolean)
  const covered = new Set(reports.flatMap(r => r.areas))
  const missed = areas.filter(a => !covered.has(a))
  log(`map: ${reports.reduce((n, r) => n + r.added, 0)} screens added across ${covered.size}/${areas.length} areas${missed.length ? `; explorers failed for ${missed.join(', ')}` : ''}`)

  phase('Validate')
  const commit = !(args && args.commit === false)
  const result = await run.agent(withPreamble(withUiLoop(
    `Validate the ui-loop screen manifest the explorers just extended (${JSON.stringify(reports.map(r => ({ areas: r.areas, files: r.files, added: r.added, problems: r.problems || [] })))}).\n` +
    `1. \`vybava ui-loop check --json\`: fix every MANIFEST_INVALID problem in the newly added entries (the diff against HEAD shows which); an existing entry's problem is reported, not rewritten.\n` +
    `2. \`vybava ui-loop map\` renders \`${cfg.appMap || 'uiLoop.appMap'}\`; \`vybava ui-loop check --json\` again must report the app map fresh.\n` +
    (commit ? `3. Commit ${cfg.dir}/screens/ and the app map path-limited ("ui-loop: map screens (${areas.join(', ')})").\n` : '3. Do not commit.\n') +
    `Return ok, the screen and capture counts, screens per area, the app map path${commit ? ', the commit' : ''} and every problem left.`
  )), { label: 'validate', phase: 'Validate', schema: UILOOP_MAP_SCHEMA })
  if (!result) throw new Error('map: validating the screen manifest failed — run `vybava ui-loop check --json`')
  const problems = [...reports.flatMap(r => r.problems || []), ...(result.problems || []), ...missed.map(a => `area ${a}: its explorer failed — rerun map with areas: ["${a}"]`)]
  return run.finish({ scope: 'screens', ok: result.ok, screens: result.screens, captures: result.captures || 0, perArea: result.perArea || [], appMap: result.appMap, commit: result.commit || '', added: reports.reduce((n, r) => n + r.added, 0), unreachable: reports.flatMap(r => r.unreachable || []), problems, receipt: completionReceipt({ complete: result.ok, problems, evidence: result.ok ? [{ appMap: result.appMap, screens: result.screens }] : [] }) })
}

const LAYERS = [
  { key: 'routes', ask: 'every route/screen a user can reach: path, title, implementing file, auth needed, how to reach it with data on screen; plus the 3-8 end-to-end journeys a real user walks (title, steps, roles).' },
  { key: 'model', ask: 'the data model and the doors around it: entities, their store/tables, the API/MCP/CLI doors that read and write them, and the ONE door each write is supposed to go through.' },
  { key: 'components', ask: 'the component and design-system layer: shared components, layout shells, tokens/scales, the pattern a new screen is expected to copy, and the places two implementations of one thing already exist.' },
  { key: 'tests', ask: 'the test estate: frameworks in use, where e2e/unit tests live, fixtures and seeds a test can rely on, and what has no coverage.' },
]

const LAYER_SCHEMA = {
  type: 'object',
  properties: {
    layer: { type: 'string' },
    projectType: { type: 'string', enum: ['web', 'expo', 'cli', 'other'] },
    routes: TERRAIN_SCHEMA.properties.routes,
    journeys: TERRAIN_SCHEMA.properties.journeys,
    facts: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, file: { type: 'string' }, note: { type: 'string' } }, required: ['what', 'file'] } },
    extendPoints: TERRAIN_SCHEMA.properties.extendPoints,
    duplicationRisks: TERRAIN_SCHEMA.properties.duplicationRisks,
    openQuestions: TERRAIN_SCHEMA.properties.openQuestions,
  },
  required: ['layer', 'facts'],
}

run.ensureBudget(LAYERS.length + 1)
phase('Explore')
const focus = scope === 'idea'
  ? `The idea under consideration:\n${requirements}\nRead for what this idea would touch, reuse or duplicate — the parts of the system it should EXTEND rather than rebuild.`
  : 'Read for a full review pass of the whole app: completeness matters more than depth — every reachable route counts.'

const layers = (await run.parallel(LAYERS.map(l => () => run.agent(withPreamble(
  `Read-only exploration of this repository, layer: ${l.key}.\n${focus}\n\nReport ${l.ask}\nEvery fact names a real repo-relative file. Prefer the repo's own route tables, navigators, generators and docs over guessing from file names. Say what you could not determine as an open question.`
), { label: `explore:${l.key}`, phase: 'Explore', agentType: 'Explore', schema: LAYER_SCHEMA })))).filter(Boolean)

if (!layers.length) throw new Error('map: every explorer failed — nothing to synthesize')
log(`map: ${layers.length}/${LAYERS.length} layers read`)

phase('Synthesize')
const terrain = await run.agent(withPreamble(
  `Synthesize ONE terrain for scope "${scope}"${project ? ` of project ${project}` : ''} from these layer reports:\n${JSON.stringify(layers)}\n\n` +
  (scope === 'idea' ? `Idea requirements:\n${requirements}\n\n` : '') +
  `Produce: the route inventory (deduplicated, every entry with a file), the journeys, the extend points (where the idea/pass should build on what exists), the duplication risks (an existing thing the idea would re-implement), and the open questions a brainstorm must settle.\n` +
  (push
    ? `Then push it as a vitrinka artifact page titled "Terrain — ${scope === 'idea' ? (requirements.slice(0, 60) || 'idea') : 'app'}" following the vitrinka artifact skill (Skill tool: vitrinka:artifact)${task ? `, attached to task ${task}` : ''}${project ? `, project ${project}` : ''}; the page holds the same content as readable sections with file references. Return the server-returned artifact url as terrainUrl and its board as boardUrl.`
    : 'Do not push anything; return the terrain only.')
), { label: 'terrain', phase: 'Synthesize', schema: TERRAIN_SCHEMA })

if (!terrain) throw new Error('map: synthesis failed')
log(`map: ${terrain.routes.length} routes, ${(terrain.journeys || []).length} journeys, ${(terrain.duplicationRisks || []).length} duplication risks${terrain.terrainUrl ? ' → ' + terrain.terrainUrl : ''}`)
const missing = LAYERS.filter(l => !layers.some(r => r.layer === l.key)).map(l => `missing terrain layer: ${l.key}`)
return run.finish(Object.assign({}, terrain, { receipt: completionReceipt({ complete: !missing.length, problems: missing, evidence: [{ layers: layers.map(r => r.layer), terrainUrl: terrain.terrainUrl || '' }] }) }))
