export const meta = {
  name: 'review-loop',
  description: 'Shoot every route on every device, review the board, fix what it files, reshoot what changed — until a pass is clean or the cap is hit',
  whenToUse: 'A responsivity or UX pass over an app surface, or the verify stage of build-idea. Unattended: findings at or above the severity threshold are accepted and fixed; the rest stay staged on the board.',
  phases: [
    { title: 'Prepare', detail: 'branch, app, matrix, task binding' },
    { title: 'Map', detail: 'route inventory and journeys (skipped when passed in)' },
    { title: 'Pass', detail: 'shoot ∥ usertest → publish → review → accept → fix → gate' },
  ],
}
// Code generated by tools/gen-workflows from workflows-src/flows/review-loop.js. DO NOT EDIT.
// Edit the flow or its lib/ fragments under workflows-src/, then `go run ./tools/gen-workflows`.
// ---- lib/preamble.js — the lines every agent prompt starts with
// Agents already carry the repo's CLAUDE.md; these name only what a
// workflow stage needs beyond it. Keep it to contracts, never procedure —
// procedure is served by the vitrinka server (`docs {topic}`) and the CLI's
// `--help`.
const PREAMBLE = [
  'You are one stage of a vitrinka workflow. Your final text IS the return value: return raw data for the schema, never a human-facing report.',
  'Work in the current checkout (a worktree). Never switch branches, never stash, never touch the main checkout.',
  'Apps and test suites run where the repo\'s CLAUDE.md says — a worktree\'s devbox when one exists (`devbox run -- \'<cmd>\'`), otherwise locally; say which in `problems` when you had to fall back.',
  'Every vitrinka board/task link you return is the server-returned `url`, verbatim — never composed, never shortened.',
  'Browser work: onyx `browser_start(session: $CLAUDE_CODE_SESSION_ID)` first, headless, then playwright; screenshots land in `.vitrinka/mcp/` or the capture root you were given, never the repo root.',
  'When a door refuses (4xx with a diagnosis), apply the corrected call it names once; a second refusal is a `problems` entry, not a workaround.',
].join('\n')

function withPreamble(prompt) {
  return PREAMBLE + '\n\n' + prompt
}
// ---- lib/schemas.js — structured-output schemas shared by the flows
const ROUTE = {
  type: 'object',
  properties: {
    path: { type: 'string' },
    title: { type: 'string' },
    file: { type: 'string', description: 'repo-relative implementing file' },
    auth: { type: 'string', description: 'none | user | admin | <role>' },
    setup: { type: 'string', description: 'how to reach it with data on screen (seed, fixture, deep link)' },
  },
  required: ['path', 'title'],
}

const TERRAIN_SCHEMA = {
  type: 'object',
  properties: {
    projectType: { type: 'string', enum: ['web', 'expo', 'cli', 'other'] },
    routes: { type: 'array', items: ROUTE },
    journeys: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          steps: { type: 'array', items: { type: 'string' } },
          roles: { type: 'array', items: { type: 'string' } },
        },
        required: ['title', 'steps'],
      },
    },
    extendPoints: { type: 'array', items: { type: 'object', properties: { what: { type: 'string' }, file: { type: 'string' }, why: { type: 'string' } }, required: ['what', 'file'] } },
    duplicationRisks: { type: 'array', items: { type: 'object', properties: { risk: { type: 'string' }, existing: { type: 'string' } }, required: ['risk', 'existing'] } },
    openQuestions: { type: 'array', items: { type: 'string' } },
    terrainUrl: { type: 'string', description: 'server-returned url of the pushed terrain artifact, empty when not pushed' },
    boardUrl: { type: 'string' },
  },
  required: ['projectType', 'routes'],
}

const FINDING = {
  type: 'object',
  properties: {
    key: { type: 'string' },
    id: { type: 'integer', description: 'annotation id from the annotate receipt' },
    cardId: { type: 'integer' },
    route: { type: 'string' },
    device: { type: 'string' },
    area: { type: 'string', description: 'route, component or subsystem the fix lives in' },
    kind: { type: 'string', enum: ['finding', 'suggestion'] },
    severity: { type: 'string', enum: ['blocker', 'major', 'minor'] },
    rule: { type: 'string' },
    summary: { type: 'string' },
    files: { type: 'array', items: { type: 'string' } },
  },
  required: ['key', 'area', 'kind', 'severity', 'summary'],
}

const FINDINGS_SCHEMA = {
  type: 'object',
  properties: {
    findings: { type: 'array', items: FINDING },
    regressions: { type: 'array', items: { type: 'object', properties: { id: { type: 'integer' }, key: { type: 'string' }, fixed: { type: 'boolean' }, note: { type: 'string' } }, required: ['key', 'fixed'] } },
    screensRead: { type: 'integer' },
    boardUrl: { type: 'string' },
  },
  required: ['findings'],
}

const SHOOT_SCHEMA = {
  type: 'object',
  properties: {
    device: { type: 'string' },
    shots: { type: 'array', items: { type: 'object', properties: { route: { type: 'string' }, label: { type: 'string' }, file: { type: 'string' } }, required: ['route', 'label'] } },
    boardUrl: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['device', 'shots'],
}

const USERTEST_SCHEMA = {
  type: 'object',
  properties: {
    qaTaskUrl: { type: 'string' },
    boardUrl: { type: 'string' },
    cases: { type: 'array', items: { type: 'object', properties: { title: { type: 'string' }, device: { type: 'string' }, verdict: { type: 'string', enum: ['pass', 'fail', 'skip'] }, note: { type: 'string' }, files: { type: 'array', items: { type: 'string' } } }, required: ['title', 'verdict'] } },
    bugs: { type: 'array', items: { type: 'string', description: 'task url of each bug filed' } },
  },
  required: ['cases'],
}

const FIX_SCHEMA = {
  type: 'object',
  properties: {
    fixed: { type: 'array', items: { type: 'string', description: 'finding key' } },
    skipped: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, why: { type: 'string' } }, required: ['key', 'why'] } },
    touchedRoutes: { type: 'array', items: { type: 'string' } },
    touchedFiles: { type: 'array', items: { type: 'string' } },
    commits: { type: 'array', items: { type: 'string' } },
  },
  required: ['fixed', 'skipped', 'touchedRoutes', 'touchedFiles'],
}

const GATE_SCHEMA = {
  type: 'object',
  properties: {
    green: { type: 'boolean' },
    ran: { type: 'array', items: { type: 'string' } },
    failures: { type: 'array', items: { type: 'string' } },
    repaired: { type: 'boolean' },
  },
  required: ['green', 'ran'],
}

const PREPARE_SCHEMA = {
  type: 'object',
  properties: {
    baseUrl: { type: 'string' },
    where: { type: 'string', enum: ['devbox', 'local'] },
    branch: { type: 'string' },
    project: { type: 'string' },
    task: { type: 'string', description: 'vitrinka task id the run is bound to' },
    override: { type: 'object', description: 'parsed .claude/vitrinka-workflows.json or {}' },
    projectType: { type: 'string' },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['baseUrl', 'where', 'branch', 'projectType'],
}

const PUBLISH_SCHEMA = {
  type: 'object',
  properties: {
    boardUrl: { type: 'string' },
    boardSlug: { type: 'string' },
    section: { type: 'string' },
    cards: { type: 'array', items: { type: 'object', properties: { cardId: { type: 'integer' }, route: { type: 'string' }, device: { type: 'string' }, label: { type: 'string' } }, required: ['cardId'] } },
  },
  required: ['boardUrl', 'boardSlug', 'section', 'cards'],
}
// ---- lib/matrix.js — device matrix and review checklist defaults per project type
// A repo overrides any of these in `.claude/vitrinka-workflows.json`
// ({projectType, matrix, checklist, exclude, baseUrl}); the Prepare agent
// reads that file and the flow merges it over these defaults.
const MATRIX = {
  web: [
    { name: 'iphone', width: 390, height: 844, scale: 3, input: 'touch', mobile: true, safeArea: true },
    { name: 'ipad', width: 1024, height: 768, scale: 2, input: 'touch', mobile: true, safeArea: false },
    { name: 'desktop', width: 1440, height: 810, scale: 2, input: 'mouse', mobile: false, safeArea: false },
  ],
  expo: [
    { name: 'iphone', platform: 'ios', sim: 'iPhone 16', input: 'touch', mobile: true, safeArea: true },
    { name: 'android', platform: 'android', sim: 'Pixel 8', input: 'touch', mobile: true, safeArea: true },
  ],
  cli: [],
}

const CHECKLIST = {
  web: [
    'grid: every edge, gap and control size sits on the 4pt grid',
    'overflow: no text clipped, ellipsised by accident, or overlapping its neighbour at long strings',
    'scroll: no horizontal scrolling at any viewport in the matrix',
    'safe-area: content and fixed bars respect the device safe-area insets (notch, home indicator)',
    'touch: tap targets ≥ 44×44 on touch devices, hover-only affordances have a touch path',
    'navigation: current location is visible, back always works, no dead-end screen',
    'controls: the same action looks and behaves the same on every screen; destructive actions confirm',
    'states: empty, loading, error and long-content states render without layout breaks',
  ],
  expo: [
    'safe-area: content respects notches, home indicator and the keyboard',
    'touch: tap targets ≥ 44×44, gestures do not fight the navigator',
    'navigation: tab and stack state survive a background/foreground cycle',
    'states: empty, loading, error and offline states render without layout breaks',
  ],
  cli: [],
}

function resolveMatrix(projectType, override) {
  const type = (override && override.projectType) || projectType || 'web'
  const matrix = (override && override.matrix) || MATRIX[type] || MATRIX.web
  const checklist = (override && override.checklist) || CHECKLIST[type] || CHECKLIST.web
  return { type, matrix, checklist, exclude: (override && override.exclude) || [] }
}
// ---- lib/helpers.js — plain-code helpers shared by the flows (no agents here)
const SEVERITY_RANK = { blocker: 3, major: 2, minor: 1 }

// Findings the loop fixes on its own: defects at or above the threshold.
// Suggestions and anything below stay staged on the board for the human.
function autoAcceptable(findings, threshold) {
  const min = SEVERITY_RANK[threshold] || SEVERITY_RANK.minor
  return findings.filter(f => f.kind === 'finding' && (SEVERITY_RANK[f.severity] || 0) >= min)
}

// Group findings by area into at most `max` disjoint fix lists. A finding
// whose files also appear in another area is `shared` and runs first, so
// the parallel fixers never edit the same file.
function groupByArea(findings, max) {
  const byArea = new Map()
  for (const f of findings) {
    const area = f.area || 'misc'
    if (!byArea.has(area)) byArea.set(area, [])
    byArea.get(area).push(f)
  }
  const fileOwners = new Map()
  for (const [area, list] of byArea) {
    for (const f of list) for (const file of f.files || []) {
      if (!fileOwners.has(file)) fileOwners.set(file, new Set())
      fileOwners.get(file).add(area)
    }
  }
  const shared = []
  for (const [area, list] of byArea) {
    const keep = []
    for (const f of list) {
      const crosses = (f.files || []).some(file => fileOwners.get(file).size > 1)
      if (crosses) shared.push(f); else keep.push(f)
    }
    byArea.set(area, keep)
  }
  let groups = [...byArea].filter(([, l]) => l.length).map(([area, list]) => ({ area, findings: list }))
  groups.sort((a, b) => b.findings.length - a.findings.length)
  while (groups.length > max) {
    const tail = groups.pop()
    const smallest = groups[groups.length - 1]
    smallest.area = smallest.area + '+' + tail.area
    smallest.findings.push(...tail.findings)
  }
  return { shared: shared.length ? { area: 'shared', findings: shared } : null, groups }
}

function uniq(list) {
  return [...new Set(list.filter(Boolean))]
}

function key(f) {
  return f.key || (f.cardId + ':' + f.summary)
}
// args: { routes?, journeys?, projectType?, matrix?, cap?: 3, severity?: 'minor'|'major'|'blocker',
//         task?, project?, board?, base?, scope?: string (what to test, prose) }
const A = args || {}
const cap = Math.max(1, Math.min(6, A.cap || 3))
const threshold = A.severity || 'minor'

phase('Prepare')
const prep = await agent(withPreamble(
  `Prepare this checkout for a review loop.\n` +
  `1. Report the current branch and the vitrinka project the repo is bound to (\`vitrinka status\` / the repo's .vitrinka descriptor).\n` +
  `2. Read \`.claude/vitrinka-workflows.json\` if it exists and return it as \`override\` ({} when absent).\n` +
  `3. Decide projectType (web | expo | cli | other) from the repo.\n` +
  `4. Start the app for this branch the way CLAUDE.md prescribes (devbox when available, else locally); wait until it answers; return the reachable base URL${A.base ? ` (requested: ${A.base})` : ''}.\n` +
  `5. Task binding: ${A.task ? `the run is bound to task ${A.task}.` : 'if the checkout carries a vt-<id> task, return it; otherwise leave task empty (the QA record lands on the project\'s Unplanned runs epic).'}\n` +
  `Never create tasks, boards or commits here.`
), { label: 'prepare', phase: 'Prepare', schema: PREPARE_SCHEMA })
if (!prep) throw new Error('review-loop: prepare failed')
const task = A.task || prep.task || ''
const project = A.project || prep.project || ''
const override = prep.override || {}
const { type, matrix, checklist, exclude } = resolveMatrix(A.projectType || prep.projectType, Object.assign({}, override, A.matrix ? { matrix: A.matrix } : {}))
if (!matrix.length) throw new Error(`review-loop: project type ${type} has no device matrix — nothing to shoot`)
const boardSlug = A.board || override.board || `${prep.branch.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}-review-loop`
log(`review-loop: ${type} on ${prep.branch} at ${prep.baseUrl} (${prep.where}), ${matrix.length} devices, cap ${cap}, threshold ${threshold}`)

phase('Map')
let terrain = A.routes ? { routes: A.routes, journeys: A.journeys || [] } : null
if (!terrain) {
  try {
    terrain = await workflow('vitrinka:map', { scope: 'app', project, task, push: false })
  } catch (e) {
    log(`review-loop: map workflow unavailable (${e && e.message}); inventorying inline`)
    terrain = await agent(withPreamble(
      'Read-only: inventory every route/screen a user can reach in this repo (path, title, implementing file, auth, how to reach it with data on screen) and the 3-8 journeys a real user walks. Prefer the repo\'s own route tables and navigators over file-name guesses.'
    ), { label: 'inventory', phase: 'Map', agentType: 'Explore', schema: TERRAIN_SCHEMA })
  }
}
if (!terrain || !terrain.routes || !terrain.routes.length) throw new Error('review-loop: no routes to shoot')
const allRoutes = terrain.routes.filter(r => !exclude.some(x => r.path === x || r.path.startsWith(x.replace(/\*$/, ''))))
const allJourneys = terrain.journeys || []
log(`review-loop: ${allRoutes.length} routes, ${allJourneys.length} journeys`)

const captureRoot = (pass, device) => `.vitrinka/screenshots/review-loop/pass-${pass}/${device}`
const devLine = d => d.width ? `${d.name} ${d.width}×${d.height}@${d.scale} ${d.input}${d.safeArea ? ' with safe-area insets emulated' : ''}` : `${d.name} (${d.platform} simulator ${d.sim})`
// A viewport device is shot in the browser and adopted with --file; a simulator
// device (expo matrix: platform, no width) is captured natively by the CLI.
const captureStep = (d, pass) => {
  const tail = `--label pass${pass}/${d.name}/<route-slug> --title "<title>" --note "<what is on screen>" --src <implementing file> --root ${captureRoot(pass, d.name)} --yes`
  return d.width
    ? `open it at exactly this viewport, wait for it to settle, scroll the whole page once so lazy content is present, then capture 2× and adopt it with \`vitrinka board capture web --file <png> --route <path> --device ${d.name} --viewport ${d.width}x${d.height}@${d.scale || 2} ${tail}\``
    : `open it in the ${d.sim} simulator through its deep link and capture it with \`vitrinka board capture ${d.platform} --open <deep link> --route <path> --device ${d.name} ${tail}\``
}
// The usertest runs on the matrix's first device when the matrix is all simulators.
const native = matrix.every(d => !d.width)
const utPlatform = native ? matrix[0].platform : 'web'
const utDevice = native ? matrix[0].name : 'desktop'
const utWhere = native ? `on the ${matrix[0].name} simulator (${matrix[0].sim})` : `on a desktop viewport and on a touch phone viewport (${matrix[0].name})`

let routes = allRoutes
let journeys = allJourneys
let regressList = []
const passes = []
let boardUrl = ''
let stoppedWithOpen = []

for (let pass = 1; pass <= cap; pass++) {
  const ph = `Pass ${pass}`
  phase(ph)
  const isFirst = pass === 1
  log(`${ph}: shooting ${routes.length} routes on ${matrix.length} devices, ${journeys.length} journeys`)

  const shooters = matrix.map(d => () => agent(withPreamble(
    `Shoot pass ${pass} of a review loop on device ${devLine(d)} against ${prep.baseUrl}.\n` +
    `Routes (shoot every one, with data on screen; a route needing setup says how):\n${JSON.stringify(routes)}\n` +
    `Read \`docs {topic: "guide:publish-capture"}\` first. For each route: ${captureStep(d, pass)}. On a touch device also capture one screen with a menu/sheet open when the route has one. Read each saved image back and re-shoot a blank or half-loaded one. Return every shot; a route you could not reach is a \`problems\` line naming why.`
  ), { label: `shoot:${d.name}`, phase: ph, schema: SHOOT_SCHEMA }))

  const tester = () => agent(withPreamble(
    `Exploratory usertest, pass ${pass}, against ${prep.baseUrl} ${utWhere}.\n` +
    `Journeys to walk:\n${JSON.stringify(journeys)}\n${A.scope ? `Focus: ${A.scope}\n` : ''}` +
    `Follow the vitrinka usertest skill's lane 2 (\`vitrinka qa usertest start${task ? ` --task ${task}` : ''} --app ${type} --platform ${utPlatform} --device ${utDevice} --yes\`, then \`case\`, captures, \`verdict\`, and \`finish --bugs direct --yes\`). One case per journey per device; a fail carries --note with the exact contract broken and the implementing files. Understand before judging: read the code behind a suspicious behaviour. Never touch production tenants. Return the cases with verdicts and the bug task urls \`finish\` printed.`
  ), { label: 'usertest', phase: ph, schema: USERTEST_SCHEMA })

  const results = (await parallel([...shooters, tester])).filter(Boolean)
  const shots = results.filter(r => r.shots)
  const ut = results.find(r => r.cases) || { cases: [], bugs: [] }
  const shotCount = shots.reduce((n, s) => n + s.shots.length, 0)
  if (!shotCount) throw new Error(`${ph}: no screenshots captured — the app or the browser is not reachable`)

  const pub = await agent(withPreamble(
    `Compose pass ${pass} of a review loop onto ONE run board (slug ${boardSlug}${project ? `, project ${project}` : ''}${task ? `, task ${task}` : ''}).\n` +
    `Sets captured this pass (one capture root per device): ${JSON.stringify(shots.map(s => ({ device: s.device, root: captureRoot(pass, s.device), shots: s.shots })))}.\n` +
    `Usertest record: ${JSON.stringify({ qaTaskUrl: ut.qaTaskUrl, boardUrl: ut.boardUrl, cases: ut.cases })}.\n` +
    `Structure: section "Pass ${pass}" with one row per device in matrix order, shots ordered by route; a summary card at the section head naming the pass, the device matrix, the shot count and the usertest verdict tally, with a portal link to the usertest board when it is a different board. Earlier pass sections stay untouched. Return the board's server url, its slug, the section title and every shot card id with its route and device.`
  ), { label: 'publish', phase: ph, agentType: 'vitrinka:vitrinka-publisher', schema: PUBLISH_SCHEMA })
  if (!pub) throw new Error(`${ph}: publishing failed`)
  boardUrl = pub.boardUrl

  const reviewers = matrix.map(d => () => agent(withPreamble(
    `Local review (you are the reviewer, no server-side judge) of pass ${pass}, device ${d.name}, on board ${pub.boardSlug} (${pub.boardUrl}).\n` +
    `Cards in scope: ${JSON.stringify(pub.cards.filter(c => !c.device || c.device === d.name))}.\n` +
    `Read \`review_brief${project ? ` {project: "${project}"}` : ''}\` and judge against it PLUS this checklist:\n- ${checklist.join('\n- ')}\n` +
    `Read every card's pixels with get_card_image before filing anything (cross-cutting problems show only across the set). File ONE \`annotate {board, agent: "claude-code", items: [...]}\` batch: each item keyed \`p${pass}-${d.name}-<n>\`, region measured on the source pixels, category = the rule id, severity blocker|major|minor, and detail naming the implementing files and what correct looks like. Sort defects as kind "finding" and taste as "suggestion".\n` +
    (regressList.length ? `Regression check — these findings were fixed last pass; for each, look at the same route on this device and report fixed true/false with a note:\n${JSON.stringify(regressList.map(f => ({ key: f.key, id: f.id, route: f.route, summary: f.summary })))}\n` : '') +
    `Return every finding with its annotation id from the receipt, its route, device, an \`area\` (the component or route the fix lives in) and the files it names.`
  ), { label: `review:${d.name}`, phase: ph, schema: FINDINGS_SCHEMA }))
  const reviews = (await parallel(reviewers)).filter(Boolean)
  const seen = new Set()
  const filed = reviews.flatMap(r => r.findings).filter(f => { const k = key(f); if (seen.has(k)) return false; seen.add(k); return true })
  const regressions = reviews.flatMap(r => r.regressions || [])
  const regressed = regressList.filter(f => regressions.some(r => r.key === f.key && r.fixed === false))
  const functional = ut.cases.filter(c => c.verdict === 'fail').map((c, i) => ({
    key: `p${pass}-usertest-${i + 1}`, route: '', device: c.device || 'desktop', area: (c.files && c.files[0]) || 'functional',
    kind: 'finding', severity: 'major', rule: 'functional', summary: `${c.title}: ${c.note || 'failed'}`, files: c.files || [],
  }))
  const fixList = [...autoAcceptable(filed, threshold), ...functional, ...regressed]
  const parked = filed.length - autoAcceptable(filed, threshold).length
  passes.push({ pass, shots: shotCount, filed: filed.length, functionalFails: functional.length, regressed: regressed.length, toFix: fixList.length, parked })
  log(`${ph}: ${shotCount} shots, ${filed.length} findings filed (${parked} left staged for the human), ${functional.length} functional fails, ${regressed.length} regressions`)

  if (!fixList.length) { log(`${ph}: clean — loop converged`); break }
  if (pass === cap) { stoppedWithOpen = fixList; log(`${ph}: cap reached with ${fixList.length} findings open — they stay on the board, unfixed (raise cap to continue)`); break }

  const ids = uniq(fixList.map(f => f.id))
  if (ids.length) {
    await agent(withPreamble(
      `Accept these agent findings on board ${pub.boardSlug} on the user's standing instruction for this loop (auto-accept ${threshold}+ defects): ids ${JSON.stringify(ids)}.\n` +
      `Door: POST /api/v1/boards/${pub.boardSlug}/annotations/agent-verdict with body {"action":"accept","ids":[...]} — bearer token from $VITRINKA_TOKEN or \`vitrinka auth token\`, fed through stdin as a header file, never inline in argv. Return the response status and the accepted count.`
    ), { label: 'accept', phase: ph, effort: 'low' })
  }

  const { shared, groups } = groupByArea(fixList, 4)
  const fixPrompt = g => withPreamble(
    `Fix these accepted findings from pass ${pass} of the review loop (area: ${g.area}) in this worktree, on branch ${prep.branch}, app at ${prep.baseUrl}:\n${JSON.stringify(g.findings)}\n` +
    `Rules: touch only the files a finding names or the component that owns the defect; other fixers are working other areas in this same checkout right now, so never reformat, rename or move shared code${g.area === 'shared' ? ' (you ARE the shared fixer — the others wait for you)' : ''}. For each finding with an annotation id: \`set_status working\` when you start, fix, then \`reply\` with the commit and \`set_status in_review\`. Commit per area with a message naming the finding keys. A finding you cannot fix without a design decision is skipped with why — never guess a redesign. Return fixed keys, skipped keys, touched routes and files, commits.`
  )
  let fixResults = []
  if (shared) fixResults.push(await agent(fixPrompt(shared), { label: 'fix:shared', phase: ph, schema: FIX_SCHEMA }))
  fixResults.push(...await parallel(groups.map(g => () => agent(fixPrompt(g), { label: `fix:${g.area}`, phase: ph, schema: FIX_SCHEMA }))))
  fixResults = fixResults.filter(Boolean)
  const fixedKeys = new Set(fixResults.flatMap(r => r.fixed))
  const skipped = fixResults.flatMap(r => r.skipped)
  const touchedRoutes = uniq(fixResults.flatMap(r => r.touchedRoutes))
  const touchedFiles = uniq(fixResults.flatMap(r => r.touchedFiles))
  log(`${ph}: ${fixedKeys.size} fixed, ${skipped.length} skipped, ${touchedFiles.length} files, ${touchedRoutes.length} routes touched`)

  const gate = await agent(withPreamble(
    `Gate the fixes of pass ${pass}: run the repo's type/build/test gates from CLAUDE.md (the strict TS gate, the Go build, the unit suites; the e2e suite only for the specs covering ${JSON.stringify(touchedRoutes)}) where CLAUDE.md says they run. A failure caused by this pass's commits (${JSON.stringify(fixResults.flatMap(r => r.commits || []))}) you repair in place and commit; a failure that predates them is reported, not fixed. Restart the app if the fixes need it and confirm ${prep.baseUrl} answers. Return green, what ran, and failures.`
  ), { label: 'gate', phase: ph, schema: GATE_SCHEMA })
  if (!gate || !gate.green) log(`${ph}: gate red — ${JSON.stringify((gate && gate.failures) || ['no result'])}; the next pass shoots anyway so the board shows the state`)

  regressList = fixList.filter(f => fixedKeys.has(f.key))
  const openRoutes = uniq([...touchedRoutes, ...fixList.filter(f => !fixedKeys.has(f.key)).map(f => f.route)])
  routes = allRoutes.filter(r => openRoutes.some(p => p && (r.path === p || r.path.startsWith(p))))
  if (!routes.length) routes = allRoutes.filter(r => touchedFiles.some(f => r.file && f === r.file))
  if (!routes.length) routes = allRoutes
  journeys = allJourneys.filter(j => j.steps.some(s => openRoutes.some(p => p && s.includes(p))))
  if (!journeys.length) journeys = allJourneys.filter(j => ut.cases.some(c => c.verdict === 'fail' && c.title === j.title))
  if (!journeys.length && functional.length) journeys = allJourneys
  log(`${ph}: next pass reshoots ${routes.length} routes, reruns ${journeys.length} journeys`)
}

return {
  boardUrl,
  branch: prep.branch,
  task,
  passes,
  converged: stoppedWithOpen.length === 0,
  open: stoppedWithOpen.map(f => ({ key: f.key, id: f.id, summary: f.summary })),
}
